### PR TITLE
[shared_preferences] Fix initialization race

### PR DESCRIPTION
**Pull request by stuartmorgan**
During the NNBD transition, the structure of the completer logic in the initialization flow was incorrectly changed to set the field after an `await` instead of immediately.

Also updates the error handling to handle `Error` the same way it currently handles `Exception`, which this change surfaced.

Fixes https://github.com/flutter/flutter/issues/42407

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by tarrinneal** [comment]
Interesting. The setPrefix method is getting an unimplemented error on some tests now.

**Comment by stuartmorgan** [comment]
> Interesting. The setPrefix method is getting an unimplemented error on some tests now.

I missed that only half of the tests were in the group that sets an instance during `setUp` (making my change to instance affect other tests). Fixing now.

**Review by tarrinneal — APPROVED** [review]
I'm surprised this worked at all before.

**Comment by stuartmorgan** [comment]
> I'm surprised this worked at all before.

Well, to hit this race you have to call `getInstance` again between *the very first time* in the app that you call `getInstance` and the initial `_getSharedPreferencesMap` call completing, which is likely to be a very small window of time. And then for it to be an actual problem, you have to either keep both of those instances around long term, or you have to keep (the wrong) one of them long term, but then also sometimes make new `getInstance` calls.

I can't image that's a common use pattern.

**Pull request merged**
