### PR TITLE
[google_maps_flutter] Add support for version 8 of the iOS SDK

### PR DESCRIPTION
**Pull request by stuartmorgan**
- Increases the max allowed SDK version to 8.x
- Adds a new iOS 14 example app, per [the documented test structure/plan](https://github.com/flutter/packages/blob/main/packages/google_maps_flutter/google_maps_flutter_ios/example/README.md)
- Moves recently added XCUITests to the iOS 11 example app, where they should have been (per doc linked above). I missed this when reviewing the addition, and noticed that it was incorrectly in the iOS 13 example while duplicating the iOS 13 example for the iOS 14 version.

Fixes https://github.com/flutter/flutter/issues/138972

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
It's probably easiest to review this as individual commits; the big commit called "Add iOS 14" is just an exact copy of `example/ios13` to `example/ios4` so shouldn't need detailed review.

**Review by jmagman — APPROVED** [review]
Cross-listing https://github.com/flutter/flutter/issues/86820 and https://github.com/flutter/packages/pull/3757

**Comment by stuartmorgan** [comment]
I hit some deprecation warning failures in CI that I didn't find locally, and it turns out that it's because locally I only resolved to 8.2 (presumably for cache reasons), but 8.3 added a new API and deprecated the ones it replaced. If we have OOB failures from that happening in the future we could restrict the range in the podspec to only allow minor versions we have tested, rather than just major ones, but AFAIK it's never hit us before so for now I'll err on the side of keeping a lenient range.

**Comment by arthurmonteiroalvesmelo** [comment]
Hey @stuartmorgan 

in file (packages/google_maps_flutter/google_maps_flutter_ios/example/ios14/README.md)

The actual text is:
```
## Versions

This example requires iOS 13, so will select a 7.x GoogleMaps SDK version.
```

But, the right is:
```
## Versions

This example requires iOS 14, so will select a 8.x GoogleMaps SDK version.
```

right?

**Comment by stuartmorgan** [comment]
Yes, that's a copy/paste mistake.

**Pull request merged**
