### PR TITLE
[Pigeon] Add one_language flag to pigeon

### PR DESCRIPTION
**Pull request by zhenqiu1101**
one_language flag allows pigeon to only generate for one platform.

*List which issues are fixed by this PR. You must list at least one issue.*
This is an internal request. No issue to link.

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the `#hackers-new` channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by gaaclarke — CHANGES_REQUESTED** [review]
This looks great.  We should have a test that invokes with `--one_language` though since if this broke it would be huge.  I think we might be able to do something like `$run_pigeon --input pigeons/message.dart --one_language --java_out stdout | grep "public class Message"` in the `run_tests.sh`.  Want to give it a look?  I can implement it you want, just let me know.

**Comment by zhenqiu1101** [comment]
> This looks great. We should have a test that invokes with `--one_language` though since if this broke it would be huge. I think we might be able to do something like `$run_pigeon --input pigeons/message.dart --one_language --java_out stdout | grep "public class Message"` in the `run_tests.sh`. Want to give it a look? I can implement it you want, just let me know.

Done. PTAL. I'm not familiar with the run_tests.sh. Please let me know if I need to change anything.

**Review by gaaclarke — APPROVED** [review]
Yep, this looks great.  I'd just move it to it's own function just like `test_running_without_arguments`.  I don't think your if statement is technically needed because of the `set -e` at the top of the file FWIW.

**Comment by gaaclarke** [comment]
Oh also, pipe the output to /dev/null please.

**Pull request merged**
