### PR TITLE
[image_picker] Add missing entitlements to macOS example

### PR DESCRIPTION
**Pull request by stuartmorgan**
When endorsing macOS and adding the example app, I forgot to add the required entitlement, so the example didn't work.

The actual fix is the entitlements file; the Runner.xc* changes are auto-generated by running `flutter build macos`; usually we do that before landing examples but clearly I didn't remember to actually run the example when endorsing in this case...

Fixes https://github.com/flutter/flutter/issues/134817

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
No changelog: This only affects running locally, and is doing what the README already says to do.

**Comment by stuartmorgan** [comment]
test-exempt: will be automatically covered once necessary test infrastructure lands

**Review by tarrinneal — APPROVED** [review]
TAMNTM

**Comment by stuartmorgan** [comment]
Re-running `repo_checks` doesn't seem to be picking up the override at the moment for some reason. I'm going to force-land, but I'll look into that later today or next week.

**Pull request merged**
