### PR TITLE
[go_router] Avoid unnecessary null checks

### PR DESCRIPTION
**Pull request by ricardodalarme**
## Description

The public static analysis complained about these errors and deducted the final package score on pub.dev

image

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by chunhtai — COMMENTED** [review]
Thanks for submitting the pr, the change looks good

can you bump the version so that the pub dev will reevaluate the score? 

also @stuartmorgan, we missed this because of unnecessary_null_comparison is ignored in the analysis_options.yaml. Do you think it can be unignored now?

**Comment by stuartmorgan** [comment]
> also @stuartmorgan, we missed this because of unnecessary_null_comparison is ignored in the analysis_options.yaml. Do you think it can be unignored now?

We've been following flutter/flutter policy on this lint, which was to leave it disabled for as long as we supported non-null-safe mode; it is still the case that all of our packages support running in non-null-safe mode. I think "when Dart 3 reaches Flutter stable" would be a better point to finally drop it from the analysis options. (Arguably we should leave it until the minimum Flutter version of all of our packages is whatever that version is, but it's definitely a diminishing-returns-over-time option, so I'd be fine with removing it a little early.)

**Comment by stuartmorgan** [comment]
Relatedly: do you actually want to remove these checks? This is prioritizing pub score over users running in non-strong mode getting good error messages.

**Comment by chunhtai** [comment]
Thanks @stuartmorgan for the explanation. I think for this two instance it is probably fine. I don't think these can be null even from non-null safe customers' code.

**Comment by chunhtai** [comment]
also It feels like we should drop the check unnecessary_null_comparison when doing public static analysis if it is unsafe to apply it due to non-null safe code in the wild.

**Comment by ricardodalarme** [comment]
Done @chunhtai, thanks you very much for being open to new PRs ❤️

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Comment by stuartmorgan** [comment]
> It feels like we should drop the check unnecessary_null_comparison when doing public static analysis

The "we" in that context would be the pana maintainers; we don't control this at a package level. You could file an issue about it, but with Dart 3 on the horizon I would be surprised if they dropped it.

> if it is unsafe to apply it due to non-null safe code in the wild

I don't know that I would say "unsafe"; something is going to explode if someone violates the API contact, the assets just make the resulting error clear and well defined.

But I do think it's odd that pana penalizes something that [the NNBD docs](unnecessary_null_comparison) explicitly list as a valid choice.

**Review by hangyujin — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
@ricardodalarme can you rebase off the latest main?

**Comment by ricardodalarme** [comment]
Done! @chunhtai 🙂

**Pull request merged**
