### PR TITLE
[go_router] Fix analyzer in test

### PR DESCRIPTION
**Pull request by camsim99**
Analyzer was failing with https://cirrus-ci.com/task/5402519338221568?logs=analyze#L427-L425. This fixes the warnings.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by camsim99** [comment]
cc @angjelkom

**Comment by ditman** [comment]
I think you need to `//ignore: unnecessary_non_null_assertion` in the offending line, until the change rolls to flutter stable? Otherwise the analyze step is going to complain?

**Comment by camsim99** [comment]
> I think you need to //ignore: unnecessary_non_null_assertion in the offending line, until the change rolls to flutter stable? Otherwise the analyze step is going to complain?

Oh I see. Let me try that.

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/plugins/pull/6847/files for the standard pattern we're using to handle the framework making things non-nullable.

(Once I merge flutter/plugins into flutter/packages, we'll pre-analyze all our packages in flutter/flutter, not just the plugin packages, so this kind of thing will get pre-fixed like the plugins were, rather than break our roller.)

**Review by chunhtai — APPROVED** [review]
LGTM, thanks for fixing this.

**Pull request merged**
