### PR TITLE
[pigeon] Fix missed casting of not nullable Dart int to Kotlin long

### PR DESCRIPTION
**Pull request by ycherniavskyi**
Kotlin generator creates source code that throws on executing because of missed necessary casting.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by tarrinneal — CHANGES_REQUESTED** [review]
Could you expand your tests to include the casting of all types and remove the 'header' from the titles of both tests? At the moment the test is technically not appropriately named for the new casting line you added.

I think this was passing our integration tests already is concerning. We may to to expand them to cover this instance.

Overall a solid pr. Thank you.

**Comment by stuartmorgan** [comment]
> We may to to expand them to cover this instance.

This PR should definitely include an integration test that covers the failing case. Any fix for a runtime failure that we find going forward should include a corresponding integration test at the minimum (and if it's useful, relevant unit tests).

**Comment by stuartmorgan** [comment]
@ycherniavskyi Are you planning on adding tests per the discussion above?

**Comment by ycherniavskyi** [comment]
@stuartmorgan yes sure, but I am waiting to merge #2997 to reabase over it and add tests then.

**Comment by tarrinneal** [comment]
> @stuartmorgan yes sure, but I am waiting to merge #2997 to reabase over it and add tests then.

It has now been merged!

**Comment by ycherniavskyi** [comment]
@tarrinneal great, so I am going to rebase and add tests today.

**Comment by ycherniavskyi** [comment]
@tarrinneal rebased and consolidated unit tests with properties naming style seen in #3066.

As for the integration tests, then, it seems they were already added within #3066, but disabled for Android Kotlin implementation. This PR resole the https://github.com/flutter/flutter/issues/115914 that was mentioned in https://github.com/flutter/flutter/issues/118726, which is the reason for some tests skipped for Android Kotlin implementation. So this PR for sure affords to remove some of this skip.

**Comment by stuartmorgan** [comment]
> So this PR for sure affords to remove some of this skip.

Have you removed the relevant skips and verified locally that the tests now pass? If so, that change should be in this PR.

**Comment by ycherniavskyi** [comment]
@stuartmorgan do it in 82ab8e8da95b12ae4fa56c126f8201cdd0a87441. Also, merge the last main and update gen files.

**Comment by tarrinneal** [comment]
>  merge the last main and update gen files.

Can you run the formatter cl tool with

`dart pub global run flutter_plugin_tools format --packages pigeon`

to clean up the generated files and upload them again.

**Comment by ycherniavskyi** [comment]
@tarrinneal done.

**Review by tarrinneal — APPROVED** [review]

**Comment by tarrinneal** [comment]
> @tarrinneal done.
great job, will be auto merged once testing is complete!

**Review by stuartmorgan — APPROVED** [review]

**Pull request merged**
