### PR TITLE
Increase the timeout to find fuchsia devices.

### PR DESCRIPTION
**Pull request by godofredoc**
https://github.com/flutter/flutter/issues/42241

### CODE REVIEW

**Comment by dnfield** [comment]
Are we confident 2 minutes is enough?

**Comment by godofredoc** [comment]
Not very confident, I just ran a couple of times locally.

**Comment by dnfield** [comment]
Should we just push it up to 5 minutes? That should be enough time even on a slow machine.

**Comment by godofredoc** [comment]
Sounds good, let me send an update

**Pull request merged**
