### PR TITLE
Add flutter markdown to packages in preparation for deprecation of flutter_markdown package.

### PR DESCRIPTION
**Pull request by kf6gpe**
@Hixie @abarth for review. Thanks!

### CODE REVIEW

**Comment by vlidholt** [comment]
You have my blessing to merge this. :)

**Comment by westy92** [comment]
You have my blessing to merge as well! 🎉

**Comment by dnfield** [comment]
This will have to get merged with the latest form master to build properly - we had to change the CI image.

**Comment by goderbauer** [comment]
I am going to close this since it is over a year old.

**Pull request closed without merging**
