### PR TITLE
[image_picker] Fix auto update sub deps

### PR DESCRIPTION
**Pull request by zeucxb**
When releasing a new version using minor auto-update(^) with the current version pattern on (image_picker_android/ios/etc) it will always get the last version.

We had a conflict with kotlin 1.8 added on image_picker_android 0.8.6+15 and even changing the image_picker version I only solved it with dependencies_override.

I don't think that a kotlin version change should be a minor but with the current version pattern we need fixed versions.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by zeucxb** [comment]
I didn't check but maybe other packages with sub dependencies are facing the same issue.

**Comment by zeucxb** [comment]
I signed the CLA after the check fail, can I re-run the CLA check?

**Comment by stuartmorgan** [comment]
> When releasing a new version using minor auto-update(^) with the current version pattern on (image_picker_android/ios/etc) it will always get the last version.

That is the desired behavior. Closing as we do not want pinning.

> We had a conflict with kotlin 1.8 added on image_picker_android 0.8.6+15 [...] I don't think that a kotlin version change should be a minor

Please file an issue about the breakage, with details, so that it can be evaluated.

> I only solved it with dependencies_override.

Pinning a version in your own application does not require dependency overrides unless you are pinning to a version that is not compatible with constraints. You can simply add a pinned dependency.

**Comment by zeucxb** [comment]
@stuartmorgan any version on image_picker gets always the last version of image_picker_android even with different Kotlin versions. Is this the desired behavior?

**Comment by stuartmorgan** [comment]
> any version on image_picker gets always the last version of image_picker_android even with different Kotlin versions. Is this the desired behavior?

As I said above, getting the latest version is the desired behavior, and if there is a change to a sub-package that is breaking it should be versioned as such. Without an issue report explaining in detail the specific Kotlin problem you are having I don't know if having that Kotlin change be a non-major change to the sub-package is desired behavior.

**Pull request closed without merging**
