### PR TITLE
[flutter_markdown] Footnote support

### PR DESCRIPTION
**Pull request by dawidope**
Support for footnote which was introduced in `markdown` 7.1.0 which is used in `flutter_markdown` package.

It allows to use the newest version of markdown without overriding it to 7.0.0 because of missing `section` tag handling.

Issue: https://github.com/flutter/flutter/issues/127425

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]
LGTM once the Linux build failure is sorted

**Comment by domesticmouse** [comment]
PTAL @tarrinneal

**Comment by dawidope** [comment]
Hi, I found the issue during adding it to my application. To support superscript the font which is used has to support `sups` feature. On Android where the default font is `Roboto` which doesn't support `sups` nothing changes. So there are two solutions:

- adding additional parameter to style sheet: `superscriptFontFeatureTag` which can be set by user, in the case of `Roboto` we can use `numr`. It isn't `sups` because it is aligned to the top of the line (not a few pixels above) but still looks better than normal font
- replacing font feature by `Transform.translate` with `WidgetSpan`. 

I have prepared demo with basic implementation. In the case of using custom font feature everything is ready. Using Transform.translate is quite buggy because it doesn't support `selectable` parameter.

Demo with `Roboto` font:
image

**Comment by tarrinneal** [comment]
> PTAL @tarrinneal

merged mid review, lol. 

no concerns about the comment from @dawidope ?

**Pull request merged**
