### PR TITLE
Revert "Roll Flutter from c85fa6abf4ff to 7eebe2992aba (#6836)"

### PR DESCRIPTION
**Pull request by ditman**
This reverts commit 11e192a86db3e3a59e532f84ee5e2f012774df9f.

Revert "Roll Flutter from c85fa6abf4ff to 7eebe2992aba (26 revisions) (#6836)"

Because of Issue:

* https://github.com/flutter/flutter/issues/125090

Example of broken build:

* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20android_device_tests_shard_2%20master/1089/overview (there's 7 retries)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Review by camsim99 — APPROVED** [review]

**Comment by reidbaker** [comment]
Do we know what code specifically is at issue?

**Comment by ditman** [comment]
@reidbaker the tests are failing in Firebase Test Lab (application crashed), where the following packages had errors:

```
  packages/google_maps_flutter/google_maps_flutter_android:
    example/integration_test/latest_renderer_test.dart failed tests
    example/integration_test/legacy_renderer_test.dart failed tests
```

A copy of one of the [FTL stack traces](https://firebase.corp.google.com/project/flutter-infra-staging/testlab/histories/bh.8eb89ae93eb3eb36/matrices/7137789491288084022/executions/bs.3e4310cdb942f13a/issues) (they all look similar-ish):

```
pid: 24713, tid: 24713, name: oglemapsexample  >>> io.flutter.plugins.googlemapsexample <<<
uid: 10261
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1725)] Check failed: fml::jni::CheckException(env). '
    x0  0000000000000000  x1  0000000000006089  x2  0000000000000006  x3  0000007fffb3b410
    x4  6d602e6c716e6573  x5  6d602e6c716e6573  x6  6d602e6c716e6573  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  0000007f446d09e0  x10 0000000000000001  x11 0000007f44712370
    x12 0000000000003405  x13 000000000000007e  x14 0000007fffb3a2e0  x15 0000001eed7102a8
    x16 0000007f4477fd50  x17 0000007f4475aeb0  x18 0000007f4d4f6000  x19 0000000000006089
    x20 0000000000006089  x21 00000000ffffffff  x22 b400007d61a2af50  x23 0000007d11a7ab78
    x24 0000000000000000  x25 0000000000000920  x26 0000000000000000  x27 0000007fffb3b708
    x28 00000000000000f9  x29 0000007fffb3b490
    lr  0000007f447021c8  sp  0000007fffb3b3f0  pc  0000007f447021f4  pst 0000000000001000
backtrace:
      #00 pc 00000000000531f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: dc4001c2ef2dfc23467040797a96840c)
      #01 pc 0000000001cefb1c  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #02 pc 0000000001d1a510  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #03 pc 0000000001cfebcc  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #04 pc 000000000249648c  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #05 pc 00000000021419f8  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #06 pc 00000000021414bc  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #07 pc 0000000002140360  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #08 pc 0000000002140d2c  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #09 pc 0000000002142914  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #10 pc 00000000021407c8  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #11 pc 0000000002140564  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #12 pc 0000000001d1b10c  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #13 pc 0000000001d20c9c  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
      #14 pc 0000000000011178  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+808) (BuildId: 0b4a793fa8045c04066d988c68bac8bb)
      #15 pc 000000000015f39c  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44) (BuildId: 48435380059f74cde3db281c74576169)
      #16 pc 00000000001a9094  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+116) (BuildId: 830f4c055299aae1a5ce50ac9bc9d9d9589cb804)
      #17 pc 000000000020a910  /apex/com.android.art/lib64/libart.so (nterp_helper+5648) (BuildId: 289d75599f6112d5757113220599e90b)
      #18 pc 00000000004999ee  /system/framework/framework.jar (android.os.MessageQueue.next+34)
      #19 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 289d75599f6112d5757113220599e90b)
      #20 pc 00000000004989dc  /system/framework/framework.jar (android.os.Looper.loopOnce+12)
      #21 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 289d75599f6112d5757113220599e90b)
      #22 pc 00000000004991ca  /system/framework/framework.jar (android.os.Looper.loop+162)
      #23 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 289d75599f6112d5757113220599e90b)
      #24 pc 00000000001bcfea  /system/framework/framework.jar (android.app.ActivityThread.main+202)
      #25 pc 0000000000457e00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: 289d75599f6112d5757113220599e90b)
      #26 pc 000000000048c038  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1560) (BuildId: 289d75599f6112d5757113220599e90b)
      #27 pc 000000000048b9f8  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+48) (BuildId: 289d75599f6112d5757113220599e90b)
      #28 pc 0000000000099148  /system/framework/arm64/boot.oat (art_jni_trampoline+120) (BuildId: f2624dff261ac721c71496a318ad91b6e6cd0231)
      #29 pc 000000000020a2b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: 289d75599f6112d5757113220599e90b)
      #30 pc 0000000000404f66  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
      #31 pc 00000000007be5ac  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+3228) (BuildId: 830f4c055299aae1a5ce50ac9bc9d9d9589cb804)
      #32 pc 0000000000457e00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: 289d75599f6112d5757113220599e90b)
      #33 pc 000000000058bbc4  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+912) (BuildId: 289d75599f6112d5757113220599e90b)
      #34 pc 0000000000609af8  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+172) (BuildId: 289d75599f6112d5757113220599e90b)
      #35 pc 00000000000bcce8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120) (BuildId: 48435380059f74cde3db281c74576169)
      #36 pc 00000000000c8bf8  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+840) (BuildId: 48435380059f74cde3db281c74576169)
      #37 pc 0000000000002560  /system/bin/app_process64 (main+1280) (BuildId: 6f97a590777bd06f31784c7272763a35)
      #38 pc 000000000004b600  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+96) (BuildId: dc4001c2ef2dfc23467040797a96840c)
```

Digging in the [ADB logs](https://firebase.corp.google.com/project/flutter-infra-staging/testlab/histories/bh.8eb89ae93eb3eb36/matrices/7137789491288084022/executions/bs.3e4310cdb942f13a/logs), searching for "Fatal":

```
06-01 12:30:42.777 22214 22214 E flutter : [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
06-01 12:30:42.777 22214 22214 E flutter : 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:1121)
06-01 12:30:42.777 22214 22214 E flutter : 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:1192)
06-01 12:30:42.777 22214 22214 E flutter : 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1458)
06-01 12:30:42.777 22214 22214 E flutter : 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-01 12:30:42.777 22214 22214 E flutter : 	at android.os.MessageQueue.next(MessageQueue.java:335)
06-01 12:30:42.777 22214 22214 E flutter : 	at android.os.Looper.loopOnce(Looper.java:161)
06-01 12:30:42.777 22214 22214 E flutter : 	at android.os.Looper.loop(Looper.java:288)
06-01 12:30:42.777 22214 22214 E flutter : 	at android.app.ActivityThread.main(ActivityThread.java:7918)
06-01 12:30:42.777 22214 22214 E flutter : 	at java.lang.reflect.Method.invoke(Native Method)
06-01 12:30:42.777 22214 22214 E flutter : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-01 12:30:42.777 22214 22214 E flutter : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
06-01 12:30:42.777 22214 22214 E flutter : 
06-01 12:30:42.777 22214 22214 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1725)] Check failed: fml::jni::CheckException(env). 
00-00 00:00:00.000     0     0 ? (none)  : --------- beginning of crash
06-01 12:30:42.777 22214 22214 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 22214 (oglemapsexample), pid 22214 (oglemapsexample)
06-01 12:30:42.778 18754 20775 I Tips_SettingControllerP: tipsId = tips_watch_safety
```

Sooo... the Platform View for the Google Maps example/integration test app is not being initialized correctly?

**Comment by ditman** [comment]
(If this is a change in the google maps SDK, this revert may also fail. Waiting for the results of "Linux_android android_device_tests_shard_2 master" in the presubmit of this PR before landing anything)

**Comment by reidbaker** [comment]
> @reidbaker the tests are failing in Firebase Test Lab (application crashed), where the following packages had errors:
> 
> ```
>   packages/google_maps_flutter/google_maps_flutter_android:
>     example/integration_test/latest_renderer_test.dart failed tests
>     example/integration_test/legacy_renderer_test.dart failed tests
> ```
> 
> A copy of one of the [FTL stack traces](https://firebase.corp.google.com/project/flutter-infra-staging/testlab/histories/bh.8eb89ae93eb3eb36/matrices/7137789491288084022/executions/bs.3e4310cdb942f13a/issues) (they all look similar-ish):
> 
> ```
> pid: 24713, tid: 24713, name: oglemapsexample  >>> io.flutter.plugins.googlemapsexample <<<
> uid: 10261
> tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
> signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
> Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1725)] Check failed: fml::jni::CheckException(env). '
>     x0  0000000000000000  x1  0000000000006089  x2  0000000000000006  x3  0000007fffb3b410
>     x4  6d602e6c716e6573  x5  6d602e6c716e6573  x6  6d602e6c716e6573  x7  7f7f7f7f7f7f7f7f
>     x8  00000000000000f0  x9  0000007f446d09e0  x10 0000000000000001  x11 0000007f44712370
>     x12 0000000000003405  x13 000000000000007e  x14 0000007fffb3a2e0  x15 0000001eed7102a8
>     x16 0000007f4477fd50  x17 0000007f4475aeb0  x18 0000007f4d4f6000  x19 0000000000006089
>     x20 0000000000006089  x21 00000000ffffffff  x22 b400007d61a2af50  x23 0000007d11a7ab78
>     x24 0000000000000000  x25 0000000000000920  x26 0000000000000000  x27 0000007fffb3b708
>     x28 00000000000000f9  x29 0000007fffb3b490
>     lr  0000007f447021c8  sp  0000007fffb3b3f0  pc  0000007f447021f4  pst 0000000000001000
> backtrace:
>       #00 pc 00000000000531f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: dc4001c2ef2dfc23467040797a96840c)
>       #01 pc 0000000001cefb1c  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #02 pc 0000000001d1a510  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #03 pc 0000000001cfebcc  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #04 pc 000000000249648c  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #05 pc 00000000021419f8  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #06 pc 00000000021414bc  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #07 pc 0000000002140360  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #08 pc 0000000002140d2c  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #09 pc 0000000002142914  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #10 pc 00000000021407c8  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #11 pc 0000000002140564  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #12 pc 0000000001d1b10c  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #13 pc 0000000001d20c9c  /data/app/~~OcF6AKc2dNXRW95Fsnce_A==/io.flutter.plugins.googlemapsexample-shb-4wV3UWQ5ZedVd6uQZg==/lib/arm64/libflutter.so (BuildId: 25ff12d695fa20fccd9cbbc2ce9112ed48b96bb8)
>       #14 pc 0000000000011178  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+808) (BuildId: 0b4a793fa8045c04066d988c68bac8bb)
>       #15 pc 000000000015f39c  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44) (BuildId: 48435380059f74cde3db281c74576169)
>       #16 pc 00000000001a9094  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+116) (BuildId: 830f4c055299aae1a5ce50ac9bc9d9d9589cb804)
>       #17 pc 000000000020a910  /apex/com.android.art/lib64/libart.so (nterp_helper+5648) (BuildId: 289d75599f6112d5757113220599e90b)
>       #18 pc 00000000004999ee  /system/framework/framework.jar (android.os.MessageQueue.next+34)
>       #19 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 289d75599f6112d5757113220599e90b)
>       #20 pc 00000000004989dc  /system/framework/framework.jar (android.os.Looper.loopOnce+12)
>       #21 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 289d75599f6112d5757113220599e90b)
>       #22 pc 00000000004991ca  /system/framework/framework.jar (android.os.Looper.loop+162)
>       #23 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 289d75599f6112d5757113220599e90b)
>       #24 pc 00000000001bcfea  /system/framework/framework.jar (android.app.ActivityThread.main+202)
>       #25 pc 0000000000457e00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: 289d75599f6112d5757113220599e90b)
>       #26 pc 000000000048c038  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1560) (BuildId: 289d75599f6112d5757113220599e90b)
>       #27 pc 000000000048b9f8  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+48) (BuildId: 289d75599f6112d5757113220599e90b)
>       #28 pc 0000000000099148  /system/framework/arm64/boot.oat (art_jni_trampoline+120) (BuildId: f2624dff261ac721c71496a318ad91b6e6cd0231)
>       #29 pc 000000000020a2b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: 289d75599f6112d5757113220599e90b)
>       #30 pc 0000000000404f66  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
>       #31 pc 00000000007be5ac  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+3228) (BuildId: 830f4c055299aae1a5ce50ac9bc9d9d9589cb804)
>       #32 pc 0000000000457e00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: 289d75599f6112d5757113220599e90b)
>       #33 pc 000000000058bbc4  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+912) (BuildId: 289d75599f6112d5757113220599e90b)
>       #34 pc 0000000000609af8  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+172) (BuildId: 289d75599f6112d5757113220599e90b)
>       #35 pc 00000000000bcce8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120) (BuildId: 48435380059f74cde3db281c74576169)
>       #36 pc 00000000000c8bf8  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+840) (BuildId: 48435380059f74cde3db281c74576169)
>       #37 pc 0000000000002560  /system/bin/app_process64 (main+1280) (BuildId: 6f97a590777bd06f31784c7272763a35)
>       #38 pc 000000000004b600  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+96) (BuildId: dc4001c2ef2dfc23467040797a96840c)
> ```
> 
> Digging in the [ADB logs](https://firebase.corp.google.com/project/flutter-infra-staging/testlab/histories/bh.8eb89ae93eb3eb36/matrices/7137789491288084022/executions/bs.3e4310cdb942f13a/logs), searching for "Fatal":
> 
> ```
> 06-01 12:30:42.777 22214 22214 E flutter : [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
> 06-01 12:30:42.777 22214 22214 E flutter : 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:1121)
> 06-01 12:30:42.777 22214 22214 E flutter : 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:1192)
> 06-01 12:30:42.777 22214 22214 E flutter : 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1458)
> 06-01 12:30:42.777 22214 22214 E flutter : 	at android.os.MessageQueue.nativePollOnce(Native Method)
> 06-01 12:30:42.777 22214 22214 E flutter : 	at android.os.MessageQueue.next(MessageQueue.java:335)
> 06-01 12:30:42.777 22214 22214 E flutter : 	at android.os.Looper.loopOnce(Looper.java:161)
> 06-01 12:30:42.777 22214 22214 E flutter : 	at android.os.Looper.loop(Looper.java:288)
> 06-01 12:30:42.777 22214 22214 E flutter : 	at android.app.ActivityThread.main(ActivityThread.java:7918)
> 06-01 12:30:42.777 22214 22214 E flutter : 	at java.lang.reflect.Method.invoke(Native Method)
> 06-01 12:30:42.777 22214 22214 E flutter : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 06-01 12:30:42.777 22214 22214 E flutter : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
> 06-01 12:30:42.777 22214 22214 E flutter : 
> 06-01 12:30:42.777 22214 22214 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1725)] Check failed: fml::jni::CheckException(env). 
> 00-00 00:00:00.000     0     0 ? (none)  : --------- beginning of crash
> 06-01 12:30:42.777 22214 22214 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 22214 (oglemapsexample), pid 22214 (oglemapsexample)
> 06-01 12:30:42.778 18754 20775 I Tips_SettingControllerP: tipsId = tips_watch_safety
> ```
> 
> Sooo... the Platform View for the Google Maps example/integration test app is not being initialized correctly?

What I am hearing from this message is NO. Something in the hash is bad but we dont know what.

**Comment by ditman** [comment]
> What I am hearing from this message is NO. Something in the hash is bad but we dont know what.

@reidbaker let me try to bisect to a more specific framework revision.

**Comment by reidbaker** [comment]
My comment should not block this pr. I was just trying to get more actionable information in this pr if it was known. The links to evidence were good and the pr technically said what went wrong but I know if it was a submodule that was at fault we likely have another pr to roll back.

**Comment by ditman** [comment]
@reidbaker yep, I'll try to land this as soon as tests pass to get the tree back to green, the bisection is just for the fix forward. Do check the OG issue linked above, this might be an old issue that is now being consistently triggered by our maps example app

(More recent reports of the issue start around here: https://github.com/flutter/flutter/issues/125090#issuecomment-2116925842)

**Comment by camsim99** [comment]
BTW the issue for that error is https://github.com/flutter/flutter/issues/125090

**Pull request merged**
