### PR TITLE
Updated sample icons image

### PR DESCRIPTION
**Pull request by Musaddiq625**
Updated sample icons image
gallery_preview_1.0.0  -->  gallery_preview_1.0.1

Old
image

New:
gallery_preview_1 0 1

### CODE REVIEW

**Comment by MitchellGoodwin** [comment]
Just to be clear, besides the highlight on "alt" being removed, and the text for `arrow_2_circlepath_circle_fill` being on one line, are there any other changes my eyes are not picking up?

**Comment by Musaddiq625** [comment]
@MitchellGoodwin 
thanks for the response
yes, this is the only change

while I was finding the new icon, this was keep irritating me 😑
so I updated it myself 🤷🏻‍♂️😄🤞🏻

**Comment by MitchellGoodwin** [comment]
Image LGTM. @stuartmorgan looks like check fails because it needs the "override: no versioning needed" label, because the NEXT label is at the top of the changelog, though it looks like #5312 fixes that. Should this PR wait on #5312? They are somewhat related.

**Comment by stuartmorgan** [comment]
> looks like check fails because it needs the "override: no versioning needed" label, because the NEXT label is at the top of the changelog

The check fails because this needs a version change.

@Musaddiq625 in the future, please don't delete the checklist from the PR template; it's there for a reason. The checklist entry about versioning links to the docs that explain that this needs a version change, and why.

**Comment by stuartmorgan** [comment]
For reference: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version and especially the first entry in https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#faq

**Comment by stuartmorgan** [comment]
@Musaddiq625 Are you still planning on updating this PR to add the version and changelog? See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates for a link to tooling that will handle the details of doing that update.

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Pull request closed without merging**
