### PR TITLE
[webview_flutter_wkwebview] Add webkit interface for showing javascript alert message

### PR DESCRIPTION
**Pull request by jsharp83**
* In the iOS Webview environment, there are cases where Web calls System Popup with javascript.
* At this time, the message comes in the WKUIDelegate part.
   - https://developer.apple.com/documentation/webkit/wkuidelegate/1537406-webview
   - https://developer.apple.com/documentation/webkit/wkuidelegate/1536489-webview
* It was implemented according to the requirements of the code review of the [previous PR](https://github.com/flutter/packages/pull/4538#issuecomment-1645355234).
* Related issue: https://github.com/flutter/flutter/issues/30358#issuecomment-1645347616

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by bparrishMines** [comment]
@jsharp83  Thanks for the contribution! It looks like this feature is also supported on Android, [onJSAlert](https://developer.android.com/reference/android/webkit/WebChromeClient#onJsAlert(android.webkit.WebView,%20java.lang.String,%20java.lang.String,%20android.webkit.JsResult)), so we should add support for this in the common platform interface: `webview_flutter_platform_interface`.

See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins for more info on the process of doing this.

**Comment by jsharp83** [comment]
@bparrishMines Thanks for the review. unlike iOS, in Android, System popup works without any additional implementation. I added a test code on webview_flutter_android example, so you can check it .

Even Android supports system popup in Javascript, someone wants to use flutter version of alert. If you think that it is necessary things to support, I will additionally implement it on android platform. Thanks.

**Comment by jsharp83** [comment]
@bparrishMines I checked onJsAlert, onJsConfirm and onJsPrompt function in WebChromeClient you already mentioned. I will implement a interface with it on WebChromeClientHostApiImpl.java

**Comment by bparrishMines** [comment]
@jsharp83 Yea, I think we should still add a common platform interface for this method since it is supported on Android. The reason being that someone could want to override the default JS alerts on Android and we don't want to create an interface on iOS that is difficult for Android to implement at a later date.

**Comment by niumj** [comment]
@jsharp83 
[Add webkit interface for showing javascript alert message](https://github.com/flutter/packages/pull/4555/commits/2aae4b268649f8b43f4b35e73a8427e990be3512)

Thank you for your contents. But when I add the changes to [webview_flutter_wkwebview] , the below errors 
   FWFWKJavaScriptPanelType  Expected a type
  Unknown type name 'FWFWKJavaScriptPanelCompletionData'
  Use of undeclared identifier 'FWFWKJavaScriptPanel'

  FWFWKJavaScriptPanelCompletionData  Expected ')'

What can I do? or can you upload other neccessary  files?

**Comment by jsharp83** [comment]
@niumj 

It is defined in
packages/webview_flutter/webview_flutter_wkwebview/pigeons/web_kit.dart

You should run pigeon script on webview_flutter_wkwebview folder
> flutter pub run pigeon --input pigeons/web_kit.dart

I closed this PR because I uploaded a new PR with Android version implementation.

If you just add a feature temporary in iOS, check this commit
https://github.com/flutter/packages/compare/main...jsharp83:packages:temp-add-javascript-system-popup

**Comment by niumj** [comment]
@jsharp83 
Thank you !

**Pull request closed without merging**
