### PR TITLE
[go_router] CustomTransitionPage: Make barrierDismissible work

### PR DESCRIPTION
**Pull request by jnschulze**
Fixes https://github.com/flutter/flutter/issues/102289

### CODE REVIEW

**Comment by chunhtai** [comment]
Hi @jnschulze, this pr needs a test before merging

**Comment by chunhtai** [comment]
Hi @jnschulze, are you still planning on coming back to this pr?

**Comment by jnschulze** [comment]
Yes, I haven‘t had a chance to write a test yet.

**Comment by chunhtai** [comment]
Hi @jnschulze, I am going close this pr. Feel free to reopen if you have time to come back to this pr.

**Comment by kamami** [comment]
Will this be worked on?

**Pull request closed without merging**
