### PR TITLE
[pigeon] Fixes some Java lint issues

### PR DESCRIPTION
**Pull request by tarrinneal**
Fixes all lint issues mentioned in https://github.com/flutter/flutter/issues/85321. 

I'm not sure that these are all changes that will be agreed upon, but I thought I'd put them out there for discussion.

*List which issues are fixed by this PR. You must list at least one issue.*
fixes https://github.com/flutter/flutter/issues/85321

This change is breaking due to the newly final java classes being generated. I wouldn't expect this to effect many users though.

### CODE REVIEW

**Comment by gaaclarke** [comment]
Hey @tarrinneal did we hear back from internal customers that these linter issues are still worth fixing?  @ChristianEdwardPadilla might have some info on this.  My understanding is that the generated code has an exception now that it has the `@Generated` annotation.

**Comment by stuartmorgan** [comment]
We want generated code to be high quality, so we should evaluate lints in that light. Making the classes final seems like something that improves the quality of the code (and in particular, code that clients will be directly interacting with), so this seems like a good change regardless of any one specific client's needs.

**Comment by gaaclarke** [comment]
> We want generated code to be high quality, so we should evaluate lints in that light. Making the classes final seems like something that improves the quality of the code (and in particular, code that clients will be directly interacting with), so this seems like a good change regardless of any one specific client's needs.

High quality in terms of stability and performance? yes.  Of a specific style? not particularly.  We'll have to make that decision on a case by case decision.  If we are in a position where the client doesn't care anymore it probably isn't worth prioritizing considering it is a breaking change.  We don't want to get in a situation where we are responding to linter complaints since clients settings can differ between customers.

**Comment by stuartmorgan** [comment]
> We'll have to make that decision on a case by case decision.

Yes, and that is exactly what I did in the comment you are replying to:
>> Making the classes final seems like something that improves the quality of the code (and in particular, code that clients will be directly interacting with), so this seems like a good change regardless of any one specific client's needs.

> We don't want to get in a situation where we are responding to linter complaints since clients settings can differ between customers.

Do you think there are are people who have a linter setting that says that data classes shouldn't be final? I highly doubt that.

**Comment by tarrinneal** [comment]
It seems to me that these changes are generally worth implementing. This doesn't mean we need to prioritize lint issues in the future, but this work is already done. 

I think the classes should be final, and as such this change is worthwhile despite "breaking".

**Pull request merged**
