### PR TITLE
[rfw] Replace deprecated `textScaleFactor`

### PR DESCRIPTION
**Pull request by stuartmorgan**
Replaces the deprecated `textScaleFactor` with a linear `TextScaler`.

Updates the minimum deployment version to 3.16 where the new API was added.

Part of https://github.com/flutter/flutter/issues/143400

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
test-exempt: code refactor with no semantic change

**Review by Hixie — APPROVED** [review]
Thanks!
LGTM

**Comment by Hixie** [comment]
Not sure why the analyzer doesn't like it though.

**Comment by stuartmorgan** [comment]
Huh, I was trusting the deprecation message that said `This feature was deprecated after v3.12.0-2.0.pre.` which should have put that change in 3.13. But looking at the official [breaking change docs](https://docs.flutter.dev/release/breaking-changes#released-in-flutter-316) it was in 3.16 rather than 3.13. 🤷🏻 

I'll update the PR to rev the min supported version up to 3.16 instead. Legacy analysis bots FTW!

**Pull request merged**
