### PR TITLE
Update Xcode to 14.3.1

### PR DESCRIPTION
**Pull request by vashworth**
Packages part of https://github.com/flutter/flutter/issues/129019

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by keyonghan — APPROVED** [review]
LGTM

**Comment by vashworth** [comment]
https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20ios_platform_tests_shard_5%20master/4259/overview

Test packages/webview_flutter/webview_flutter_wkwebview is failing with:
```
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following PlatformException was thrown running a test (but after the test had completed):
flutter: PlatformException(NSInternalInconsistencyException, InstanceManager does not contain an NSURL with
flutter: identifier: 65554, null, null)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      NSUrlHostApi.getAbsoluteString (package:webview_flutter_wkwebview/src/common/web_kit.g.dart:2823:7)
flutter: <asynchronous suspension>
flutter: #1      WebKitWebViewController._webView.<anonymous closure>.<anonymous closure> (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:255:48)
flutter: <asynchronous suspension>
```

@bparrishMines @cyanglaz Any ideas on what's going on?

Looks like similar issue to: https://github.com/flutter/flutter/issues/128422

**Comment by cyanglaz** [comment]
I can repro it locally but inconsistent. I think it is a race condition where the object in the weakInstance is removed before it is accessed. I can't figure out where it was removed. It also doesn't seem to be related to the `withWeakReferenceTo allows encapsulating class to be garbage collected` test as shown in the log but more like an issue with `can receive updates to history state'`.  (I tried to commented out `can receive updates to history state` and couldn't reproduce the failure, it could also be because its inconsistency so I'm not entirely sure. )

I think @bparrishMines is more familiar with the code than I am so it would be nice if @bparrishMines could take a look.

I also don't think it is related to the xcode migration as I can reproduce the same failure with XCode 14.2. 
I'm going to trigger a re-run to see if it passes.

**Comment by vashworth** [comment]
submit-queue has been failing for a long time. I'm going to try updating the branch to unstick it.

**Pull request merged**
