### PR TITLE
[ci] Fix test syntax and gradle deps to unblock rolls.

### PR DESCRIPTION
**Pull request by ditman**
Fix analysis in a `package:go_router_builder` test case. The test used to *not* pass a `required` parameter, but an incoming version of dart seems to be enforcing the `required` keyword.

Re-attempts: https://github.com/flutter/packages/pull/1854

This also replaces the internal gradle configuration of flutter/packages to get rid of `jcenter()` in favor of `mavenCentral()`, as discussed [here](https://github.com/flutter/flutter/issues/78338).

No CHANGELOG change: change only in a test case, to allow for syntax that won't be allowed by dart soon.
No version change: changes only in example/test apps. Not user-facing code.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]

**Review by stuartmorgan — APPROVED** [review]
LGTM to unblock roll. I'm not sure why we have this test.

**Comment by ditman** [comment]
> LGTM to unblock roll. I'm not sure why we have this test.

@stuartmorgan it used to pass until now, I guess older versions of dart weren't throwing this lint?

**Review by jmagman — APPROVED** [review]
`mavenCentral` LGTM if the tests pass.

**Comment by ditman** [comment]
This PR only touches test code (or apps used on tests). Removed "needs-tests" label.

**Pull request merged**
