### PR TITLE
[pigeon]: added public keyword to swift classes, protocols and structs

### PR DESCRIPTION
**Pull request by MSimone12**
This PR fixes the build command for iOS frameworks on add-to-app, since the Swift compiler requires that public classes use other public classes, so, when implementing the protocols, they need to be public, when calling the setup class, it needs to be public as well, same for structs. 

*List which issues are fixed by this PR. You must list at least one issue.*

- flutter/flutter/issues/116619

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by gaaclarke** [comment]
Can you explain a bit more about the problem case this solves please?  The thought was to have the generated entities have `internal` access and the generated code would live in the same module that the client code would, so there is no need to be public.

This is a breaking change for swift clients so we have to make sure we are willing to break everyone over it.

**Comment by MSimone12** [comment]
@gaaclarke 

Basically when building for add-to-app on iOS, the Compiler complains about the methods not being public, and therefore, compçains about depending on internal members, like the protocols and classes generated by pigeon, marking those structures as public resolves this compiler build error.

**Comment by gaaclarke** [comment]
> @gaaclarke
> 
> Basically when building for add-to-app on iOS, the Compiler complains about the methods not being public, and therefore, complains about depending on internal members, like the protocols and classes generated by pigeon, marking those structures as public resolves this compiler build error.

Could you to provide a tiny example, please?  I just want to make sure it's not something we can solve with documentation, like "make sure to add the generated files this way to a project" versus making a breaking change.

**Comment by MSimone12** [comment]
> > @gaaclarke
> > Basically when building for add-to-app on iOS, the Compiler complains about the methods not being public, and therefore, complains about depending on internal members, like the protocols and classes generated by pigeon, marking those structures as public resolves this compiler build error.
> 
> Could you to provide a tiny example, please? I just want to make sure it's not something we can solve with documentation, like "make sure to add the generated files this way to a project" versus making a breaking change.

This is the code for an Add-to-app plugin/api developed to make easy the integration of the flutter module with the native code, the public class members are because the compiler complained about needing them to be public, and when generating the swift code from pigeon, the same compiler complained about relying on internal members, that's the why of this PR.

```swift
import Flutter
import UIKit


public typealias LocalStorageSetHandler = (String, String) -> Bool

public typealias LocalStorageGetHandler = (String) -> String

public class SwiftNativeApiPlugin: NSObject, FlutterPlugin, OtherApi {
        
  public static let instance = SwiftNativeApiPlugin();
  
  override private init() {}
    
  public let engine = FlutterEngine(name: "native_api")
  public var otherArgs : OtherArgs?
    
  public func setOtherArgs(args: OtherArgs) {
      self.otherArgs = args
  }
    
  public func getEngine() -> FlutterEngine {
    return engine
  }
   
  public func getOtherArgs() -> OtherArgs? {
      return self.otherArgs
  }

  public static func register(with registrar: FlutterPluginRegistrar) -> Void {
    OtherApiSetup.setUp(binaryMessenger: registrar.messenger(), api: SwiftNativeApiPlugin.instance)
  }

  public func getViewController() -> FlutterViewController {
    let viewController = FlutterViewController(engine: engine, nibName: nil, bundle: nil)
    return viewController
  }

  public func configure(env: FlutterEnv, initialRoute: String?) {
    engine.run(withEntrypoint: self.getEntrypoint(env: env), initialRoute: initialRoute)
  }


  private func getEntrypoint(env: FlutterEnv) -> String {
      switch env {
          case .development:
              return "startDevApp"
          case .hml:
              return "startHmlApp"
          case .blue:
              return "startBlueApp"
          case .production:
              return "startProdApp"
      }
      
  }
    
}

public enum FlutterEnv {
    case development
    case hml
    case blue
    case production
}
```
and this is the generated code that produces that error:

```swift
...

struct OtherArgs {
  var cpf: String? = nil
  var licensePlate: String? = nil
  var name: String? = nil
  var email: String? = nil
  var phone: String? = nil

  static func fromMap(_ map: [String: Any?]) -> OtherArgs? {
    let cpf = map["cpf"] as? String 
    let licensePlate = map["licensePlate"] as? String 
    let name = map["name"] as? String 
    let email = map["email"] as? String 
    let phone = map["phone"] as? String 

    return OtherArgs(
      cpf: cpf,
      licensePlate: licensePlate,
      name: name,
      email: email,
      phone: phone
    )
  }
  func toMap() -> [String: Any?] {
    return [
      "cpf": cpf,
      "licensePlate": licensePlate,
      "name": name,
      "email": email,
      "phone": phone
    ]
  }
}

protocol OtherApi {
  func getOtherArgs() -> OtherArgs?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OtherApiSetup {
  /// The codec used by OtherApi.
  static var codec: FlutterStandardMessageCodec { OtherApiCodec.shared }
  /// Sets up an instance of `OtherApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OtherApi?) {
    let getOtherArgsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.OtherApi.getOtherArgs", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getOtherArgsChannel.setMessageHandler { _, reply in
        let result = api.getOtherArgs()
        reply(wrapResult(result))
      }
    } else {
      getOtherArgsChannel.setMessageHandler(nil)
    }
  }
}
```

and that's where the public keyword was added, to solve this build issue.

**Comment by MSimone12** [comment]
@gaaclarke by the way, didn't mean to remove the request for your review, just re-requested @tarrinneal's review

**Comment by stuartmorgan** [comment]
@MSimone12 Could you file an issue (and link to it from the PR description, as requested in the checklist) with a full example (not just code excerpts) and the actual compile errors? There's a lot of important details being glossed over here about how exactly your build is configured and what the specific errors are.

**Comment by stuartmorgan** [comment]
Since the issue was auto-closed due to lack of response, I'm going to close this as well. If at some point you revisit the issue to provide the requested information about the use case, we can revisit the PR as well.

**Pull request closed without merging**
