### PR TITLE
[pigeon] Do generation for tests via the library

### PR DESCRIPTION
**Pull request by stuartmorgan**
For test output generation in the parts of the test script that have been converted to Dart, use the library entrypoint instead of shelling out to `pigeon` each time.

In quick tests this is a 10x improvement in running `tool/generate.dart`:
- on my macOS machine: 6 seconds instead of about a minute
- on my Windows machine: 16 seconds instead of about 4.5 minutes(!)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by tarrinneal — APPROVED** [review]
pretty incredible time savings! You'll need to merge from main once your other pr merges to get this merged though.

**Comment by tarrinneal** [comment]
just realized you'll need to run the tooling scripts on this pr also

**Comment by tarrinneal** [comment]
Also, just out of curiosity. What does this change actually do differently? All the code is still generated every time, correct?

**Comment by stuartmorgan** [comment]
> Also, just out of curiosity. What does this change actually do differently? All the code is still generated every time, correct?

We're just avoiding the overhead of forking a new, fresh `pigeon` process for each input file. IIRC Aaron said there's non-trivial time to load the Dart analyzer library, so paying that N times was probably a significant part of the problem.

**Comment by stuartmorgan** [comment]
The Windows failures were because it turns out we were never `close()`ing all of the `File` `IOSink`s we opened for the output files, so they were all still open for writing (and Windows really doesn't like concurrent file access). We never noticed before because when the `pigeon` process exits everything gets close automatically, and we'd only ever used in via process calls.

**Pull request merged**
