### PR TITLE
[vector_graphics_compiler] fix a renamed method parameter lint

### PR DESCRIPTION
**Pull request by pq**
An upcoming fix to `avoid_renaming_method_parameters` will flag this rename.

(I updated the base class since that seems more correct.)

For references, here's the fix in flight: https://dart-review.googlesource.com/c/sdk/+/394662

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
Change LGTM

I think we would normally bump the version and do a bugfix release for this to avoid accumulating lots of unpublished changes? @stuartmorgan

**Comment by matanlurey** [comment]
test-exempt: Lint compliance to be tested by said lint.

**Comment by pq** [comment]
@jonahwilliams (or @stuartmorgan): in order to update what gets analyzed on the Dart SDK flutter-analyze try-bots, does a new version need to get vended in or does it grab package source at HEAD?

**Comment by stuartmorgan** [comment]
> I think we would normally bump the version and do a bugfix release for this to avoid accumulating lots of unpublished changes? @stuartmorgan

We bend the interpretation of the "PRs that only affect local development of the package (e.g., changes to ignored lints)." version exemption sometimes to include cases where technically what is changing is actually code, but it's *very* obvious that it isn't changing behavior. I'm fine with that in this case.

> in order to update what gets analyzed on the Dart SDK flutter-analyze try-bots, does a new version need to get vended in or does it grab package source at HEAD?

It's analyzing repo source, not published source.

**Comment by stuartmorgan** [comment]
> Depends on where the analysis is failing. if its in the framework repo then it may be getting pulled in via pub

The upstream analysis (both flutter/fluter and Dart-level) are source-based. flutter/flutter uses a pinned version that is auto-rolled. I forget what the Dart variant does about the exact version, but it's repo source.

**Comment by pq** [comment]
Here's the bot failure:

**Comment by pq** [comment]
Hmmm, looks like this caused a breakage after all:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8731382513574602801/+/u/Run_flutter_plugins_tests/stdout

(On the Flutter HHH bot).

@stuartmorgan, @jonahwilliams: Will this get fixed by an auto-roll?

**Comment by pq** [comment]
Cool, thanks. Is there a good place for me to communicate that help is on the way?

**Comment by stuartmorgan** [comment]
Sorry, I'm not sure what you are asking. Communicate to whom, and about what help? If a Dart-team-maintained tree is broken, I'm not familiar with the process for managing that.

**Comment by pq** [comment]
Sorry, my question wasn't really well-posed. I'm trying to figure out the reach of the inconvenience and let impacted folks know this should get fixed w/ the auto-roll. I'll do some more poking but if this is just affecting a Dart-team-maintained tree, that's good and I'll communicate w/ Dart folks. Thanks!

**Comment by gspencergoog** [comment]
@pq This is currently one of the things blocking the Flutter roll into google3, since it's causing the engine to flutter roller to fail, and that's blocking a needed Dart compiler fix from getting into the flutter repo. It looks like the flutter-packages-flutter-autoroll is blocked on some infra problems on macOS. Once that's resolved, I suspect things will all iron out, I just wanted to let you know about the pileup.

**Comment by pq** [comment]
Thanks @gspencergoog! If we need to push this through before the auto-roll is unblocked, we could consider disabling `avoid_renaming_method_parameters` temporarily. (We've done that kind of thing in the past.) Let me know if I can help at all (and sorry for the added hassle!)

**Comment by gspencergoog** [comment]
Seems like the packages roll made it through, so one less thing in the way. :-)

**Comment by pq** [comment]
Woohoo! Thanks!

**Pull request merged**
