### PR TITLE
[pigeon] Port over several test suites from run_tests.sh to run_tests.dart

### PR DESCRIPTION
**Pull request by fuzzybinary**
I'm looking to help with pigeon a bit, and this looked like a good place to help out initially. I ported over some of the simpler tests run in run_tests.sh into run_tests.dart.

This ports over
 - dart_unittests
 - flutter_unittests
 - mock_handler_tests

I'm not sure if I should change run_tests.sh temporarily to run these tests, or if there's another test file that would need to be updated

Partial fix for:
https://github.com/flutter/flutter/issues/85068

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by fuzzybinary** [comment]
Updated to have run_tests.sh call into dart's version of the same test runs.

**Review by gaaclarke — COMMENTED** [review]
Sorry, I was out for a couple of weeks.  This LGTM.  I think we can clean it up later to make it a little less verbose (my bad I set the example).  You're going to have to add a version change to the pubspec and update the CHANGELOG too.

**Comment by fuzzybinary** [comment]
Updated! Let me know if there's anything else I need to do.

**Review by gaaclarke — APPROVED** [review]
LGTM thanks!

**Pull request merged**
