### PR TITLE
Ensure that initialLocation doesn't take precedence over deep-links

### PR DESCRIPTION
**Pull request by johnpryan**
Fixes https://github.com/flutter/flutter/issues/106204

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by loic-sharma — APPROVED** [review]

**Comment by BrilliantFish** [comment]
the bug now have

**Comment by BrilliantFish** [comment]
I can't understand "Ensure that initialLocation doesn't take precedence over deep-links"

**Comment by johnpryan** [comment]
The GoRouter's state was being set to initialLocation (for example `/home`) when a deep link was received by the platform (such as `/my-deep-link`)

**Comment by thierryoliveira** [comment]
Is this bug happening again? When my app was not launched yet, and I call a deep-link, the router is going to  `initialLocation` instead of the right route. It's working correctly when the app is already open/minimized.

**Comment by johnpryan** [comment]
Hi @thierryoliveira, would you mind filing a new issue?

**Comment by thierryoliveira** [comment]
Hi @johnpryan. I will create a new one right now, thank you!

**Pull request merged**
