### PR TITLE
[multiple packages] Update collection-fors to prefer final (as per updated `prefer_final_in_for_each`)

### PR DESCRIPTION
**Pull request by pq**
The newly updated lint will soon flag for-each in collections.

See discussion: https://github.com/dart-lang/linter/pull/4383

/cc @goderbauer @yjbanov 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: lint update

**Review by gmackall — APPROVED** [review]
Changes LGTM, though the formatting will need to be adjusted according to the repo_checks!

**Comment by pq** [comment]
Thanks @gmackall! Formatting fixed but I wonder if you could add the `override: no versioning needed` label for me?

**Comment by gmackall** [comment]
I know that changes to ignored lints are version exempt, but I'm actually not sure about changes that are for broken but soon-to-be fixed lints. cc'ing @stuartmorgan, do you happen to know?

**Comment by stuartmorgan** [comment]
Usually we don't exempt code changes, even if it's to fix lints, because just because the *intent* of the change was to fix a lint doesn't mean the effect of the change won't be to actually change behavior in some subtle way. I have seen (and been responsible for) plenty of cases where a change whose description says "does not change behavior" has to be rolled back because it did in fact change behavior. In general, err on the side of bumping versions for that reason.

In this case though, we can have a high enough degree of confidence that it can't break anything—I would not expect this to even change the generated code at all—to skip having it in its own release.

**Comment by pq** [comment]
Thanks @stuartmorgan!

**Pull request merged**
