### PR TITLE
[go_router] Fix a typo in a comment in the shell_route.dart

### PR DESCRIPTION
**Pull request by ultraon**
Fixed a typo in a comment in the shell_route.dart.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [x] the PR is exempt from version changes
- [x] the PR is exempt from CHANGELOG changes.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
no version and change log: The example isn't going to be visible in pub.dev and api doc.

**Comment by stuartmorgan** [comment]
> no version and change log: The example isn't going to be visible in pub.dev and api doc.

Did the check fail? It shouldn't have.

**Comment by chunhtai** [comment]
apparently not!

**Comment by ultraon** [comment]
@chunhtai thanks for the approval, could you please share what the next step is to merge the PR?

**Review by hannah-hyj — APPROVED** [review]
LGTM

**Pull request merged**
