### PR TITLE
[pigeon] Style fixes in C++ generator

### PR DESCRIPTION
**Pull request by stuartmorgan**
Fixes various style guide violations in the C++ generator output:
- Include blocks were not correctly sorted.
- Switch statements had trailing whitespace.
- The namespace close didn't have the right comment.
- Many {'s were missing the preceding space.
- Many methods and variables used camel-case naming.

Fixes https://github.com/flutter/flutter/issues/104290

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
This just fixes some minor non-line-wrapping changes I noticed that clang-format made on the generated files while trying out the new generator.

**Comment by stuartmorgan** [comment]
I added another commit of non-clang-format fixes to naming, so the scope is a bit larger. I can split them if you prefer, but they are all under the umbrella of "style is wrong".

**Comment by azchohfi** [comment]
@stuartmorgan there is a conflict with the change log.

**Comment by azchohfi** [comment]
Actually, this should be 3.1.2.

**Comment by stuartmorgan** [comment]
> @stuartmorgan there is a conflict with the change log.

I'm used to working in flutter/plugins where there are pretty routinely conflicts in the changelogs and version bumps, so it's often not worth resolving the version until PRs pass review; see the last item [here](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#faq).

But I can resolve this one; there aren't many pending Pigeon changes, and probably none that will land before this one.

**Review by azchohfi — APPROVED** [review]
I've tested this PR on the Video Player and it worked fine, so LGTM.
My only concern is that it breaks the generated APIs so, at least in theory, we should bump the major version. Since the C++ generator was merged only a couple of days ago, I believe it would be ok to break it without a major version, but I'm not sure how these exceptions should be handled.

**Comment by stuartmorgan** [comment]
> My only concern is that it breaks the generated APIs so, at least in theory, we should bump the major version.

The discussion around using "experimental" for new generators (some of this may have been offline, sorry) was that we wouldn't consider breaking changes to a generator that's in the experimental stage to be package-breaking, so that was intentional. Once we feel like it's stabilized enough, we'll remove the experimental bit from the flags and then apply the normal breaking change policy.

**Pull request merged**
