### PR TITLE
bump mockito to version 5.4.1

### PR DESCRIPTION
**Pull request by christopherfujino**
Part of https://github.com/flutter/flutter/issues/127226

Follow up to https://github.com/flutter/packages/pull/3544. Version 5.4.0 from that PR is not new enough, see

```
Because mockito >=5.4.0 <5.4.1 depends on test_api >=0.2.1 <0.6.0 and every version of flutter_test from sdk depends on test_api 0.6.0, mockito >=5.4.0 <5.4.1 is incompatible with flutter_test from sdk.
So, because quick_actions_platform_interface depends on both flutter_test from sdk and mockito 5.4.0, version solving failed.
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8780090492483790881/+/u/run_test.dart_for_flutter_plugins_shard_and_subshard_analyze/test_stdout

### CODE REVIEW

**Review by tarrinneal — APPROVED** [review]
Image_picker and pigeon lgtm

**Review by stuartmorgan — APPROVED** [review]
LGTM

This reminds me, I still need need to add special mockito handling in the `update-packages` command.

**Comment by stuartmorgan** [comment]
Overrides: this is a dev only change, the scripts just don't look at the details of pubspecs.yaml changes yet, so can't tell.

**Comment by christopherfujino** [comment]
> LGTM
> 
> This reminds me, I still need need to add special mockito handling in the `update-packages` command.

thanks

**Review by ditman — APPROVED** [review]
Thanks for the update!

**Comment by ditman** [comment]
Clicking "update branch" to get this: https://github.com/flutter/packages/pull/4086

**Pull request merged**
