### PR TITLE
Remove unnecessary breaks in default clauses of switch statements

### PR DESCRIPTION
**Pull request by jason-simmons**
See https://dart.googlesource.com/sdk.git/+/045d26bc74209f5acc6466669f89686344e83de2

### CODE REVIEW

**Review by matanlurey — APPROVED** [review]

**Comment by jason-simmons** [comment]
@stuartmorgan Does this require incrementing any package version numbers?

Or should I add the override labels?

**Comment by stuartmorgan** [comment]
Override changelog and version: While technically a code change, this is a no-op behaviorally.

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Pull request merged**
