### PR TITLE
[fuchsia_ctl] Fix typo "Unkown"

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by godofredoc — APPROVED** [review]

**Comment by ditman** [comment]
@nilsreichardt does this need tests? There's some `@visibleForTesting` in this file. If not, can you get an exemption from @Hixie to appease the `flutter-dashboard` bot?

Once the `needs tests` label is sorted out, this can be auto-landed just by adding the "waiting for tree to go green" label.

Thanks!

**Comment by nilsreichardt** [comment]
@ditman I looked a bit into the code and the entire `main.dart` is not tested. The `@visibleForTesting` has no effect because these methods are not used in tests. You can remove `@visibleForTesting`, run `dart analyze` and you will have no issues.

You can also see this in the code coverage output that `bin/main.dart` is untouched:
```
NilsMBP13M13:fuchsia_ctl nils$ genhtml coverage/lcov.info -o coverage/
Reading data file coverage/lcov.info
Found 11 entries.
Found common filename prefix "/Users/nils/Desktop/Projects/packages/packages/fuchsia_ctl/lib"
Writing .css and .png files.
Generating output.
Processing file src/image_paver.dart
Processing file src/ssh_client.dart
Processing file src/tar.dart
Processing file src/amber_ctl.dart
Processing file src/emulator.dart
Processing file src/logger.dart
Processing file src/package_server.dart
Processing file src/ssh_key_manager.dart
Processing file src/operation_result.dart
Processing file src/ffx.dart
Processing file src/command_line.dart
Writing directory view page.
Overall coverage rate:
  lines......: 83.1% (305 of 367 lines)
  functions..: no data found
```

I don't think this needs tests, because it's just typo fix in an error message which is printed to the console. So the behavior of this package does not change. Or this test would have to explicitly test the content of the error message.

**Comment by Hixie** [comment]
test-exempt: typo fix

that said, we do have a number of tests for typos and the like in the tool, so if you're feeling particularly excited to you could look to adding one that catches this typo broadly (e.g. scanning the source for this typo) or that verifies the exact output of the tool when doing this action (this in particular is often really worth it because it helps catch cases where we accidentally add new output that we didn't mean to add, like blank lines, or debugging prints).

**Comment by ditman** [comment]
Thanks for the thorough investigation @nilsreichardt! My main concern with this types of change is "maybe the output of this tool is being parsed elsewhere" (which is not the case here, but I have seen done earlier).

IMO if they're not being used, the `@visibleForTesting` annotations should be removed. I think they give a "false sense of security" to see them there: like "this is probably tested somewhere (but nope!)".

I'm landing this change now. Thanks everybody for taking a look!

**Comment by godofredoc** [comment]
> ot suitable for automatic merging in its current state.
> 
> * Please get at least one approved review if you are already a member or two member reviews if you are not a member before re-applying this label. **Reviewers**: If you left a comment approving, please use the "approve" review

@ditman would you mind giving a second LGTM? we need 2 LGTMs for new contributions.

**Review by ditman — APPROVED** [review]
LGTM! Let's go!

**Comment by nilsreichardt** [comment]
> that said, we do have a number of tests for typos and the like in the tool, so if you're feeling particularly excited to you could look to adding one that catches this typo broadly (e.g. scanning the source for this typo) or that verifies the exact output of the tool when doing this action (this in particular is often really worth it because it helps catch cases where we accidentally add new output that we didn't mean to add, like blank lines, or debugging prints).

Thanks for explanation :) Do you have any packages as an example where you have tests for cases like this? I could then take a look at them and write a test for something like this next time 👍

**Comment by nilsreichardt** [comment]
> My main concern with this types of change is "maybe the output of this tool is being parsed elsewhere" (which is not the case here, but I have seen done earlier).

Good point 👍 

> IMO if they're not being used, the @visibleForTesting annotations should be removed.

I'll create a new PR for this :)

**Comment by ditman** [comment]
@nilsreichardt the plugin_tools package has lots of tests that assert the output to the terminal of running a script, because it's a very important part of the UX of the script. For example: https://github.com/flutter/plugins/blob/main/script/tool/test/analyze_command_test.dart#L138 (there's many more similar examples in that `script/tool/test` directory)

(fuchsia_ctl is maybe not quite there wrt to testing, and I don't know the package very well to know how "feasible" would it be to add those types of tests, but that's one idea)

**Comment by nilsreichardt** [comment]
@ditman Great, thanks! ❤️

**Pull request merged**
