### PR TITLE
[pigeon] Fix enum parameters in Dart test

### PR DESCRIPTION
**Pull request by stuartmorgan**
Fixes the handling of enum parameters in the Dart test class generation for testing host APIs.

Fixes https://github.com/flutter/flutter/issues/105742

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
This generated the same code that I wrote manually as a workaround in https://github.com/flutter/plugins/pull/6635.

**Comment by tarrinneal** [comment]
Seems to be failing the dart analyze tool. I'm not sure why, as you didn't change anything that would result in those failures.

**Comment by stuartmorgan** [comment]
That failure will be fixed by https://github.com/flutter/packages/pull/2751 (see link there for an explanation of the issue).

**Review by tarrinneal — APPROVED** [review]
lgtm

**Comment by stuartmorgan** [comment]
Ugh, the workaround we did isn't enough for Pigeon's unusual package structure (https://github.com/dart-lang/pub/issues/3618#issuecomment-1297422312). I think we'll need to flip `publish` back to `stable` again temporarily.

**Comment by stuartmorgan** [comment]
I forgot that `publishable` was combined into a task with various other things that we ideally want to stay on `master`. Rather than split it back out, I inserted an ugly workaround into the Cirrus config to pre-fetch all of the sub-packages of `pigeon`. Hopefully we won't need the hack for long, since it doesn't scale well; if it's not fixed soon we'll probably have to split the task out and move it to `stable` instead.

**Pull request merged**
