### PR TITLE
[go_router_builder] Update to `go_router` 6

### PR DESCRIPTION
**Pull request by ValentinVignal**
*List which issues are fixed by this PR. You must list at least one issue.*

No issue but this is a follow up to https://github.com/flutter/packages/pull/2848

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] ~I listed at least one issue that this PR fixes in the description above.~ I listed the related PR instead
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by ValentinVignal** [comment]
I believe this PR can have a test exemption? Am I correct?

**Comment by chunhtai** [comment]
This migrates go_router_builder due to go_router v6 breaking changes. The existing test should be good enough.

**Comment by ValentinVignal** [comment]
> You will need to regenerate the example/ in order to pass the ci

I didn't modify any code of `go_router_builder` so the generated files shouldn't have changed, right? 🤔 Anyway, I tried re-generated them and I don't have any changes.
Plus, on `dart_unit_tests CHANNEL:stable`, the fails on `/example/test/ensure_build_test.dart`. The differences are on the `pubspec.yaml` so I'm not sure I understand what is happening 🤔  (The test is passing on my local)

**Comment by chunhtai** [comment]
ah it is the path override that causes the test to fail, it is not related to this change, sorry about the confusion. I will put up a pr to fix it.

**Comment by chunhtai** [comment]
This should fix it https://github.com/flutter/packages/pull/2984

**Comment by Hixie** [comment]
test-exempt: rolling dependencies

**Comment by chunhtai** [comment]
The pr was merged. Can you rebase off the main branch and see if that fixes ci

**Comment by chunhtai** [comment]
it looks like your branch is still missing the latest commit https://github.com/flutter/packages/commit/73637b81a91e4373811bbc68922768edf025ac2e

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by johnpryan — APPROVED** [review]

**Pull request merged**
