### PR TITLE
[flutter_template_images] Rename list_detail_app to skeleton

### PR DESCRIPTION
**Pull request by brianegan**
I'm very sorry -- I'm working on a new template for the Flutter team. I thought I'd gotten a final LGTM and asked the team to deploy a version of the `flutter_template_images` repository using the `list_detail_app` naming, but a name change was requested afterwards! 

The team would like to rename the `list_detal_app` to `skeleton`.

*List which issues are fixed by this PR. You must list at least one issue.*

 - https://github.com/flutter/flutter/pull/76519

## Pre-launch Checklist

- [X] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated `CHANGELOG.md` to add a description of the change.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the `#hackers-new` channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like the naming discussion is still in full swing over at https://github.com/flutter/flutter/pull/76519. It's probably a good idea to wait until that's resolved before proceeding with this one.

**Comment by brianegan** [comment]
I'll go ahead and close this one out for now since I'm unsure on the status of the main PR and unfortunately have no additional time to support them.

**Comment by stuartmorgan** [comment]
Closing these two PRs leaves this package in a state where it is not compatible with any version of Flutter. If you are not moving forward with the new template, please revert your earlier change so this package isn't in limbo.

**Comment by brianegan** [comment]
Thanks @stuartmorgan -- I'd imagine the team will move forward with the template, but my time on the project has drawn to a close. I'll let them take it from here, including reopening this PR if "skeleton" is the name folks want to go with :)

**Pull request closed without merging**
