### PR TITLE
[url_launcher_android] Enable Android WebView to open PDFs and non-HTTP URLs (`mailto:`, `tel:`, `sms:`, etc.)

### PR DESCRIPTION
**Pull request by michaelmiles1**
This PR adds the ability of the launched WebView in Android to follow and open non-HTTP links by starting new Intents, such as opening a PDF viewer or your preferred email application.

Issues fixed: 
[#106331](https://github.com/flutter/flutter/issues/106331) - this fix was inspired by the attempted fix [here](https://github.com/flutter/plugins/pull/6006), but I had to extend the `WebViewClient` to make it testable
[#27309](https://github.com/flutter/flutter/issues/27309) - opening PDFs wasn't causing a crash for me, but was not opening PDFs on any Android device

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ ] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by gmackall** [comment]
Hi @michaelmiles1, thanks for the contribution! Have you had a chance to look at signing the CLA (see the google-cla bot comment)? Once you sign it, I can take a look at this PR!

**Comment by stuartmorgan** [comment]
> * [x]  I signed the [CLA](https://cla.developers.google.com/).

In particular, it looks like you made commits with two different email addresses, but only signed a CLA for one of them.

**Comment by michaelmiles1** [comment]
Working on resolving this CLA issue with my organization @gmackall @stuartmorgan, thanks for your patience

**Comment by stuartmorgan** [comment]
Marking as a draft until the CLA issues are resolved. Please mark as ready for review once that's been handled. Thanks!

**Comment by stuartmorgan** [comment]
Unfortunately we’re unable to accept PRs without a signed CLA. If you sign the CLA in the future, please comment to let us know, and we can re-open this PR.

**Comment by michaelmiles1** [comment]
Thanks @stuartmorgan, this had to be escalated to legal for approval and will be reopened when we figure it out

**Comment by michaelmiles1** [comment]
PR with CLA issues fixed is here: https://github.com/flutter/packages/pull/5017

**Pull request closed without merging**
