### PR TITLE
[google_maps_flutter_platform_interface] Add support for cloud-based map styling

### PR DESCRIPTION
**Pull request by jokerttu**
This PR is sub-PR splitted out from the https://github.com/flutter/packages/pull/3682
containing only the platform_interface package changes.

Related to issue https://github.com/flutter/flutter/issues/67631

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
The changes here need testing in map_configuration_test.dart.

It looks like currently we're only testing diff in general, but we should test the others as well. (No need to backfill tests all the existing properties in equality, empty, etc., but we should add them for the new one.)

**Comment by jokerttu** [comment]
> The changes here need testing in map_configuration_test.dart.
> 
> It looks like currently we're only testing diff in general, but we should test the others as well. (No need to backfill tests all the existing properties in equality, empty, etc., but we should add them for the new one.)

Added test cases to diffs.
I was planning to add getCloudMapId method to google_maps_inspector_platform.dart but native GMaps instances does not have way to read the mapId from the instance object once it is initialized on Android nor on iOS, so there is really no way to check if the current map instance is really initialized with proper mapId.

**Comment by reidbaker** [comment]
From triage: @stuartmorgan I think this is waiting on a response from you.

**Review by stuartmorgan — APPROVED** [review]
LGTM!

**Comment by stuartmorgan** [comment]
Looks like this is ready to land and was just never submitted, so I'm going to add the `autosubmit` label.

**Comment by stuartmorgan** [comment]
Unclear why this needs a second review 🤷🏻

**Review by tarrinneal — APPROVED** [review]
optional nit, I'm going to land this in the next couple hours if you don't respond.

**Pull request merged**
