### PR TITLE
[flutter_adaptive_scaffold] Surface `useLegacyColorScheme` property in `AdaptiveScaffold`

### PR DESCRIPTION
**Pull request by a-wallen**
Surfaces the `useLegacyColorScheme` property from `BottomNavigationBar`. 

Fixes https://github.com/flutter/flutter/issues/116903

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Closing as this has been draft for a while; please feel free to re-open if this is something you plan to revisit.

**Comment by a-wallen** [comment]
@stuartmorgan no problem. FWIW this PR can land once `useLegacyColorScheme` rolls into stable, but since that property hasn't rolled on that branch I marked the PR as a draft. I'm not sure if that changes your decision about closing that PR.

**Comment by stuartmorgan** [comment]
Sure, if it's good to go other than that, leaving it open makes sense. Thanks!

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Thanks for the comment on this @a-wallen!  Good to hear from you.

`useLegacyColorScheme` is in stable now, so we should be able to land it.

**Comment by gspencergoog** [comment]
Oh, I guess it's not defined in 3.3.10 (it is in the stable 3.6.0 branch in my Flutter, though).

I guess we'll wait until the legacy version catches up.

**Comment by a-wallen** [comment]
SGTM. Nice I guess I'll be seeing you again when that happens @gspencergoog.

**Comment by stuartmorgan** [comment]
Syncing with main now that everything has rolled forward for the 3.10 release.

**Comment by stuartmorgan** [comment]
I pinged @Hixie in Discord about the CLA problem.

**Review by stuartmorgan — APPROVED** [review]

**Comment by stuartmorgan** [comment]
The CLA issue is fixed, but we'll need to update this to resolve the conflicts. CHANGELOG is the usual trivial change, but there's a code conflict too.

**Comment by stuartmorgan** [comment]
@gspencergoog Do you have time to fix the conflicts here, or should I add that to my list?

**Comment by gspencergoog** [comment]
I could fix the conflicts, but `NavigationBar` doesn't even have `useLegacyColorScheme`, so I'm thinking that we could just close this PR, since we're not using `BottomNavigationBar` anymore.

**Pull request closed without merging**
