### PR TITLE
[ci] Add LUCI version of dart unit tests

### PR DESCRIPTION
**Pull request by stuartmorgan**
Add initial LUCI versions of the dart unit tests task.

Part of https://github.com/flutter/flutter/issues/114373

### CODE REVIEW

**Comment by stuartmorgan** [comment]
This takes noticeably longer than the Cirrus version using the "heavy workload" machine configuration, so I switched from two shards to three. Is that the preferred approach, or would it be better to make these use higher-spec config as well (presumably by increasing `cores`)?

**Comment by keyonghan** [comment]
> This takes noticeably longer than the Cirrus version using the "heavy workload" machine configuration, so I switched from two shards to three. Is that the preferred approach, or would it be better to make these use higher-spec config as well (presumably by increasing `cores`)?

With these targets as heavy workload, and have been running against more cpu/memory machines in cirrus, it makes sense to run them against higher-spec machines in LUCI, which are with 32-cores.

**Comment by stuartmorgan** [comment]
Thanks, switched to two shards and 32-core machines, and we can see how that goes.

**Comment by stuartmorgan** [comment]
@yusuf-goog Ping on this review?

**Comment by keyonghan** [comment]
> @yusuf-goog Ping on this review?

(Yusuf is ooo earlier this week, and not sure if he is back.)
LGTM with this PR, approving (sorry miss-tracked this after last week's comment..).

**Review by keyonghan — APPROVED** [review]
LGTM

**Pull request merged**
