### PR TITLE
[ci] Split android-platform_tests in 2 shards

### PR DESCRIPTION
**Pull request by ditman**
The `android-platform_tests` task has started OOM'ing.

After increasing its memory limit to `12G`, it passed, but the current max utilization is at 11.44GB.

This PR splits the `android-platform_tests` in 3 shards, to see if memory utilization goes down further without having to request a beefier instance.

Also, make the environment variable consistent with flutter/plugins (in [this PR](https://github.com/flutter/plugins/pull/6374))

Fixes https://github.com/flutter/flutter/issues/111126

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by ditman** [comment]
```
Ran for 7 package(s)
Skipped 16 package(s)
```

This ain't sharding anything!

**Comment by ditman** [comment]
Created related issue: https://github.com/flutter/flutter/issues/111126

**Comment by ditman** [comment]
Shard index 0 is using ~10GB
Shard index 1 is using ~6GB

**Comment by ditman** [comment]
Shard index 0 is using ~7GB
Shard index 1 is using ~7GB
Shard index 2 is using ~5GB

**Comment by Hixie** [comment]
test-exempt: configuration

**Comment by stuartmorgan** [comment]
The numbers here (the fact that it's not actually just dividing: 11, or 10+6=16, or 7+7+5=19) make me think there's an element of "uses whatever is available, but can swap out if needed". I.e., it seems likely that even though it's using 11GB, we're not actually about to tip over the limit again. And it was fine at 8 until a small recent change, so the likelihood that half now actually requires 10 seems low.

Looking at run times though, it looks like two shards brings this test into about the same timeframe as our slowest other tests, so doing two shards just from a time-to-complete-tests standpoint seems like a good idea. Three seems like overkill for now.

**Review by stuartmorgan — APPROVED** [review]
LGTM with two shards instead of three. Thanks for doing some trials on this!

**Comment by ditman** [comment]
> LGTM with two shards instead of three. Thanks for doing some trials on this!

Yeah, 2 shards sound just enough!

**Comment by ditman** [comment]
Silly bot, it can't see the retry...

**Pull request merged**
