### PR TITLE
[dynamic_layouts] Add a staggered grid layout example

### PR DESCRIPTION
**Pull request by DavBot02**
Adds the staggered grid meant for the example application. Not meant to land yet, will rebase when #2550 lands.
Follow up on #2520.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like there are some merge conflicts? Any chance you could resolve those on this PR and get the checks to green? Thanks!

**Comment by DavBot02** [comment]
> Looks like there are some merge conflicts? Any chance you could resolve those on this PR and get the checks to green? Thanks!

Yes, let me see if I can get @snat-s changes and complete the sample app

**Comment by goderbauer** [comment]
You probably want to revert all files outside of `packages/dynamic_layouts/` that were changed in this PR.

**Comment by DavBot02** [comment]
I'm not sure why those checks are failing

**Comment by Piinks** [comment]
It was a flake, I re-ran it and it passed.

**Review by Piinks — APPROVED** [review]
This LGTM! 🎉 

It looks like it contains the changes from https://github.com/flutter/packages/pull/2550, so that will have to land first @snat-s

**Comment by Piinks** [comment]
The changes from #2550 have landed, can you rebase this so we can land it? :)

**Comment by DavBot02** [comment]
Looks like it's done! Can someone please merge it? I think I don't have write access

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
