### PR TITLE
[flutter_markdown] update tests to remove use of deprecated idicatorForCheck/UncheckedCheckBox symbols from markdown

### PR DESCRIPTION
**Pull request by timmaffett**
This PR updates the checkbox testing code within `list_test.dart` to work for the new markdown release that uses a new checkbox scheme and no longer requires the use of these deprecated symbols (`idicatorForCheckedCheckBox`  and `idicatorForUncheckedCheckBox` ) to predict expected checkbox related output from markdown.

The new markdown will include changes which allow the existing (unchanged) `list_test.dart` code to continue to compile and for the tests to pass, but this PR corrects the code to remove the use of these symbols entirely.

Please see detailed discussion at https://github.com/dart-lang/markdown/pull/450  .

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [X] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by timmaffett** [comment]
Important note: this PR will not function correctly (and should not be merged) until the new markdown (6.0.1?) is released. 

This is a change to fix the flutter_markdown to work with the next markdown (i.e. post 6.0.0).

**Comment by stuartmorgan** [comment]
This needs an update to be publishable.

**Comment by timmaffett** [comment]
@stuartmorgan  should be gtg now,

**Comment by stuartmorgan** [comment]
No changelog needed; minor test updates only.

**Comment by stuartmorgan** [comment]
Landing on red to fix the tree.

**Pull request merged**
