### PR TITLE
[ci] Removes bespoke web scripts.

### PR DESCRIPTION
**Pull request by ditman**
Removes the bespoke scripts (`regen_mocks.sh`, `run_test.sh`) that I had added to web packages.

I'll keep those in my own `~/bin` moving forward, since I'm not sure anybody else actually used/needed them other than myself :)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by ditman** [comment]
I think this PR can ignore the `Missing CHANGELOG change`, since all it's doing is removing non-standard scripts that trip the check.

**Review by stuartmorgan — APPROVED** [review]
LGTM

Out of curiosity, is there a reason you aren't just using the repo tooling's `drive-examples --web`? If it's just the ability to specify a specific test file, we could definitely add a flag for that.

**Comment by ditman** [comment]
> Out of curiosity, is there a reason you aren't just using the repo tooling's drive-examples --web? If it's just the ability to specify a specific test file, we could definitely add a flag for that.

@stuartmorgan I gave this some thought before removing custom scripts, and there's two (three-ish) things that bothered me:

* Having to run the script from the root of the checkout and specify a `--packages` (rather than from the directory where I'm actually working on and assuming the package is whatever directory I'm in).
* The `tool_runner.sh` hardcodes `--packages-for-branch` and IIRC that prevents me from passing `--packages=my_package` because the script says it must be one or the other (IIRC).
* Detecting that chromedriver is not running early (or the driver for the browser that is going to be used) is faster than letting flutter drive fail.

Minor annoyances, really, and I'm not sure if they warrant a fix or they're a quirk of the way I'm used to working with the repo!

**Comment by stuartmorgan** [comment]
> * Having to run the script from the root of the checkout

That's definitely annoying; I'd gotten so used to it that it hadn't occurred to me that we can easily fix it now: https://github.com/flutter/flutter/issues/128231

> and specify a `--packages` (rather than from the directory where I'm actually working on and assuming the package is whatever directory I'm in).

https://github.com/flutter/flutter/issues/128232

> * The `tool_runner.sh` hardcodes `--packages-for-branch` and IIRC that prevents me from passing `--packages=my_package` because the script says it must be one or the other (IIRC).

I pared `tool_runner.sh` down to just CI stuff a while ago; you shouldn't use it locally. Instead, `dart run` the script directly.

> * Running a single file is useful some times, especially when introducing new test files to the package.

https://github.com/flutter/flutter/issues/128234

> * Detecting that chromedriver is not running early (or the driver for the browser that is going to be used) is faster than letting flutter drive fail.

This one is probably best left out of the tool since adding it in a cross-platform way would be kind of a pain.

But if we fix the others then your wrapper script can just be that one check.

**Comment by ditman** [comment]
Thanks for creating the tracking issues!

> But if we fix the others then your wrapper script can just be that one check.

I haven't tried the check in a while, it might be something that can be made part of `dart drive` too to make it fail fast!

**Pull request merged**
