### PR TITLE
[in_app_purchase] Bump `in_app_purchase_android` dependency to 3.0.0

### PR DESCRIPTION
**Pull request by JeroenWeener**
Bumps `in_app_purchase_android` to 3.0.0.

This PR is the final step for closing flutter/flutter#110909.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: migrating for roll

**Review by bparrishMines — APPROVED** [review]
LGTM

cc @stuartmorgan for secondary review

**Comment by kinex** [comment]
Too late but I think this PR had breaking changes, so it should have updated major version number. Now it breaks the build if you upgrade packages (without major version upgrade).

**Comment by stuartmorgan** [comment]
> Too late but I think this PR had breaking changes

It's not too late; we have the ability to retract a package version on pub.dev. I don't see any exports of anything that changed though, so I'm not seeing how it's breaking.

> Now it breaks the build if you upgrade packages

Please file an issue during an example app that imports only this package that is broken by this change, and we can follow up there.

**Comment by kinex** [comment]
I filed an issue here https://github.com/flutter/flutter/issues/127766. Anyway, thanks for this PR! It has changes I have waited for a long time. Now just have to figure out how to get them into use...

**Comment by enricoi** [comment]
@kinex have you find a solution to get GooglePlayProductDetails.skuDetails? I used 'skuDetails.freeTrialPeriod' to know if show free trial offer ui or not but now I don't know how to do. Thanks

**Pull request merged**
