### PR TITLE
Function(ImageInfo, bool) --> ImageStreamListener

### PR DESCRIPTION
**Pull request by 2534290808**
fix void Function(ImageInfo, bool) can't be assigned to the ImageStreamListener

### CODE REVIEW

**Comment by adrianvintu** [comment]
Please let us know on the status of this.

**Comment by andreidiaconu** [comment]
@2534290808 From what I can see, this will not move forward for 2 reasons:

- The CLA needs to be signed, as googlebot mentioned
- The issues raised by `analyze` need to be fixed:

```
  info - Specify type annotations at lib/palette_generator.dart:282:35 - (always_specify_types)
  info - Set literals were not supported until version 2.2, but this code is required to be able to run on earlier versions at lib/palette_generator.dart:282:35 - (sdk_version_set_literal)
  info - Prefer const with constant constructors at test/palette_generator_test.dart:105:19 - (prefer_const_constructors)
  info - Prefer const with constant constructors at test/palette_generator_test.dart:115:14 - (prefer_const_constructors)
  info - Prefer const with constant constructors at test/palette_generator_test.dart:122:14 - (prefer_const_constructors)
```

If you need help with the second point, let us know. If you don't agree with the CLA, also let us know, so we can open a separate PR that can be merged. Thank you for getting back to us.

@adrianvintu if you need a workaround for now, you can consider forking the patch fork :) or using it directly in your pubspec:
```
  palette_generator:
    git:
      url: git://github.com/2534290808/packages.git
      path: packages/palette_generator
      ref: patch-1
```

**Comment by adrianvintu** [comment]
@andreidiaconu holy shmoly Andrei, thank you for the cool workaround.

Wish you all the best!

**Comment by tvolkert** [comment]
This is also fixed in https://github.com/flutter/packages/pull/24, which contains the analysis error fixes and a version bump as well, so I'm going to close this PR in favor of that one.

Sorry for the dup - I only saw this PR after I sent the other one!

**Comment by tvolkert** [comment]
Ok, https://github.com/flutter/packages/pull/24 is merged.  I don't have permission to upload a new version of the package.    @gspencergoog can you add me as an uploader and/or publish a new version?

**Comment by gspencergoog** [comment]
I added you as an uploader, and I also published a new version.

**Pull request closed without merging**
