### PR TITLE
[cross_file] Added example and migrated tests

### PR DESCRIPTION
**Pull request by balvinderz**
Added example for cross file
 Migrated web tests to integration_test
 Migrated io tests to flutter_test

Fixes 
1. https://github.com/flutter/flutter/issues/89693
2. https://github.com/flutter/flutter/issues/93073

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [X] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by balvinderz** [comment]
@ditman  can you please review 😄 

Also i am not sure if `run_tests.dart` and `dart_test.yaml` are needed anymore

**Comment by ditman** [comment]
@balvinderz our CI is more or less ready to understand different platforms in different packages, but this change still needs some extra changes to pass analysis.

Can you check the CI failures and try to fix them? Some are very simple, for example I think that the dart_unit_tests checks are failing because you completely removed `test`, instead of leaving a small [test directory](https://github.com/flutter/plugins/tree/main/packages/video_player/video_player_web/test) like we do in the other plugins that use integration_test.

Alternatively, dart:vm tests could still live as unit tests, without the need to make them integration tests?

(Integration tests were only needed for web packages so we could use `flutter drive` to start a Chromium browser and have a browser environment to run tests. Moving the tests for native to integration (without really testing anything extra) is probably going to make them slower.)

**Review by ditman — CHANGES_REQUESTED** [review]
This still needs more love from @balvinderz, please, try to make the CI checks pass :)

**Comment by balvinderz** [comment]
> Can you check the CI failures and try to fix them? Some are very simple, for example I think that the dart_unit_tests checks are failing because you completely removed `test`, instead of leaving a small [test directory](https://github.com/flutter/plugins/tree/main/packages/video_player/video_player_web/test) like we do in the other plugins that use integration_test.

Why is CICD checking for tests folder in example folder? I checked and no other packages contain test folder in the example folder.

> Alternatively, dart:vm tests could still live as unit tests, without the need to make them integration tests?

`x_file_io_test.dart` still lives inside test folder. I have just migrated them from package:test to package:flutter_test

**Comment by ditman** [comment]
> I checked and no other packages contain test folder in the example folder.

Every web plugin contains integration tests in the `example` directory :) (check in flutter/plugins!)

**Comment by balvinderz** [comment]
> > I checked and no other packages contain test folder in the example folder.
> 
> 
> 
> Every web plugin contains integration tests in the `example` directory :) (check in flutter/plugins!)

Yes they do but the folder is named as `integration_test` . But here CICD check is explicitly looking for a `test` folder in the example directory.

**Comment by ditman** [comment]
@balvinderz this might be the first package that is web+mobile in the same package, rather than being split into the different platforms, and that's probably confusing CI/CD.

**Comment by stuartmorgan** [comment]
> But here CICD check is explicitly looking for a `test` folder in the example directory.

And it doesn't find it, and skips that test for the example, as expected.

The failure is not from the example, it's from the top-level package:
```
Running command: "dart run test" in /tmp/cirrus-ci-build/packages/cross_file
Could not find package `test` or file `test`
```

Probably because you are trying to use `flutter_test` in a package that doesn't have a Flutter dependency (and thus is run via `dart run test`, not `flutter test`).

**Comment by balvinderz** [comment]
Not getting enough time to work. Will try to reopen this when I get time.

**Pull request closed without merging**
