### PR TITLE
[google_maps_flutter] remove warning when cloudMapId is used

### PR DESCRIPTION
**Pull request by cedvdb**
fix [#fix #149060](https://github.com/flutter/flutter/issues/149060)
should be test-exempt, just warning removal.

*List which issues are fixed by this PR. You must list at least one issue.*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by cedvdb** [comment]
@ditman can this be test exempt ?

**Comment by stuartmorgan** [comment]
> should be test-exempt, just warning removal

The reason this PR eliminates the warning is that it changes the behavior of the plugin; it is not exempt.

**Comment by cedvdb** [comment]
I would have expected tests to fail if behaviors were changed

**Comment by cedvdb** [comment]
I'm closing this because I don't have the time to look into it

**Comment by cedvdb** [comment]
I'm not sure what behavior change you are referring to ? I expected to rely on the existing tests to see if I broke something or not. If that cannot be done I'm not willing to go forward with this, so I'll close

**Comment by stuartmorgan** [comment]
> I'm not sure what behavior change you are referring to ?
> Maybe the fact that it is not passing styles anymore if the map ID is passed

Yes, exactly.

> which I thought was an implementation detail with no impact on behaviors.

It does have an impact on behavior though; calling the underlying API incorrectly is causing a warning. That's why the issue and the PR exist in the first place.

**Comment by cedvdb** [comment]
> It does have an impact on behavior though; calling the underlying API incorrectly is causing a warning. That's why the issue and the PR exist in the first place.

It seems to me that it'd be more appropriate to test that there is no warning, You probably have good reasons to suggest that alternative. I'm interested in having those reasons here in case I end up having some time for this in the future.

My guess is that testing for warnings would be harder to write. However this kind of test could be reused for other warnings, so may be worth it. Not sure if there is a precedent to this.

**Comment by stuartmorgan** [comment]
We want our tests to test the code we control. We control whether we are making a combination of API calls that the docs explicitly say we shouldn't. We don't control what the result of doing that is, whether it's a warning to the console or something else.

> I was thinking about monkey patching console.warn and console.error to emit events

We don't want to intentionally introduce tests that are highly susceptible to out-of-band breakage due to changes in code we don't control.

**Pull request closed without merging**
