### PR TITLE
Add support for core packages.

### PR DESCRIPTION
**Pull request by godofredoc**
Tests sometimes fail because they can't find packages from the core
images.

### CODE REVIEW

**Comment by godofredoc** [comment]
Fixes:

https://github.com/flutter/flutter/issues/55165

**Comment by godofredoc** [comment]
Also fixes:

https://github.com/flutter/flutter/issues/50249

**Comment by goderbauer** [comment]
(PR triage): Gentle ping, do you still have plans for this PR?

**Comment by godofredoc** [comment]
> (PR triage): Gentle ping, do you still have plans for this PR?

Yes, merging.

**Pull request merged**
