### PR TITLE
[extension_google_sign_in_as_googleapis_auth]updated the code snippet

### PR DESCRIPTION
**Pull request by nirala96**
*Removed the unnecessary triple dots from the code snippets that get copied*

*issue - unnecessary triple dots that gets copied with the snippet*

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the `#hackers-new` channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by nirala96** [comment]
@googlebot I signed it!

**Comment by nirala96** [comment]
review-requested:[stuartmorgan]

**Comment by nirala96** [comment]
review-requested:[@stuartmorgan]

**Comment by stuartmorgan** [comment]
> * [ ]  I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
> * [ ]  I updated `CHANGELOG.md` to add a description of the change.

This needs a version update, otherwise it won't be published to pub.dev (which is presumably the point of the change)

**Comment by nirala96** [comment]
@stuartmorgan please review

**Comment by nirala96** [comment]
@stuartmorgan what else needs to be done?

**Review by stuartmorgan — APPROVED** [review]
LGTM, thanks for the submission!

**Pull request merged**
