### PR TITLE
[pigeon] Fix too little information when having an exception

### PR DESCRIPTION
**Pull request by fzyzcjy**
Please see the issue description

*List which issues are fixed by this PR. You must list at least one issue.*
Fix https://github.com/flutter/flutter/issues/96027

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Only a tentative PR. If you like it I will add tests to it

**Review by gaaclarke — COMMENTED** [review]
LGTM.  One nit, I'd remove the "to be" verb from the details "cause: foo" is is more clear than "cause is: foo" imo.  Let me know if you need guidance on testing.

**Comment by gaaclarke** [comment]
Heads up too, looks like the CI is in a wonky state.  Much of the team was out the past couple of weeks, so it will take a minute to clear it up.

**Comment by fzyzcjy** [comment]
> LGTM. One nit, I'd remove the "to be" verb from the details "cause: foo" is is more clear than "cause is: foo" imo. Let me know if you need guidance on testing.

done

**Comment by stuartmorgan** [comment]
> > Heads up too, looks like the CI is in a wonky state. Much of the team was out the past couple of weeks, so it will take a minute to clear it up.
> 
> ok I will wait

I'm not aware of any issues with CI. If this is about all the tasks that didn't run, it's because they are conditional on `format`, which failed.

**Comment by gaaclarke** [comment]
The analyze step is failing outside of this PR, it's not the contributor's fault, that's the wonkiness I was referring to.  I'll clear it up later today.

**Comment by gaaclarke** [comment]
This PR is old too, it might be that a rebase on master will clear up your issue if we've already cleared everything up like @stuartmorgan mentioned.

**Comment by stuartmorgan** [comment]
> The analyze step is failing outside of this PR, it's not the contributor's fault, that's the wonkiness I was referring to. I'll clear it up later today.

Oh, I see. That's an out-of-band failure for a recent new analysis warning, which definitely needs to be fixed (it just broke the tree, in fact).

**Comment by gaaclarke** [comment]
(you should rebase after https://github.com/flutter/packages/pull/544 lands)

**Comment by stuartmorgan** [comment]
I don't understand why this PR is showing as having been merged by me; what I merged was 544 (and this is--correctly--not showing on https://github.com/flutter/packages/commits/main).

**Comment by stuartmorgan** [comment]
The PR also shows 0 files now? I'm assuming this is related to:
> @pull pull bot force-pushed the main branch from 8d38e96 to 6dea894 2 hours ago

It seems like whatever that bot is destroyed your PR (likely because you called your branch "main")

**Comment by fzyzcjy** [comment]
All right... let me create a new pr

**Comment by fzyzcjy** [comment]
@gaa

> Let me know if you need guidance on testing.

Could you plz provide a bit of guidance? Thanks

(new) PR at: https://github.com/flutter/packages/pull/545

**Pull request merged**
