### PR TITLE
[url_launcher] Decode file URLs before passing it to ShellExecuteW

### PR DESCRIPTION
**Pull request by ftsui**
- ShellExecuteW does not handle file: urls that contain %-encoded UTF-8 strings correctly.  %-encoded ASCII
   strings are handled correctly, as are file "urls" that contain Unicode strings in its path component.
- This change perform URL decode on file: urls before passing to ShellExecuteW.

Fixes https://github.com/flutter/flutter/issues/156790

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Thanks for the contribution! Since the checklist isn't complete, I'm assuming this is a work in progress, and marking as a Draft accordingly. Once you've completed all of the steps, please mark it as ready for review.

It also appears that this PR assumes that `url_launcher` is only used for `file:` URLs. It's intended for use with any URL, and is very frequently used with schemes like `https` and `mailto`; a change that breaks those use cases would not be accepted.

**Review by stuartmorgan — APPROVED** [review]
LGTM, @cbracken for secondary review.

(Longer term we may need to revisit this logic; it's not at all clear that we are using `open` correctly current even though it mostly seems to work. The docs say "The item can be a file or folder", and even with this change we are passing a file *URL* rather than path, which may not be right. And it's not clear whether `open` is supposed to even work at all for other kinds of URLs, even though it apparently does.)

**Comment by ftsui** [comment]
My guess would be that file: is being handled by ShellExecute as a file moniker (which happens to have a similar syntax, but without URL encoding).  That might also explain starting the image editor instead of a browser when passed an image file.  It would be a somewhat unfortunate change in behavior if this were to be changed to pass all URLs to the browser.

**Comment by stuartmorgan** [comment]
> It would be a somewhat unfortunate change in behavior if this were to be changed to pass all URLs to the browser.

That's definitely an anti-goal. What we want is for the OS to determine the best handler for any given URL and pass it to that; that's explicitly what the underlying APIs used by all the other platform implementations of `url_launcher`. It seems like `open` is doing that in practice (at least mostly), but it doesn't seem like that's documented behavior so ideally we'd find something that explicitly is documented to do the thing we want (if there is such a thing on Windows).

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

lgtm. There's a joke to be made somewhere about 管理ing all of my various 家s, but I'm not sure I'm clever enough to make it.

**Pull request merged**
