### PR TITLE
Amend package:web tweaks to allow package:web roll

### PR DESCRIPTION
**Pull request by srujzs**
https://github.com/dart-lang/web/commit/7604578eb538c471d438608673c037121d95dba5 adds a number of APIs in order to get a more consistent API surface. This includes disablePictureInPicture and disableRemotePlayback, which both take in a bool and not a JSBoolean. However, it can't be rolled into google3 as this package will now be broken due to the way extension type methods take a higher precedence over extension methods.

This CL aligns those methods with the package:web equivalent so that usages of these methods can be consistent. controlsList is also amended to take in a String so that if it's ever added to the Web IDL, it doesn't conflict with the package:web definition that will be added then.

### CODE REVIEW

**Comment by srujzs** [comment]
Hmm, the bot isn't happy with my versioning here. Should I be doing a 2.3.0+1/2.3.1 and update the pubspec as well?

**Comment by ditman** [comment]
> Hmm, the bot isn't happy with my versioning here. Should I be doing a 2.3.0+1/2.3.1 and update the pubspec as well?

@srujzs Yes please, do it `2.3.1` (`2.3.0+1` is not a valid pub version number, ask me how I know :P)

As for the test, didn't we have overrides for these properties in the test code as well? (to make them "readable"?)

**Review by ditman — COMMENTED** [review]
> Hmm, the bot isn't happy with my versioning here. Should I be doing a 2.3.0+1/2.3.1 and update the pubspec as well?

@srujzs Yes please, do it `2.3.1` (`2.3.0+1` is not a valid pub version number, ask me how I know :P)

As for the tests, please check here, where we do something similar but for the integration tests of the package (I can help you running those locally if needed):

* https://github.com/flutter/packages/blob/main/packages/video_player/video_player_web/example/integration_test/pkg_web_tweaks.dart

**Comment by srujzs** [comment]
> Yes please, do it 2.3.1 (2.3.0+1 is not a valid pub version number, ask me how I know :P)

Done!

> As for the tests, please check here, where we do something similar but for the integration tests of the package

Ah I forgot that this repo has two such files to tweak `package:web`. Done.

**Comment by srujzs** [comment]
Friendly ping. :)

**Review by ditman — APPROVED** [review]
Thanks for the fix, ship it!

**Pull request merged**
