### PR TITLE
[go_router_builder] Activate leak testing

### PR DESCRIPTION
**Pull request by ValentinVignal**
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by ValentinVignal** [comment]
cc @polina-c

**Comment by ValentinVignal** [comment]
I think this PR is eligible for the tags `override: no versioning needed` and `override: no changelog needed`

**Comment by polina-c** [comment]
> I think this PR is eligible for the tags `override: no versioning needed` and `override: no changelog needed`

For changelog you can say something like "Increased protection ageinst memory leaks.".

Why versioning is not needed? Can you add more details?

Versioning is a good thing as a concrete version can be declared as 'bad', so users may want to be able to choose or hard code a version to avoid issues. (if i understand it right)

**Comment by ValentinVignal** [comment]
@polina-c I was copying what we did for https://github.com/flutter/packages/pull/7546. 

I don't mind adding a new version (I guess a patch increase?). Let me just explain why I thought it wouldn't need one first:
This change won't impact any user of the package. I see it as an update of the infra tools used by the maintainers. There won't be any changes in the API or the behavior of the package.

Having said that. Let me know if you still prefer me to update the version number and changelog. If yes, I'll do it :)

**Comment by ValentinVignal** [comment]
Also @polina-c @chunhtai , it looks like the ci `Linux analyze_downgraded stable` is not happy.

If I understand correctly, it runs `flutter downgrade` before analyzing the repo, and from the logs, it looks like it cannot find the symbol `LeakTesting` used in `flutter_test_config.dart`. Looking Looking at the logs, it seems the install versions `leak_tracker_flutter_testing: 2.0.0` and `leak_tracker_testing: 1.0.5`.

But `LeakTracking` was adding to `leak_tracker_testing: 9.0.9` (https://github.com/dart-lang/leak_tracker/pull/152).

Having said that, it didn't complain for the PR activating leak tracking on `go_router` (https://github.com/flutter/packages/pull/7546). Both of them have the same flutter and dart constraints: 

```yaml
sdk: ^3.3.0
flutter: ">=3.19.0"
```

https://github.com/flutter/packages/blob/b9ac917daeb0fbf5bd6ad4a7d2a69ab81749d767/packages/go_router/pubspec.yaml#L8-L10

https://github.com/flutter/packages/blob/b9ac917daeb0fbf5bd6ad4a7d2a69ab81749d767/packages/go_router_builder/pubspec.yaml#L9-L11

So I'm not sure what is the difference here or what I should do.

I found that `go_router` was listed in `script/configs/custom_analysis.yaml` but not `go_router_builder`. I don't know if that's relevant:

https://github.com/flutter/packages/blob/b9ac917daeb0fbf5bd6ad4a7d2a69ab81749d767/script/configs/custom_analysis.yaml#L1-L30

**Comment by chunhtai** [comment]
I don't think custom analysis has thing to do with this. my suspicion is that something in go_router bump the lower limit on the leak_tracker.

@polina-c do you know what may have cause this?

**Comment by polina-c** [comment]
> @polina-c I was copying what we did for #7546.
> 
> I don't mind adding a new version (I guess a patch increase?). Let me just explain why I thought it wouldn't need one first: This change won't impact any user of the package. I see it as an update of the infra tools used by the maintainers. There won't be any changes in the API or the behavior of the package.
> 
> Having said that. Let me know if you still prefer me to update the version number and changelog. If yes, I'll do it :)

Yes, your explanation makes sense for me. Here is my explanation: for repositories I am not familiar with, it is much easier for me to satisfy the lints, than to explain why i need exception.

You are welcome to go for exception, but I cannot help you with this for this repo, because i am not very familiar with it.

**Comment by chunhtai** [comment]
no changelog and no version bump reason: test only

**Comment by ValentinVignal** [comment]
@chunhtai @polina-c what do you think of?

```yaml
leak_tracker_flutter_testing: ">=3.0.0"
```

**Comment by polina-c** [comment]
> @chunhtai @polina-c what do you think of?
> 
> ```yaml
> leak_tracker_flutter_testing: ">=3.0.0"
> ```

If it makes all bots happy, I am for it :)

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by polina-c** [comment]
Thank you @ValentinVignal, for being persistent here.

**Pull request merged**
