### PR TITLE
Updates Dart formatting for the latest version of Flutter

### PR DESCRIPTION
**Pull request by bparrishMines**
The latest version of changes how Dart is formatted, so this updates all the packages affected. And does a manual roll.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by hellohuanlin — APPROVED** [review]

**Review by tarrinneal — APPROVED** [review]

**Comment by stuartmorgan** [comment]
That new switch formatting is somewhat unfortunate. Oh well 🤷🏻

**Comment by stuartmorgan** [comment]
I'm 100% okay with you removing all of the version bumps and changelogs here; the change is mechanical and uninteresting. That would make it much easier to land.

**Comment by bparrishMines** [comment]
If the tests fail after this last commit, then I'll revert the pubspec changes.

**Comment by bparrishMines** [comment]
@stuartmorgan @tarrinneal It looks like dart unit tests that test `pigeon` and `go_router_builder` are failing on stable. We may need to make some of their tests only run on a specific branch.

**Comment by stuartmorgan** [comment]
I wrote the Pigeon test that's failing here; let me see if I can figure out a good way to skip just that on stable before we turn the whole thing off.

**Comment by stuartmorgan** [comment]
PR posted for Pigeon, I can look at the go_router_builder test and see what it's doing exactly.

**Comment by stuartmorgan** [comment]
@bparrishMines I can't think of a quick way to hack around the go_router_builder test that would work for LUCI as well as Cirrus. I think the best option is to skip the test with an issue link, and assign that issue to a go_router owner to revisit this test. They can decide how to handle it (leave the test off, change the test, turn off all go_rounter_builder tests for one or the other branch for now, etc.)

**Review by reidbaker — APPROVED** [review]

**Review by cbracken — APPROVED** [review]
LGTM even though I'm not in love with the new style!

**Comment by domesticmouse** [comment]
> LGTM even though I'm not in love with the new style!

Agreed, not a fan

**Comment by stuartmorgan** [comment]
Looks like enough people weren't fans that it was reverted for now, so we can hold the roll until that bubbles through engine and framework.

**Pull request closed without merging**
