### PR TITLE
[camerax] Explicitly remove `READ_EXTERNAL_STORAGE` permission

### PR DESCRIPTION
**Pull request by camsim99**
Specifies that `READ_EXTERNAL_STORAGE` permission should not be implied from `WRITE_EXTERNAL_STORAGE` and thus removed from any merged manifests.

Fixes https://github.com/flutter/flutter/issues/131116.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by camsim99** [comment]
While this does remove the permission, discussing internally whether or not the permission may be actually needed for saving images. Will re-open once confirmed either way.

**Comment by camsim99** [comment]
It really doesn't seem like Flutter apps will need this permission to use the CameraX plugin because `READ_EXTERNAL_STORAGE` (and its replacements, since it is now deprecated) are really only necessary to read external files, but the plugin only writes to them. I confirmed that this change still allows image capture and video recording to work, so this is ready for review!

**Review by reidbaker — APPROVED** [review]

**Comment by camsim99** [comment]
Will land this after https://github.com/flutter/packages/pull/4620

**Comment by rohansohonee1** [comment]
The following change causes this permission to be removed from any merged manifests. So was this the intended behavior? 

Because this change gives an issue i.e if another plugin defines this permission of `READ_EXTERNAL_STORAGE` then it also gets removed from the merged manifest.

Eg: Using this plugin along with file_picker plugin.
file_picker requires this permission & it has been defined in it's manifest file as following:
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>
```
In the merged manifest logs it rejects the file_picker permission.
```
uses-permission#android.permission.READ_EXTERNAL_STORAGE
ADDED from [:camera_android_camerax] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/camera_android_camerax/intermediates/merged_manifest/debug/AndroidManifest.xml:17:5-19:31
REJECTED from [:file_picker] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/file_picker/intermediates/merged_manifest/debug/AndroidManifest.xml:9:5-11:38
	tools:node
		ADDED from [:camera_android_camerax] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/camera_android_camerax/intermediates/merged_manifest/debug/AndroidManifest.xml:19:9-28
	android:name
		ADDED from [:camera_android_camerax] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/camera_android_camerax/intermediates/merged_manifest/debug/AndroidManifest.xml:18:9-64
```


@camsim99 
Please let me know if I am missing something?

**Pull request closed without merging**
