### PR TITLE
Fix bug when parsing `DartOptions.copyrightHeader` with `@ConfigurePigeon`

### PR DESCRIPTION
**Pull request by bparrishMines**
When using a `pigeon.dart` file that passes a copyrightHeader to `DartOptions/ObjcOptions/JavaOptions` a type error is thrown. For example, the following code leads to the error below it:

```dart
import 'package:pigeon/pigeon.dart';

@ConfigurePigeon(PigeonOptions(
  dartOptions: DartOptions(copyrightHeader: <String>[
    'Copyright 2013 The Flutter Authors. All rights reserved.',
    'Use of this source code is governed by a BSD-style license that can be',
    'found in the LICENSE file.',
  ]),
))

@HostApi()
class MyApi { }
```

```
Unhandled exception:
type 'int' is not a subtype of type 'Iterable<String>?' in type cast
#0      DartOptions.fromMap (package:pigeon/dart_generator.dart:25:47)
#1      PigeonOptions.fromMap (package:pigeon/pigeon_lib.dart:195:25)
#2      Pigeon.run (package:pigeon/pigeon_lib.dart:1090:31)
#3      runCommandLine (package:pigeon/pigeon_cl.dart:14:17)
#4      main (file:///Users/bmparr/.pub-cache/bin/bin/bin/hosted/pub.dartlang.org/pigeon-1.0.16/bin/pigeon.dart:12:14)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
```

This happens because [DartOptions.copyrightHeader](https://pub.dev/documentation/pigeon/latest/dart_generator/DartOptions/copyrightHeader.html) requires an `Iterable`, but this is not supported in [_expressionToMap](https://github.com/flutter/packages/blob/main/packages/pigeon/lib/pigeon_lib.dart#L621) (a helper method that uses analyzer to read an annotation). This method is missing support of a `ListLiteral`, so it ultimately sets the `copyrightHeader` value to a `0` in the [else statement](https://github.com/flutter/packages/blob/main/packages/pigeon/lib/pigeon_lib.dart#L649) of the method. When the `pigeonOptions` map is parsed in [DartOptions.fromMap](https://github.com/flutter/packages/blob/main/packages/pigeon/lib/dart_generator.dart#L22), the code attempts to pass a `0` to the `copyrightHeader` field. This causes the error shown above.

This indicates there are two bugs when parsing a `@ConfigurePigeon` annotation:
1. `DartOptions.copyrightHeader`, `JavaOptions.copyrightHeader`, `ObjcOptions.copyrightHeader` are not parsed correctly and the value is set to `0`.
2. Errors caused by parsing does't prevent constructing a `PigeonOptions` object: https://github.com/flutter/packages/blob/main/packages/pigeon/lib/pigeon_lib.dart#L1090.

This PR attempts to solve both of these bugs by:
1. Adding support for `ListLiteral`s parsed in an annotation.
2. Exiting the program and printing parsing errors before they are used to construct a `PigeonOptions` class.

As a side note, I think `json_serializable` could probably help with avoiding these type of errors. We could try using it for all of the `PigeonOptions` classes?

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by gaaclarke** [comment]
Hey @bparrishMines can you provide more information in the description about what error you would run into?  I want to better understand what was going wrong.  That feature is used in the tests so I want to know how it is being used differently.  Looks like maybe you are using a List literal when you should be using a string?

I used the feature successfully here: https://github.com/flutter/plugins/pull/4732/files#diff-22cdf3f89e5734ff33fb6876645474cbabbd8f7fca4a4377539cb188599cc862R12

**Comment by bparrishMines** [comment]
@gaaclarke I updated the PR description. I meant to do it before I added you as reviewer, but I procrastinated 😅.

**Comment by bparrishMines** [comment]
Also, in your example, I believe you pass a file with a copyright header. My example passes the copyright header literal.

**Comment by gaaclarke** [comment]
> Also, in your example, I believe you pass a file with a copyright header. My example passes the copyright header literal.

Ah yea, that's how it was intended to be used and how it's documented: https://github.com/flutter/packages/blob/a7c287bd2a88c02750b6d30ab45ab64580082116/packages/pigeon/lib/pigeon_lib.dart#L166

If you wanted to pass it in as a literal instead of a path we should make it a different option instead of overloading this one since this is a breaking change.

**Comment by bparrishMines** [comment]
This isn't overloading a field. `PigeonOptions.copyrightHeader` takes a `String` path. `DartOptions.copyrightHeader` takes an `Iterable<String>`.

**Comment by gaaclarke** [comment]
> This isn't overloading a field. `PigeonOptions.copyrightHeader` takes a `String` path. `DartOptions.copyrightHeader` takes an `Iterable<String>`.

Okay, I'll give it another look, thanks for the background.

**Review by gaaclarke — APPROVED** [review]
LGTM, thanks!

**Comment by bparrishMines** [comment]
> Ahh okay, I see the problem. I wasn't thinking people would set the DartOptions.copyrightHeader directly. I was thinking they would be going through PigeonOptions.copyrightHeader. Now we are stuck with it though. I better be more careful about manipulating data between PigeonOptions and other options in the future.

If this is not the preferred way to set the `copyrightHeader`, I could also add an `@Deprecate` tag and create an issue to remove the field?

**Comment by gaaclarke** [comment]
I don't think that's necessary, thanks though.  I think what I should have done is kept the datatypes the same between DartOptions.copyrightHeader and PigeonOptions.copyrightHeader.  I sure it was some silly optimization like not reading through the file twice that lead me to it.  On the other side testing is a pain if we are using files instead of streams.  This is good for now and we can rework it later if a better alternative presents itself.

**Pull request merged**
