### PR TITLE
[flutter_lints] add sort_constructors_first lint

### PR DESCRIPTION
**Pull request by amanv8060**
add sort_constructors_first lint

Fixes https://github.com/flutter/flutter/issues/100996

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: configuration change.

**Review by goderbauer — CHANGES_REQUESTED** [review]
@amanv8060 Can you please file an issue at https://github.com/dart-lang/lints/issues to suggest that that lint should be added to `package:flutter_lints`? That way, we can have a discussion over there with all stakeholder involved to determine if this would be a good lint to enforce for everyone. 

Since adding a lint may produce new warnings for existing users of the package, it is considered a breaking change and we want to be extra careful with those. Therefore, we review suggested lints periodically and then update the lint package in one batch based on those reviews to avoid too much churn on users - instead of adding lints one-by-one.

**Comment by amanv8060** [comment]
Filed : https://github.com/dart-lang/lints/issues/76

**Comment by stuartmorgan** [comment]
> Therefore, we review suggested lints periodically and then update the lint package in one batch based on those reviews to avoid too much churn on users - instead of adding lints one-by-one.

Given this, is there any reason to leave this PR open?

**Comment by stuartmorgan** [comment]
> - [x] I updated CHANGELOG.md to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style).

@amanv8060 For future PRs, please be sure to review the style guide linked there again; the PR currently uses incorrect style—which I see is true of the previous update too, but the goal is to standardize for all packages going forward. (Using "Adds" instead of "Added" is ever the example in the guide for the verb form.)

**Comment by amanv8060** [comment]
Sure. Closing this PR.

**Pull request closed without merging**
