### PR TITLE
Enable prefer_mixin and bump plugin_platform_interface to 2.1.7

### PR DESCRIPTION
**Pull request by goderbauer**
Follow-up to https://github.com/flutter/packages/pull/5717#discussion_r1440717046.

### CODE REVIEW

**Comment by goderbauer** [comment]
@stuartmorgan This is the follow-up we discussed.

**Review by tarrinneal — APPROVED** [review]

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Review by ditman — APPROVED** [review]
🚀

**Comment by ditman** [comment]
🤞🎲🍀

**Comment by stuartmorgan** [comment]
This is still hitting the bad new `quick_actions` flake (which may well also be caused by https://github.com/flutter/flutter/issues/140987)

**Comment by goderbauer** [comment]
🥳

**Comment by goderbauer** [comment]
The tree turned red on this commit, but that's because of https://github.com/flutter/flutter/issues/141032 unrelated to this commit.

**Pull request merged**
