### PR TITLE
[file_selector] Fixed typo in code comment 'pltaform' -> 'platform'

### PR DESCRIPTION
**Pull request by BrutalCoding**
Found & fixed a typo while I was going through the code.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
Thanks for the contribution! This will need to complete the missing steps from the checklist that are causing `repo_checks` to fail in the CI before it can be fully reviewed.

**Comment by stuartmorgan** [comment]
@BrutalCoding Are you still planning on updating this PR as mentioned in the comment above?

**Comment by BrutalCoding** [comment]
> @BrutalCoding Are you still planning on updating this PR as mentioned in the comment above?

@stuartmorgan Apologies, I lost track of this issue.

Do you reckon that this PR is exempt from versioning? If so, we should apply the "override: no versioning needed" label if I'm not mistaken.

I'll try to spend some time on this PR somewhere this weekend. Seems like this PR is outdated by now so I'd prob start with updating/rebasing > checking ci logs > fix issues/tick off boxes > wait for feedback.

**Comment by stuartmorgan** [comment]
> Do you reckon that this PR is exempt from versioning?

Which of the exemptions would it fall under?

**Comment by stuartmorgan** [comment]
Closing in favor of https://github.com/flutter/packages/pull/6027; thanks for flagging the issue.

**Pull request closed without merging**
