### PR TITLE
[shared_preferences] Documented return values for remove and set methods.

### PR DESCRIPTION
**Pull request by RamonFarizel**
This PR adds documentation about the `remove` and `set` methods.
Those methods are basically following the `get` methods patterns, they throw an exception when the type is not expected.
Also, returns true when the operation succeeded.

List which issues are fixed by this PR. You must list at least one issue.
fixes:  [#146070](https://github.com/flutter/flutter/issues/146070)

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I [linked to at least one issue that this PR fixes] in the description above.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [X] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by tarrinneal** [comment]
All of the changelogs and pubspecs changes for the sub packages (android, foundation, etc) should be reverted. Only the subpackages with changes need them.

**Comment by tarrinneal** [comment]
I'm of the opinion that these changes to the doc comments aren't necessary, as the methods are self documenting.

You can't call `setString` with anything that isn't a string. Same with the other set methods.

The "returns true" comments are unfortunately not exactly correct, as some platforms don't actually have any response that verifies success. If I were to design this api myself today, I wouldn't have any bool returns for that reason.

@stuartmorgan what do you think?

**Comment by RamonFarizel** [comment]
Thanks for your thoughts, folks.

So if we are moving with updating the docs, what do you think is the best approach? 
1. Should we have this message repeated for all set and remove methods?
2. Only a single message mentioning that this is useful for all those methods?

**Comment by stuartmorgan** [comment]
Unless something is part of the comment directly on a method, it won't show up in IDE tools, and it will be harder to find even when looking at the header manually, so far fewer people would see anything added anywhere but to each method.

**Comment by RamonFarizel** [comment]
Okay, I've implemented the changes.

**Pull request closed without merging**
