### PR TITLE
[cross_file] Fix accidental constructor change

### PR DESCRIPTION
**Pull request by stuartmorgan**
In https://github.com/flutter/packages/pull/3095 I accidentally changed a constructor argument's nullability because I wasn't familiar with the correct variation of super parameters, and addressed a lint warning incorrectly. That version has been retracted; this restores the original behavior.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
The test is convoluted, but it works (and is arguably no more convoluted than the three-files-that-must-match structure of the class itself).

**Comment by stuartmorgan** [comment]
Filed https://github.com/dart-lang/sdk/issues/51196 for the false positive.

Although it's not actually clear to me why XFileBase has a constructor at all. Do you know what the reason was?

**Comment by asashour** [comment]
A humble suggestion, the code can be written as:

```dart
  XFile(
    String super.path, {
    String? mimeType,
    ...
  }) {
```

**Comment by stuartmorgan** [comment]
> A humble suggestion, the code could be written as

Indeed; fixed, and updated the PR description to reflect that the analyzer wasn't at all the problem. Thanks!

**Review by ditman — APPROVED** [review]
LGTM! Thanks for the test!!

**Comment by ditman** [comment]
> it's not actually clear to me why XFileBase has a constructor at all. Do you know what the reason was?

@stuartmorgan I don't remember, my only suspicion is to attempt to mandate that all subclasses (at least) have a `path` parameter? Not sure that's a valid solution (or requirement!)

**Pull request merged**
