### PR TITLE
[packages] Set parallelizable to NO to reduce test flakiness in packages project tests

### PR DESCRIPTION
**Pull request by LouiseHsu**
fixes https://github.com/flutter/flutter/issues/146358

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Do we always want this to be true in every project? If so, we should probably make a repo tool change that enforces it, so we don't invariably forget for new projects in the future.

**Comment by hellohuanlin** [comment]
interesting. if setting to NO works, i suspect the flakiness may be due to our OCMock usage where we somehow created some sort of side effect by mistake.

**Comment by LouiseHsu** [comment]
> interesting. if setting to NO works, i suspect the flakiness may be due to our OCMock usage where we somehow created some sort of side effect by mistake.

this is probably true, but when it hangs its very difficult to debug, bc no stack trace or errors are generated

**Comment by LouiseHsu** [comment]
> Do we always want this to be true in every project? If so, we should probably make a repo tool change that enforces it, so we don't invariably forget for new projects in the future.

I feel like we probably should, unless you think there would be a significant performance trade off if the tests aren't running parallel. But most of the packages that I looked at dont have this attribute set at all, these are the only ones.

**Comment by jmagman** [comment]
> But most of the packages that I looked at dont have this attribute set at all

What's the Xcode default when you create a new project?

**Comment by LouiseHsu** [comment]
> > But most of the packages that I looked at dont have this attribute set at all
> 
> What's the Xcode default when you create a new project?

parallelizable is set to YES by default when you create a new xcode project, but I think this is relatively new.

**Review by jmagman — APPROVED** [review]

**Comment by stuartmorgan** [comment]
> interesting. if setting to NO works, i suspect the flakiness may be due to our OCMock usage where we somehow created some sort of side effect by mistake.

Global mocking in OCMock is a strong contender for the source of problems that only show up when running in parallel. That's one of several reasons I'm extremely against adding any new usage of it in the reviews I do.

**Comment by stuartmorgan** [comment]
I'll file an issue for tooling enforcement of this; the PR can definitely land without the tooling part.

**Pull request merged**
