### PR TITLE
[google_maps_flutter] Add support for marker clustering - platform interface

### PR DESCRIPTION
**Pull request by jokerttu**
This PR introduces support for marker clustering

This is prequel PR for: https://github.com/flutter/packages/pull/4319
Containing only changes to `google_maps_flutter_platform_interface` package.

Follow up PR:s will hold the platform and app-facing plugin implementations.

Linked issue: https://github.com/flutter/flutter/issues/26863

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Comment by jokerttu** [comment]
Rebased and version number updated from 2.5.0 to 2.6.0

**Comment by stuartmorgan** [comment]
This has approval, so you can add the `autosubmit` label any time.

**Comment by jokerttu** [comment]
> This has approval, so you can add the `autosubmit` label any time.

@stuartmorgan This need to be done by someone who has permissions to add labels.

**Comment by stuartmorgan** [comment]
I can add it, but you're showing as an org member so you should be able to add labels. If that's not working there's a configuration problem somewhere, so please follow up in #server-support on Discord.

**Comment by stuartmorgan** [comment]
Well now I'm very confused.

**Comment by stuartmorgan** [comment]
Oh I see, you're a member of Flutter, but not flutter-hackers. I'm not sure how that happened.

**Comment by stuartmorgan** [comment]
I've nominated you for full access, so once you confirm in Discord we'll be able to land this with the one review :)

**Pull request merged**
