### PR TITLE
[cross_file] Use Blobs to store files on the web.

### PR DESCRIPTION
**Pull request by ditman**
This PR changes the backing data structure for XFile on the web to Blobs ([docs](https://developer.mozilla.org/en-US/docs/Web/API/Blob)). This allows the browser to handle much larger files, faster (up to 4GB in Safari, 8GB+ in FF and Chrome, at least on my machine).

## Issues

* Fixes https://github.com/flutter/flutter/issues/76036
* Fixes https://github.com/flutter/flutter/issues/88465
* Fixes https://github.com/flutter/flutter/issues/89014

This PR does _not_ cover (but might highlight the need for...):

* https://github.com/flutter/flutter/issues/91869
* https://github.com/flutter/flutter/issues/91867

## Tests

* All prior tests are passing
* Added unit-tests for the backing blob (even though it's probably just an implementation detail)

An example app using this code has been deployed here:

* https://dit-large-file-selector.web.app

It should let users pick up very large files, and still be able to iterate through them (it can take a few seconds for Safari/Chrome to "Load" the file after it's been selected. Firefox is much quicker doing that!)

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the `#hackers-new` channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by nwparker** [comment]
lgtm!

On clarification. The code implies the 4gb issue is for both mobile and desktop Safari. Is this correct?

**Comment by ditman** [comment]
> The code implies the 4gb issue is for both mobile and desktop Safari. Is this correct?

@nwparker This is correct*.

_* Tested with the latest Safari on the iOS Simulator, verified it crashes with > 4GB and parses with < 4GB._

**Comment by elliotsayes** [comment]
This does not appear to fix the issue for large files (~3.5GB).

In `Future<Blob> get _blob`
the code hangs indefinitely on:
`request = await HttpRequest.request(path, responseType: 'blob');`
For smaller files, e.g. around 50mb, the request does not hang.

Loading the path in the browser (e.g. `blob:http://localhost:58178/c2909ba7-faee-401b-b471-b2d010c9a976`) works fine to e.g. play/seek a video, regardless of file size.

**Comment by stuartmorgan** [comment]
This PR landed over a year ago, so can't be changed. Issues should be reported in the issue tracker.

**Comment by elliotsayes** [comment]
If it will be left open for over a year without a fix like https://github.com/flutter/flutter/issues/91867 then, respectfully, I don't see the point

**Pull request merged**
