### PR TITLE
[flutter_adaptive_scaffold] Make drawer items scrollable

### PR DESCRIPTION
**Pull request by percula**
This PR makes the drawer navigation list scrollable. Previously, if a large amount of navigation items were used, they would be cut off.

Fixes flutter/flutter#114175

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@gspencergoog From triage: Ping on this review?

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Sorry for the slow review.  cc @a-wallen for second review.

**Review by a-wallen — APPROVED** [review]

**Comment by gspencergoog** [comment]
@percula  Looks like the formatting needs to be fixed.

See [the error](https://github.com/flutter/packages/pull/2744/checks?check_run_id=9150116862) for a command that will fix it.

**Comment by gspencergoog** [comment]
Looks like you might have merged instead of rebased. You'll want to rebase your changes and resolve the conflicts.

Let me know if you need some help with that.

**Comment by percula** [comment]
@gspencergoog Sorry about that, I'm pretty sure I selected "rebase" in Android Studio but it did do something funky after that 🤷. Should be good now!

**Comment by gspencergoog** [comment]
Oh, I see that it doesn't actually have any tests for the new scrollable functionality.  Could you add a test for that so that it doesn't get broken in the future?

**Comment by stuartmorgan** [comment]
What's the status of this PR? Is it still waiting for more tests?

**Review by a-wallen — CHANGES_REQUESTED** [review]
@stuartmorgan this PR still needs tests.

**Comment by percula** [comment]
Yeah, sorry I've been a bit busy and haven't had time to write a test. Hopefully after the holidays I can get to it.

**Comment by gspencergoog** [comment]
@percula I can help you, but we have another issue: Alex has left the team, and since he's requested changes (and probably won't be checking back later to approve), we won't be able to land this particular PR because GitHub's UI doesn't have a way to override that.

If you could open a new PR with the same contents, we can proceed with figuring out your tests.

**Review by a-wallen — APPROVED** [review]
@gspencergoog the test LGTM. I'll approve so that this one can get merged.

**Comment by gspencergoog** [comment]
@a-wallen Thanks Alex, I appreciate it!

OK, @percula ,so now we just need to get this rebased onto the latest HEAD to get rid of the conflicts.

**Comment by stuartmorgan** [comment]
@percula Are you still planning on updating this to the latest `main` per the discussion above?

**Comment by percula** [comment]
Yep! Sorry, just got lost in my inbox. I'll do this tonight

**Comment by percula** [comment]
@stuartmorgan @gspencergoog Sorry for the delay, my fork is now synced and good-to-go!

**Comment by percula** [comment]
@gspencergoog Ok, my fork is rebased on the latest `main`. But the test is failing, can you help figure out why? As I mentioned, I don't have much experience with test and was having difficulty getting the test to find the hamburger menu and click it, so that the test could verify it can scroll to the last destination item.

**Comment by gspencergoog** [comment]
Looks like there are at least two things:

1) The test packages/flutter_adaptive_scaffold/test/adaptive_scaffold_test.dart is failing. Try running that locally to debug it. It looks like it can't find the widget to tap on that it used to find before your change.
2) There's a type annotation missing on packages/flutter_adaptive_scaffold/test/adaptive_scaffold_test.dart:248:62: "Missing type annotation. Try specifying the type 'NavigationDestination'."

**Comment by percula** [comment]
2 is an easy fix. Just need to commit the change.

1 though...I tried for over an hour on my local machine and got nowhere. I was hoping someone on the Flutter team might know of an existing test that taps the hamburger button, so I can copy that behavior and fix my test. Any ideas?

**Comment by stuartmorgan** [comment]
@percula Should this be marked as a draft? Have you reached out about your test issues on Discord?

**Comment by stuartmorgan** [comment]
Marking as a draft due to lack of updates; please feel free to mark as ready for review once the above is addressed.

**Comment by Hixie** [comment]
@percula Thanks for your contribution. It sounds like you don't have the bandwidth to work on this right now, so I'm going to close this PR and let people know in the issue that you've done the bulk of the work and if anyone wants to finish it that they can start with your PR here. Thanks again for what you've done so far, and if you ever want to try to resume this work please don't hesitate to reach out on our discord (link in the contributing guidelines, see below)!

**Comment by percula** [comment]
@Hixie sounds good. I'm still open to working on this, but I got stuck when writing the test. I don't know how to get the test to tap the hamburger menu. If anyone knows how to do that, I'm all ears 🙂

**Pull request closed without merging**
