### PR TITLE
[most on Android] Bump compile SDK version to 34

### PR DESCRIPTION
**Pull request by camsim99**
This PR does the following:

1. Bumps compile SDK version to 34 for all packages on Android besides `webview_flutter_android`, which is blocked by finishing https://github.com/flutter/flutter/issues/137082.
2. Bumps legacy all_packages app to 33 because compiling failed after completing 1 (see example of failing build [here](https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_build_all_packages%20master/5159/overview)). There was a Flutter fix available, so I believe this bump is safe.
3. Replaces all deprecated `compileSdkVersion` usages with `compileSdk`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by camsim99** [comment]
@stuartmorgan before taking out of draft mode, just want to verify that no version changes are needed here? I was planning to override.

**Comment by stuartmorgan** [comment]
> @stuartmorgan before taking out of draft mode, just want to verify that no version changes are needed here? I was planning to override.

This gets into specifics of Android build system bits that I'm always somewhat fuzzy on. Does changing this in a plugin's build.gradle affect plugin client builds in any way? If so, it's strongly preferred to bump versions, so that if it, say, unexpectedly breaks something we catch that now, not later when someone else happens to land some unrelated change, and then we have to try to figure out which change caused the problem. If it only affects things like our unit test builds in CI, then it doesn't need a version or CHANGELOG.

**Review by reidbaker — APPROVED** [review]

**Comment by camsim99** [comment]
> > @stuartmorgan before taking out of draft mode, just want to verify that no version changes are needed here? I was planning to override.
> 
> This gets into specifics of Android build system bits that I'm always somewhat fuzzy on. Does changing this in a plugin's build.gradle affect plugin client builds in any way? If so, it's strongly preferred to bump versions, so that if it, say, unexpectedly breaks something we catch that now, not later when someone else happens to land some unrelated change, and then we have to try to figure out which change caused the problem. If it only affects things like our unit test builds in CI, then it doesn't need a version or CHANGELOG.

This shouldn't affect plugin clients, so I'm going to keep this as is. This also aligns with what's written in the [wiki](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version), so someone must have had the same question :)

**Review by gspencergoog — APPROVED** [review]

**Review by Piinks — APPROVED** [review]
LGTM!

**Review by gmackall — APPROVED** [review]

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by bartekpacia** [comment]
Hi @camsim99, when will the updates be released?

**Comment by stuartmorgan** [comment]
We don't generally do releases for `compileSdk` changes. What's the use case where the `compileSdk` is affecting you?

**Comment by bartekpacia** [comment]
Please see https://github.com/flutter/flutter/issues/63533#issuecomment-2027851231

**Comment by stuartmorgan** [comment]
> Please see [flutter/flutter#63533 (comment)](https://github.com/flutter/flutter/issues/63533#issuecomment-2027851231)

Interesting. @reidbaker @camsim99 It sounds like we should revisit the version bump exemption for `compileSdk` changes.

**Comment by reidbaker** [comment]
Yeah I maintain that there isnt a large impact but we wouldnt want a long time to pass without a published version being shipped.

**Comment by stuartmorgan** [comment]
I'll update the wiki to remove that then; the carve-out is only supposed to be for things with no client benefit (for exactly that reason, we used to have things clients actually wanted sitting unpublished for a long time.

**Comment by bartekpacia** [comment]
Thanks a lot. This change will reduce my CI build times.

**Pull request merged**
