### PR TITLE
[go_router] Add `titleBuilder` to `GoRoute` and `GoRouterState`

### PR DESCRIPTION
**Pull request by getBoolean**
This is something I hacked together, bringing the `titleBuilder` from `auto_route` to `go_router`. I suspect it will need some changes, as I am not familiar with the internals of GoRouter.

- Issue: https://github.com/flutter/flutter/issues/140297

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by chunhtai** [comment]
This seems to be a very limited use case, I think the root problem is that the shellroute doesn't have information about the current child. I think this is something we should figure out a better API to expose such thing. WDYT?

**Comment by getBoolean** [comment]
@chunhtai yes that would work, though I wasn't able to come up with a more generic solution without casting. Perhaps a solution could involve generics.

**Comment by getBoolean** [comment]
I experimented with having adding generic type that the custom data builder can return. it is possible, but i had to add generics to nearly every go_router class. (Probably not what we want, but what are your thoughts?)
https://github.com/getBoolean/flutter_packages/commit/80a70229bf2edd7770d71deb8f03d419ab7bdfba

**Comment by getBoolean** [comment]
In 0ddddb6, I converted the title builder to extensions, similar to Flutter's theme extensions. I think this would work the best @chunhtai 

Usage:

```dart
GoRoute(
  path: 'b',
  extensions: <GoRouterStateExtensionBuilder>[
    (_, __) => const RouteTitleExtension('B'),
    (_, __) => const OtherCustomDataExtension('B.2'),
  ],
  builder: (BuildContext context, GoRouterState state) {
    return const Scaffold(
      body: Text('Screen 2'),
    );
  },
)

class RouteTitleExtension
    implements GoRouterStateExtension<RouteTitleExtension> {
  const RouteTitleExtension(this.title);

  final String title;
}

GoRouterState.of(context).extension<RouteTitleExtension>(context).title
```

**Comment by getBoolean** [comment]
New PR opened based on 13.0.0 https://github.com/flutter/packages/pull/5736

**Pull request closed without merging**
