### PR TITLE
[webview_flutter_platform_interface][webview_flutter_wkwebview] Fix inconsistent imports

### PR DESCRIPTION
**Pull request by bparrishMines**
Pushing the plugin internally causes errors from these imports. This fixes them to follow the convention of all the other imports.

This is only changing imports so not tests and no version bump.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
LGTM

I wonder how that Dart code even compiled; it has an extra level of `../` unless I'm misreading it.

**Comment by stuartmorgan** [comment]
> I think it's correct assuming`../../` takes you to the `lib` folder.

But the file it's in is `webview_flutter_platform_interface/lib/src/platform_webview_controller.dart`; `../..` should just be `webview_flutter_platform_interface`.

**Comment by bparrishMines** [comment]
Ah, I see what you mean now. 

Just tested it and turns out that all of these are valid: 

```dart
import '../src/platform_navigation_delegate.dart';
import '../../src/platform_navigation_delegate.dart';
import '../../../src/platform_navigation_delegate.dart';
import '../../../../src/platform_navigation_delegate.dart';
import '../../../../../src/platform_navigation_delegate.dart';
```

**Comment by bparrishMines** [comment]
This fails though:

```dart
import '../../lib/src/platform_navigation_delegate.dart';
```

I think the compiler considers `lib` as the root folder. So any number of `../` will just equal the root folder. Same with bash.

**Pull request merged**
