### PR TITLE
[pigeon] Fix C++ generator's handling of non-class host APIs

### PR DESCRIPTION
**Pull request by stuartmorgan**
Overhauls the way arguments and return types are handled for host APIs:
- Fixes handling of non-class types
- Changes the way optional types are represented
- Switches from `unique_ptr` for return types, which are awkward to use and still had a copy at the encoding step, to an approach that relies on move semantics and RVO for efficiency. Copies are possible (e.g., if someone defeats RVO in their host API implementation), but it should hopefully give us a good balance of efficiency and ease of use.

This ports several of the missing native tests from iOS to Windows in order to give meaningful coverage of these changes. It also adds significant Dart unit testing of the type handling.

To limit PR scope, this does not address:
- Enums as arguments, which are almost certainly still broken.
- Flutter APIs, which still assumes data classes.

Those can be fixed in follow-ups.

Fixes https://github.com/flutter/flutter/issues/105164
Fixes https://github.com/flutter/flutter/issues/105057

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by azchohfi** [comment]
RVO is confusing. Still reviewing this.

**Comment by azchohfi** [comment]
I'm thinking here that since all the custom messages are also wrapped with an `ErrorOr<X>` wrapper, it means that there is a runtime decision for which object is created (either an Error **or** X), which means (from my understanding) that it will not use RVO. We still benefit from move ctors, but not RVO, right? Did I get it wrong?

**Comment by stuartmorgan** [comment]
(https://github.com/flutter/plugins/pull/6035 is an example of this PR in action if it's helpful for reviewing)

**Comment by stuartmorgan** [comment]
@azchohfi Do you think you'll be able to review this in the next couple of weeks?

If not, @gaaclarke could you take a look?

**Comment by azchohfi** [comment]
I completely forgot about this. I had half-reviewed it already, but thanks for the ping. Will do!

**Comment by stuartmorgan** [comment]
Thanks! I'll try to get to the other follow-ups (style fixes, Flutter API tests and type changes) relatively soon now that this is complete.

**Pull request merged**
