### PR TITLE
[various] Add `http` 1.0 compatibility

### PR DESCRIPTION
**Pull request by stuartmorgan**
The `http` package was updated to 1.0. There are no change that affect our usage (it just adds new class restrictions), so this extends all dependencies to include both 0.13.x and 1.x.

All changes here are tool-applied (`update-dependencies` and `update-release-info`) except for the script/tools/ pubspec update, so are identical in all packages.

Fixes https://github.com/flutter/flutter/issues/127926

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by ditman — APPROVED** [review]
LGTM! (Restarted a CI check that had timed out with an "Infra Issue")

**Comment by ditman** [comment]
Hm, the Windows failure seems related to failing to run Chrome tests in `google_maps_flutter`?

```
============================================================
|| Running for packages/google_maps_flutter/google_maps_flutter [@5:29]
============================================================
[0m
Running command: "flutter.bat test --color --platform=chrome" in C:\b\s\w\ir\x\w\packages\packages\google_maps_flutter\google_maps_flutter

...

00:00 +0: compiling C:/b/s/w/ir/x/w/packages/packages/google_maps_flutter/google_maps_flutter/test/circle_updates_test.dart
00:00 +0 -1: compiling C:/b/s/w/ir/x/w/packages/packages/google_maps_flutter/google_maps_flutter/test/circle_updates_test.dart [E]
  Failed to load "C:/b/s/w/ir/x/w/packages/packages/google_maps_flutter/google_maps_flutter/test/circle_updates_test.dart":
  Failed to find ".\Google\Chrome\Application\chrome.exe" in the search path.
    Command: .\Google\Chrome\Application\chrome.exe 
  package:process/src/interface/local_process_manager.dart 56:7    LocalProcessManager.start
  package:flutter_tools/src/base/error_handling_io.dart 689:24     ErrorHandlingProcessManager.start.<fn>
  package:flutter_tools/src/base/error_handling_io.dart 559:20     _run
  package:flutter_tools/src/base/error_handling_io.dart 688:12     ErrorHandlingProcessManager.start
  package:flutter_tools/src/web/chrome.dart 260:53                 ChromiumLauncher._spawnChromiumProcess
  package:flutter_tools/src/web/chrome.dart 219:36                 ChromiumLauncher.launch
  ===== asynchronous gap ===========================
  package:flutter_tools/src/test/flutter_web_platform.dart 665:29  BrowserManager.start
  ===== asynchronous gap ===========================
  package:flutter_tools/src/test/flutter_web_platform.dart 448:25  FlutterWebPlatform.load
  ===== asynchronous gap ===========================
  package:test_core/src/runner/loader.dart 232:27                  Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  package:test_core/src/runner/load_suite.dart 98:19               new LoadSuite.<fn>.<fn>
  
00:00 +0 -1: compiling C:/b/s/w/ir/x/w/packages/packages/google_maps_flutter/google_maps_flutter/test/google_map_test.dart
00:00 +0 -2: compiling C:/b/s/w/ir/x/w/packages/packages/google_maps_flutter/google_maps_flutter/test/google_map_test.dart [E]
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1391:47                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1399:13                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/isolate_patch.dart 189:12      _RawReceivePort._handleMessage
```

That shouldn't be happening, should it?

**Comment by ditman** [comment]
Probably needs to be added here?

* https://github.com/flutter/packages/blob/main/script/configs/windows_unit_tests_exceptions.yaml#L18

(I don't understand why this didn't show up before, or is this a result of the endorsement?)

**Comment by stuartmorgan** [comment]
> (I don't understand why this didn't show up before, or is this a result of the endorsement?)

I'm not sure why it didn't show up in your endorsement PR, since I believe having the web plugin entry is what triggers that change. Weird.

https://github.com/flutter/packages/pull/4152

I think the fact that it's not looking for inline implementation is probably a bug in the tooling though.

**Review by tarrinneal — APPROVED** [review]

**Pull request merged**
