### PR TITLE
[camerax] Fix CameraInfo cast causing failure in integration test

### PR DESCRIPTION
**Pull request by camsim99**
Fixes a cast causing a post-submit failure for the Flutter roll into packages: https://github.com/flutter/packages/runs/12290760669.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
LGTM.

Do we know how a roll broke this?

**Comment by camsim99** [comment]
> Do we know how a roll broke this?

I'm actually confused about this, but this test started breaking for me late last week after making no changes to anything related (except maybe run the test with the `master` Flutter branch, which I'm guessing may be the common thread). The integration test also passes on one device, but not the other. Because of that, my guess is that it's something with Dart but I'm not sure if that makes sense...

**Comment by camsim99** [comment]
Also, @stuartmorgan is this going to be able to land or will submit-queue block it?

**Comment by stuartmorgan** [comment]
The `warning: land on red to fix tree breakage` label will allow autosubmit to land into a red tree, for cases like this one.

**Pull request merged**
