### PR TITLE
[cross_file] Removed unused Flutter dependencies.

### PR DESCRIPTION
**Pull request by tomassasovsky**
Removed unused Flutter dependencies to the cross_file package. Can now be imported and used from other Dart packages without the need of making it a Flutter package.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by ditman** [comment]
Very interesting change, I'll get this reviewed on monday!

**Comment by tomassasovsky** [comment]
For sure; at work, we have a Flutter package that wraps around all endpoints we have in our backend. This is because we have 2 apps sharing the same API, so it gets imported into both of them.

The issue is that we're using the [pkg:tus_client](https://pub.dev/packages/tus_client) for file uploads, and since it has cross_file as a dependency, it needs the flutter SDK as a dependency also, which there really is no need for.

My goal with this is to make the pkg:cross_file, pkg:tus_client, and our API Client one, Dart ones so that they can be imported without the need for the Flutter SDK.

Regarding the **Tree Hygiene** issue, what shall I do?

**Comment by ditman** [comment]
> Regarding the Tree Hygiene issue, what shall I do?

@tomassasovsky Try not to use `main` as the branch that you use to send pull requests to the repos :)

**Comment by tomassasovsky** [comment]
> Try not to use `main` as the branch that you use to send pull requests to the repos

I'll keep that in mind, thanks!
Shall I close this PR and make a new one from another branch?

Also, I've opened an [issue](https://github.com/flutter/flutter/issues/102934) for this.

**Comment by ditman** [comment]
> Shall I close this PR and make a new one from another branch?

Yes, please, AFAIK I don't know how branches can be switched within a PR, but PRs are free. Closing this one!

**Comment by tomassasovsky** [comment]
@ditman is there a convention set on branch naming for the flutter repository?

**Comment by ditman** [comment]
> 



> @ditman is there a convention set on branch naming for the flutter repository? how should I call the branch for this issue, for example?

AFAIK no, there's no naming convention because the branch stays in your repo (**don't make it offensive, I guess?** 😄). I'd call this something like: `cross-file-remove-flutter-dep` or similar. Alternatively, I've also used: `issue-XYZ` as the branch name when the fix is very specific to an issue or I can't think of a good (short-ish) name for the branch 😅

**Comment by tomassasovsky** [comment]
great! following this up on https://github.com/flutter/packages/pull/1712!

**Pull request closed without merging**
