### PR TITLE
[git] Ignore .uuid files that have started popping up.

### PR DESCRIPTION
**Pull request by ditman**
Ignores junk (?) `.uuid` files that seem to have started popping up in my working copy (generated by gradle?):

```console
dit@dit:~/github/packages$ git status
On branch main
Your branch is up to date with 'flutter/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	packages/adaptive_scaffold/example/android/.uuid
	packages/adaptive_scaffold/example/android/gradle/.uuid
	packages/adaptive_scaffold/example/android/gradle/wrapper/.uuid
	packages/animations/example/android/.uuid
	packages/animations/example/android/gradle/.uuid
	packages/animations/example/android/gradle/wrapper/.uuid
	packages/dynamic_layouts/example/android/.uuid
	packages/dynamic_layouts/example/android/gradle/.uuid
	packages/dynamic_layouts/example/android/gradle/wrapper/.uuid
	packages/flutter_markdown/example/android/.uuid
	packages/flutter_markdown/example/android/gradle/.uuid
	packages/flutter_markdown/example/android/gradle/wrapper/.uuid
	packages/go_router/example/android/.uuid
	packages/go_router/example/android/gradle/.uuid
	packages/go_router/example/android/gradle/wrapper/.uuid
	packages/palette_generator/example/android/.uuid
	packages/palette_generator/example/android/gradle/.uuid
	packages/palette_generator/example/android/gradle/wrapper/.uuid
	packages/rfw/example/hello/android/.uuid
	packages/rfw/example/hello/android/gradle/.uuid
	packages/rfw/example/hello/android/gradle/wrapper/.uuid
	packages/rfw/example/local/android/.uuid
	packages/rfw/example/local/android/gradle/.uuid
	packages/rfw/example/local/android/gradle/wrapper/.uuid
	packages/rfw/example/remote/android/.uuid
	packages/rfw/example/remote/android/gradle/.uuid
	packages/rfw/example/remote/android/gradle/wrapper/.uuid

nothing added to commit but untracked files present (use "git add" to track)
```

(No issue found about this, but it's bothering me a little bit) 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@GaryQian Any idea what these are? If it is gradle, we should probably be adding them to the template's ignore list too.

**Comment by ditman** [comment]
@GaryQian @stuartmorgan this is exactly what I'm seeing: 

```console
dit@box:packages/animations/example$ git status
On branch main
nothing to commit, working tree clean

dit@box:packages/animations/example$ flutter build apk
Running "flutter pub get" in example...                          1,153ms

💪 Building with sound null safety 💪

Calling mockable JAR artifact transform to create file: /usr/local/.../0b6088bfe77c50a75de8dff0b5129d0a/android.jar with input /usr/local/.../android-31/android.jar
Removed unused resources: Binary resource data reduced from 47KB to 38KB: Removed 19%
Running Gradle task 'assembleRelease'...                           68.6s
✓  Built build/app/outputs/flutter-apk/app-release.apk (18.6MB).

dit@box:packages/animations/example$ git status
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	android/.uuid
	android/gradle/.uuid
	android/gradle/wrapper/.uuid

nothing added to commit but untracked files present (use "git add" to track)
```

The problem was especially worse on my machine, after running some of the CI scripts locally (things that built many `example`s) ((not sure where those .uuid come from though))

**Review by stuartmorgan — APPROVED** [review]
LGTM I guess; I would prefer to actually know what's creating them and why we're not all seeing them, but it seems like a very low-risk ignore.

**Comment by ditman** [comment]
@stuartmorgan I don't mind this too much, as I said, it only becomes cumbersome when doing batch operations in the repo (which I guess is a CI problem, not a local dev problem 😛) ((PS: you must have seen them in some of your latest PRs though!))

**Comment by stuartmorgan** [comment]
Nope, I have literally zero of these files anywhere on my machine. 🤷🏻

**Comment by stuartmorgan** [comment]
(Just to be sure I tried your STR from above exactly; no `.uuid` files.)

**Comment by ditman** [comment]
> LGTM I guess; I would prefer to actually know what's creating them and why we're not all seeing them, but it seems like a very low-risk ignore.

I used `auditctl` and `ausearch -f "$(pwd)/android/.uuid"` and found the entry where the file seems to be created:

```
time->Fri Oct 28 15:07:34 2022
type=PROCTITLE msg=audit(1666994854.821:5576): proctitle=2F7573722F6C6F63616C2F676F6F676C652F686F6D652F6469742F6769746875622F666C75747465722F62696E2F63616368652F646172742D73646B2F62696E2F64617274002D2D64697361626C652D646172742D646576002D2D7061636B616765733D2F7573722F6C6F63616C2F676F6F676C652F686F6D652F6469742F67
type=PATH msg=audit(1666994854.821:5576): item=1 name="/usr/local/google/home/dit/github/packages/packages/animations/example/android/.uuid" inode=525088 dev=fe:01 mode=0100644 ouid=697382 ogid=89939 rdev=00:00 nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1666994854.821:5576): item=0 name="/usr/local/google/home/dit/github/packages/packages/animations/example/android/" inode=526139 dev=fe:01 mode=040750 ouid=697382 ogid=89939 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1666994854.821:5576): cwd="/usr/local/google/home/dit/github/packages/packages/animations/example"
type=SYSCALL msg=audit(1666994854.821:5576): arch=c000003e syscall=257 success=yes exit=9 a0=ffffff9c a1=7fabf5bc7d10 a2=80242 a3=1b6 items=2 ppid=46877 pid=202073 auid=697382 uid=697382 gid=89939 euid=697382 suid=697382 fsuid=697382 egid=89939 sgid=89939 fsgid=89939 tty=pts2 ses=4 comm="DartWorker" exe="/usr/local/google/home/dit/github/flutter/bin/cache/dart-sdk/bin/dart" subj==unconfined key=(null)
```

The `proctitle` bytes decode to:

`/usr/local/google/home/dit/github/flutter/bin/cache/dart-sdk/bin/dart--disable-dart-dev--packages=/usr/local/google/home/dit/g`

Which is most likely [this](https://github.com/flutter/flutter/blob/0b451b6dfd6de73ff89d89081c33d0f971db1872/bin/internal/shared.sh#L238), but at that point I don' t know how to dive deeper into which. #SadTrombone.

As @GaryQian mentioned, this seems to be related to `fontconfig` / `fc-cache` or some other tool from the family creating `.uuid` files and not cleaning them up afterwards.

I don't know why this happens on my machine and not others (maybe because I'm using the CRD graphical interface?)

**Comment by stuartmorgan** [comment]
Thanks for tracking it down that far!

We're definitely at the point of diminishing returns in terms of spending more time investigating, so let's just land this.

**Pull request merged**
