### PR TITLE
[go_router] Fixed TabView swiping in custom stateful shell route example 

### PR DESCRIPTION
**Pull request by tolo**
Updated `custom_stateful_shell_route.dart` example to better support swiping in TabView. Also added code to demonstrate use of PageView instead of TabView. Note that to be fully effective from a usability perspective, the PR flutter/packages#6467 (branch preloading) need also be merged. 

This PR addresses: 
* flutter/flutter#150837 
* flutter/flutter#112267

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Review by chunhtai — COMMENTED** [review]
Code LGTM, Can you add a test to make sure the fix is not reverted in the future?

**Comment by tolo** [comment]
I see some confusion in issues around go_router related to using CupertinoTabScaffold, so I thought I'd include that as well in the sample, since it's somewhat related. Perhaps it can contributed to remove some confusion. Let me know what you think.

**Comment by tolo** [comment]
Pushed an additional update with some cleanup & clarifications

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by tolo** [comment]
@chunhtai, which Discord channel do I need to be in (don't see any flutter-hackers), or might it just be that I haven't been logged in for a while?

**Review by hangyujin — APPROVED** [review]
LGTM

**Comment by hangyujin** [comment]
Hi @tolo! Thank you for contributing!

FYI: `Flutter-hackers` the bot mentioned is not a discord channels, it's a Github group. See the [contributor access](https://github.com/flutter/flutter/blob/master/docs/contributing/Contributor-access.md) wiki page for details.

**Comment by tolo** [comment]
> Hi @tolo! Thank you for contributing!
> 
> FYI: `Flutter-hackers` the bot mentioned is not a discord channels, it's a Github group. See the [contributor access](https://github.com/flutter/flutter/blob/master/docs/contributing/Contributor-access.md) wiki page for details.

Ah, my bad, thanks for the clarification @hangyujin 😄

**Pull request merged**
