### PR TITLE
[Go_Router] 117514: Added hasRoute to GoRouter -  Checks if the given path matches a registered route

### PR DESCRIPTION
**Pull request by dancamdev**
This is the implementation for a new feature suggested in [117514](https://github.com/flutter/flutter/issues/117514)

The issue does a great job explaining the use case.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by ahmednfwela** [comment]
instead of a `hasRoute`, can't we expose a `tryParseRoute` instead ? it will return `RouteMatchList?` which is more useful than just true/false

**Comment by dancamdev** [comment]
> instead of a `hasRoute`, can't we expose a `tryParseRoute` instead ? it will return `RouteMatchList?` which is more useful than just true/false

This provides a clearer API in my opinion, yes.

**Review by chunhtai — COMMENTED** [review]
We should open up the API before we do this. Right now I think the RoutMatchList is package level private.

**Comment by ahmednfwela** [comment]
@chunhtai are there specific members you want to hide/remove ? I think the current state of the package is too strict, as it's very hard to edit/use internal behavior without a complete fork of the package.
this goes back to the discussion in https://github.com/flutter/flutter/issues/107757

**Comment by chunhtai** [comment]
I think we should be able to open up all of them now, just need a bit more refactoring. It is the next thing on my list.

There shouldn't be any package level private, and it is not really private anyway...

**Comment by chunhtai** [comment]
Closing this pr as this would not be needed if the we open up the API.

**Pull request closed without merging**
