### PR TITLE
:bug: Fix typo in flutter provider import

### PR DESCRIPTION
**Pull request by JosephhBh**
Adding the ^ symbol which was missing in provider import : provider: 6.0.5

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by johnpryan — APPROVED** [review]

**Comment by chunhtai** [comment]
I am not entirely sure why the test would fail. but you should be able to reproduce it by running
```
./script/tool_runner.sh pubspec-check --min-min-flutter-version=3.0.0 --allow-dependencies=script/configs/allowed_unpinned_deps.yaml --allow-pinned-dependencies=script/configs/allowed_pinned_deps.yaml
```

**Comment by chunhtai** [comment]
i took a look at the code, it looks like only Redirect example uses provider, we can consider refactor the example to not use provider and remove the dependency entirely.

**Comment by chunhtai** [comment]
Hi @JosephhBh do you still plan to come back to this pr?

**Comment by JosephhBh** [comment]
Yes for sure , do you want to remove the make the refactor and remove the
provider package ?

**Comment by chunhtai** [comment]
I think we should remove the provider package from the dependency list and rewrite the redirection example using a custom inherited widget

**Comment by stuartmorgan** [comment]
> I am not entirely sure why the test would fail.

Please see the error output from the test, which links to our repo policy on dependencies.

**Comment by stuartmorgan** [comment]
@JosephhBh Are you still planning on updating this PR per the discussion above?

**Comment by chunhtai** [comment]
@JosephhBh I will close this pr for now, feel free to reopen if you have time to come back to this pr

**Pull request closed without merging**
