### PR TITLE
Add issues/PRs badges to README

### PR DESCRIPTION
**Pull request by moko256**
| Before | After |
|-|-|
|screenshot before PR|screenshot after PR|

This PR adds badges for each package's issues and PRs to README.

I found that some labels title are different in flutter/flutter and flutter/packages, but I use existing label title.
I found some package doesn't have each label, but I use this format: "p: " + package name. It's better to create this not to discrepancy.

Should I rename these labels in each repository? or leave without renaming this not to update existing link?

Packages doesn't have same label title in issues and PRs (empty = doesn't have label for them):
| Package name | Issues (flutter/flutter) | PRs (flutter/packages) |
|-|-|-|
| animations | p: animations | p: animation |
| css_colors |  | p: css_colors |
| flutter_lints | p: flutter_lints |  |
| go_router | p: go_router |  |
| pigeon | pigeon | p: pigeon |
| xdg_directories |  | p: xdg_directories |

Fixes flutter/flutter#103872.

No changes in `flutter/tests`.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [X] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by guidezpl** [comment]
I created the missing labels for flutter/flutter and flutter/packages

**Comment by stuartmorgan** [comment]
The PR labels would be created on demand by the auto-labeller, but the real problem is that https://github.com/flutter/packages/blob/main/.github/labeler.yml hasn't been updated to include those packages, which means the queries will often miss things.

Could you update that in this PR, since it's related?

**Comment by moko256** [comment]
Also, should I rename "p: animation" to "p: animations"? 

In master, this was associated with animation directory.
https://github.com/flutter/packages/blob/41c848cafe4c5c5d45d8dde260899832823c2c5d/.github/labeler.yml#L1-L2

**Comment by moko256** [comment]
I removed "p: bsdiff" and rename "p: animation" to "p: animations" in labeler.yaml.

**Pull request merged**
