### PR TITLE
[pigeon] add null safety guide to readme

### PR DESCRIPTION
**Pull request by fzyzcjy**
*Replace this paragraph with a description of what this PR is changing or adding, and why.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the `#hackers-new` channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by gaaclarke — APPROVED** [review]

**Comment by gaaclarke** [comment]
I tried to rebase this for you but I don't seem to have permissions.  I also tried tweaking the text:

```
## Null Safety (NNBD)

In order to generate null-safe code run the command line with the extra argument
`--dart_null_safety`. For example:
`flutter pub run pigeon --input ./pigeons/messages.dart --dart_null_safety`.
```

**Comment by fzyzcjy** [comment]
@gaaclarke Hmm so what can I do?

**Comment by gaaclarke** [comment]
You need to rebase onto master or give me permissions to push to your PR.

Rebasing will be something like this (its a bit weird because your branch is named master):
```
git fetch origin
git rebase -i <UPSTREAM REMOTE>/master
# handle conflicts
git add README.md # commit resolution to conflict
git rebase --continue
git push -f <YOUR REMOTE>
```

**Comment by gaaclarke** [comment]
Or if you don't want to deal with it, i can duplicate the change in a different PR.

**Comment by fzyzcjy** [comment]
@gaaclarke Sure. Let me rebase it.

**Comment by fzyzcjy** [comment]
@gaaclarke Done

**Pull request merged**
