### PR TITLE
[cross_file] Move from flutter/plugins.

### PR DESCRIPTION
**Pull request by ditman**
`cross_file` doesn't fit very well with the testing infra of flutter/plugins, since it's just a cross-platform abstraction of dart:io File, and not a proper plugin. 

It seems that flutter/packages might be a better home for this package, and it should have been always deployed here, but since it was forked off of a plugin, it lived until now in flutter/plugins.

This PR moves the package to flutter/packages, and only minimally changes code to comply with the slightly different analysis rules of this repo.

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the `#hackers-new` channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by ditman** [comment]
This is a [link with the changes after the package was moved](https://github.com/flutter/packages/pull/305/files/46020d9d1fc3c253815209d648d965d8d637f554..HEAD) to the new repo.

**Review by stuartmorgan — APPROVED** [review]
LGTM!

**Comment by ditman** [comment]
Merged and published: https://pub.dev/packages/cross_file/versions/0.3.1+1

**Comment by kevmoo** [comment]
Don't forget to update your table in the README 😄

**Comment by ditman** [comment]
> Don't forget to update your table in the README 😄

@kevmoo wow, I totally missed that one!

**Pull request merged**
