### PR TITLE
[pigeon] Fix void methods generated in Swift.

### PR DESCRIPTION
**Pull request by timukasr**
Issue: https://github.com/flutter/flutter/issues/111083

When Pigeon generates void methods for Swift, it currently returns `nil`. On Dart side, there is a check that produces PlatformException when null is received:
```
if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    }
```
Fixed by wrapping the `nil` using `wrapResult` method.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
This will definitely need a test, as noted by the bot comment above. @gaaclarke Don't we have an e2e test that does void function calls? Maybe it's not enabled for Swift?

@timukasr Could you please file an issue that shows an example Pigeon definition file that reproduces this, and reference it from the PR description, so we have all the relevant details captured?

**Comment by timukasr** [comment]
Created [issue](https://github.com/flutter/flutter/issues/111083) and added test.

**Review by gaaclarke — COMMENTED** [review]
This looks great but it needs a platform test too, not just a textual unit test.  That will allow the generated code to be compiled and executed.

I think a good place to put it would be here: https://github.com/flutter/packages/blob/main/packages/pigeon/platform_tests/ios_swift_unit_tests/ios/RunnerTests/AllDatatypesTests.swift

 All of those tests send and receive a piece of data, which is going to be different for our case.  I think this test is a good example: https://github.com/flutter/packages/blob/c2a064c1b7bbdabbfffc5f180f136281bf5e013d/packages/pigeon/platform_tests/ios_swift_unit_tests/ios/RunnerTests/PrimitiveTests.swift#L22

**Comment by timukasr** [comment]
Sry, seems too much hassle for me. Some else can take over or you can close the PR.

**Comment by stuartmorgan** [comment]
Thanks for the contribution! I'm going to go ahead and close this since you don't plan to proceed with it, but anyone interested in picking this up is welcome to fork this branch to create a new PR.

**Pull request closed without merging**
