### PR TITLE
Roll Flutter from fc8856eb80d3 to c40baf47c5c8 (57 revisions)

### PR DESCRIPTION
**Pull request by ditman**
Manual version of https://github.com/flutter/packages/pull/4269

----

Roll Flutter from fc8856eb80d3 to c40baf47c5c8 (57 revisions)

https://github.com/flutter/flutter/compare/fc8856eb80d3...c40baf47c5c8

2023-06-21 engine-flutter-autoroll@skia.org Roll Packages from 6e1918fa166c to 0fdf05f51029 (8 revisions) (flutter/flutter#129286)
2023-06-21 christopherfujino@gmail.com move test ownership from zanderso -> tools team (flutter/flutter#129199)
2023-06-21 42216813+eliasyishak@users.noreply.github.com Refactor `Analytics` global getter to point to context only (flutter/flutter#129196)
2023-06-21 engine-flutter-autoroll@skia.org Roll Flutter Engine from cfbd3652532d to f973fb4636d3 (1 revision) (flutter/flutter#129253)
2023-06-21 engine-flutter-autoroll@skia.org Roll Flutter Engine from 059643dcc8e3 to cfbd3652532d (1 revision) (flutter/flutter#129243)
2023-06-21 engine-flutter-autoroll@skia.org Roll Flutter Engine from 5313ca367549 to 059643dcc8e3 (1 revision) (flutter/flutter#129240)
2023-06-21 engine-flutter-autoroll@skia.org Roll Flutter Engine from 946f523859fe to 5313ca367549 (2 revisions) (flutter/flutter#129234)
2023-06-21 engine-flutter-autoroll@skia.org Roll Flutter Engine from e5a860c5479c to 946f523859fe (2 revisions) (flutter/flutter#129232)
2023-06-21 31859944+LongCatIsLooong@users.noreply.github.com Relax `OverlayPortal` asserts (flutter/flutter#129053)
2023-06-21 engine-flutter-autoroll@skia.org Roll Flutter Engine from adfc3af300a9 to e5a860c5479c (3 revisions) (flutter/flutter#129228)
2023-06-21 godofredoc@google.com Move all the firebase lab device configs to .ci.yaml. (flutter/flutter#129219)
2023-06-21 engine-flutter-autoroll@skia.org Roll Flutter Engine from 7d4abb81ccd1 to adfc3af300a9 (2 revisions) (flutter/flutter#129225)
2023-06-20 andrewrkolos@gmail.com update resolution-aware asset docs links (flutter/flutter#128769)
2023-06-20 jmccandless@google.com Fix: Magnifier appears and won't dismiss (flutter/flutter#128545)
2023-06-20 thkim1011@users.noreply.github.com DecoratedSliver (flutter/flutter#127823)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from 666244148e89 to 7d4abb81ccd1 (1 revision) (flutter/flutter#129217)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from 06d0c08460e5 to 666244148e89 (2 revisions) (flutter/flutter#129208)
2023-06-20 yeasinsheikh50@gmail.com fixed PreferredSize constuctor invocations (flutter/flutter#128181)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from 1c16af76ca26 to 06d0c08460e5 (3 revisions) (flutter/flutter#129200)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from ec64672afd91 to 1c16af76ca26 (1 revision) (flutter/flutter#129197)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from 4444ede34a9c to ec64672afd91 (3 revisions) (flutter/flutter#129194)
2023-06-20 15619084+vashworth@users.noreply.github.com Fix duplicate devices from xcdevice with iOS 17 (flutter/flutter#128802)
2023-06-20 ychris@google.com iOS info.plist template: make UIViewControllerBasedStatusBar to be true (flutter/flutter#128970)
2023-06-20 whesse@google.com Fix detection that tests are running on monorepo bots (flutter/flutter#129173)
2023-06-20 chingjun@google.com Use the new `getIsolatePauseEvent` method from VM service to check for pause event. (flutter/flutter#128834)
2023-06-20 31922733+SwaroopSambhayya@users.noreply.github.com Adding ScrollController support for Stepper widget (flutter/flutter#128814)
2023-06-20 engine-flutter-autoroll@skia.org Roll Packages from 59d93d64cb83 to 6e1918fa166c (6 revisions) (flutter/flutter#129176)
2023-06-20 thkim1011@users.noreply.github.com Refactor generate_localizations_test.dart (flutter/flutter#128974)
2023-06-20 kevinjchisholm@google.com [process] Add a design doc issue template. (flutter/flutter#128361)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from bd6d3fc90462 to 4444ede34a9c (1 revision) (flutter/flutter#129169)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from 73c4ba4240cc to bd6d3fc90462 (1 revision) (flutter/flutter#129168)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from 7ee874792067 to 73c4ba4240cc (1 revision) (flutter/flutter#129162)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from 6a6c8fb591f5 to 7ee874792067 (1 revision) (flutter/flutter#129160)
2023-06-20 leigha.jarett@gmail.com Add to API docs to explain what Assist and Suggestion chips are (flutter/flutter#129034)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from a91bb3f566b9 to 6a6c8fb591f5 (1 revision) (flutter/flutter#129158)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from e0d456d9251b to a91bb3f566b9 (1 revision) (flutter/flutter#129148)
2023-06-20 engine-flutter-autoroll@skia.org Roll Flutter Engine from 55418e648958 to e0d456d9251b (1 revision) (flutter/flutter#129146)
2023-06-19 engine-flutter-autoroll@skia.org Roll Flutter Engine from 84ecaa053ec6 to 55418e648958 (1 revision) (flutter/flutter#129145)
2023-06-19 engine-flutter-autoroll@skia.org Roll Flutter Engine from 23a2c246600f to 84ecaa053ec6 (2 revisions) (flutter/flutter#129142)
2023-06-19 tessertaha@gmail.com Introduce MaterialState `color` property for chips (flutter/flutter#128584)
2023-06-19 engine-flutter-autoroll@skia.org Roll Flutter Engine from 280491d4cc21 to 23a2c246600f (8 revisions) (flutter/flutter#129140)
2023-06-19 jason-simmons@users.noreply.github.com Fix an ordering dependency in the flutter_tools upgrade test (flutter/flutter#129131)
2023-06-19 engine-flutter-autoroll@skia.org Roll Flutter Engine from 164c6b49dfb5 to 280491d4cc21 (1 revision) (flutter/flutter#129102)
2023-06-19 tessertaha@gmail.com Fix `InputDecoration.applyDefaults` ignoring some properties (flutter/flutter#129010)
2023-06-19 engine-flutter-autoroll@skia.org Roll Flutter Engine from d298f0bf720c to 164c6b49dfb5 (1 revision) (flutter/flutter#129100)
2023-06-19 engine-flutter-autoroll@skia.org Roll Flutter Engine from 7ffa1355f718 to d298f0bf720c (24 revisions) (flutter/flutter#129092)
...

----

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by ditman** [comment]
I've never seen this; are we expecting a missing check?

Screenshot 2023-06-21 at 1 22 48 PM

**Comment by ditman** [comment]
https://github.com/flutter/flutter/issues/129134

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Comment by ditman** [comment]
(Looks like ci.yaml validation disappeared from this PR checks)

**Comment by ditman** [comment]
The check timed out, giving it another shot.

**Comment by ditman** [comment]
Clicking the Squash-And-Merge at a time where everything looks green, to get the roller rollin' again!

**Pull request merged**
