### PR TITLE
[ci] Enable more tests in Cirrus

### PR DESCRIPTION
**Pull request by stuartmorgan**
This brings the Cirrus configuration more in line with flutter/plugins,
to reduce testing diffs between the two repositories:
- Updates naming and grouping comments to match flutter/plugins to make
  them easier to compare.
- Enables building examples on all platforms. This was being done for
  Android, and iOS, and Windows, but not Linux, macOS, or web, which
  wasn't an intentional mismatch.
- Enables 'flutter drive' tests for web.
  - Does not enable them for other platforms as currently there is no
    need for them, and setup is non-trivial on some platforms (FTL
    secrets for Android, new Dockerfile dependencies for Linux).
- Enables native unit tests for all platforms. (In practice this is a
  no-op at the moment, but it's a very fast no-op that doesn't
  require extra setup.)

These CI configurations come almost directly from flutter/plugins.

Supporting changes:
- Rolls repo tooling forward to pick up support for `drive-examples` in
  non-plugin packages, and for running Dart unit tests in examples.
- Copies the `install_chromium.sh` script from flutter/plugins to
  support web `drive-examples`, and moves the existing version for
  benchmarks to a different name with a TODO to merge them.
- Removes unsupported platforms from `rfw/example/wasm` so
  that CI doesn't try to build them.
- Adds Linux desktop dependencies to the Dockerfile.
- Removes unnecessary libraries from `flutter_markdown`'s
  Linux example, which came from an old template, as we no longer
  tell people to install those libraries in our documentation.

Fixes https://github.com/flutter/flutter/issues/102851

No CHANGELOG change: The tweaked tests in `pointer_interceptor` don't need a CHANGELOG entry, since that's temporary code that will be removed once the current flutter `master` rolls into `stable`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@yjbanov @ditman Can the recent change to `pointer_interceptor`'s tests be made in a way that works for both stable and master, or do we need to stop testing stable for that package for now? Currently we can't turn on package example tests because it fails on stable: https://cirrus-ci.com/task/5694692015734784

**Comment by ditman** [comment]
> Can the recent change to pointer_interceptor's tests be made in a way that works for both stable and master

Checking.

**Comment by ditman** [comment]
(Note that we've marked this test as `ignored` in g3, so it might not be trivial :))

**Comment by ditman** [comment]
Hacky tweak that should enable this, here:

https://github.com/flutter/packages/pull/1731

(I can push those changes into this branch, so we can land both at once?)

**Review by ditman — APPROVED** [review]
If CI passes here, let's merge this so we get more testing going!

**Comment by stuartmorgan** [comment]
> /cc @stuartmorgan it seems the tool is not picking up updates to the PR text? `publishable` insists that we need a "No CHANGELOG change: XYZ" (but I added it?)

You have to re-push after updating the PR text; there's some sort of cache of the description happening at the GitHub or Cirrus level if you just re-run. It's super annoying.

**Comment by ditman** [comment]
> You have to re-push after updating the PR text; there's some sort of cache of the description happening at the GitHub or Cirrus level if you just re-run. It's super annoying.

Argh, I added an unnecessary CHANGELOG entry then. Luckily we'll be able to remove it when we undo the code. Thanks for the info!

**Pull request merged**
