### PR TITLE
[ci] Switch analyze tests to LUCI

### PR DESCRIPTION
**Pull request by stuartmorgan**
Fully enables the new analyze and downgraded-analyze tests in LUCI, and removes the Cirrus versions.

Part of https://github.com/flutter/flutter/issues/114373

### CODE REVIEW

**Review by keyonghan — APPROVED** [review]
LGTM

**Comment by stuartmorgan** [comment]
Hm, looks like this is too slow on the full-repo run. Can we easily see what the gating factor is here (CPU? Memory?)

**Comment by keyonghan** [comment]
> Hm, looks like this is too slow on the full-repo run. Can we easily see what the gating factor is here (CPU? Memory?)

All linux VMs are configured the same way though. Couldn't tell why it's [slow](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8777671367463604433/+/u/Run_package_tests/analyze/stdout) compared to a [passing build.](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8777672455701043377/+/u/Run_package_tests/analyze/stdout)

Btw: 
https://github.com/flutter/flutter/issues/125577 to collect os/cpu info for packages targets.
https://github.com/flutter/flutter/issues/129291 to route all Linux targets to VMs.

**Comment by stuartmorgan** [comment]
Oh, looking again I don't think it's slow, I think it hung. Maybe a server-side resolver problem or network issue?

Comparing the relative time offsets in the logging, the one that didn't finish and the one that did both got through shared_preferences by about minute 9, but then the failing one just never got any further than than (at least, not that was logged).

**Comment by stuartmorgan** [comment]
Looks like the Cirrus `repo_checks` failure is also a timeout, which is more evidence for some kind of external bad event.

**Pull request merged**
