### PR TITLE
[image_picker]: Disabled compressing video during picking on iOS

### PR DESCRIPTION
**Pull request by nikolaydymura**
When selecting video file from Gallery it tooks long time to compressing video

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by EgorEko** [comment]
Oh! This is so cool. This is what I need. Thanks to the developers.

**Comment by jaxybayevdanial** [comment]
We really need uncompressed video, great improvement!

**Comment by Ramazan1511** [comment]
Useful feature, great improvement

**Comment by SivtsovaT** [comment]
It's perfect, I was waiting for this, thank you! 😊

**Comment by Dr33Deathman** [comment]
Good feeature! Thank you. I was waiting this for a long time!!  👍👍👍

**Comment by OlenaFedna** [comment]
Looks great! Thank you.

**Comment by galFerenc1991** [comment]
I like it! Useful feature, thanks for developers!

**Comment by nataliiazabiiaka** [comment]
Its perfect! I was waiting this!!!

**Comment by Bogdan778** [comment]
I was waiting this too. Must for release

**Comment by Serbayev** [comment]
exactly what I needed in my project

**Comment by shyraqshy** [comment]
Great one, need this !

**Comment by stuartmorgan** [comment]
Brigading a PR is not constructive. Please do not comment here unless you have specific review comments.

**Comment by stuartmorgan** [comment]
In the future, please do not delete the checklist that is in the PR template; it is there for a reason. This PR is missing required elements described in the checklist (I’ve restored it to the PR description), which need to be addressed before it moves forward with review.

I am marking the PR as a Draft. Please review the checklist, updating the PR as appropriate, and when that’s complete please feel free to mark the PR as ready for review.

**Comment by nikolaydymura** [comment]
@stuartmorgan Thanks for the explanation, I've closed the PR and left changes in my fork.

**Pull request closed without merging**
