### PR TITLE
[pigeon] fix int bug

### PR DESCRIPTION
**Pull request by tarrinneal**
fixes https://github.com/flutter/flutter/issues/155512

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
LGTM.

Did you audit the other generators to make sure none of them have this same bug in the other direction (for calling a `FlutterApi` with an int, and no custom types anywhere)?

**Comment by tarrinneal** [comment]
> LGTM.
> 
> Did you audit the other generators to make sure none of them have this same bug in the other direction (for calling a `FlutterApi` with an int, and no custom types anywhere)?

Yeah, the change to handling ints is only a dart change so the logic doesn't exist in the other generators

**Comment by EchoEllet** [comment]
It seem that [this part](https://github.com/flutter/packages/pull/7725/files#diff-0586de4d30521ddc85ce6b0c29ea52bbb41577fbd7f2cf4eb4d19e48d3f525cfR346-R347) causing Flutter analysis failure:

```dart
class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value); // Unnecessary duplication of receiver. Try using a cascade to avoid the duplication
    } else {
      super.writeValue(buffer, value);
    }
  }
```

Should be updated to:

```dart
buffer..putUint8(4)
      ..putInt64(value);
```

This version was released as a minor version, pub always uses the latest available minor version and it causes [analysis failure](https://github.com/singerdmx/flutter-quill/actions/runs/11103808226/job/30846555011), maybe this should be changed to satisfy Dart analysis or ignore all lint rules in the top of the file, or maybe provide the option to?

Since at the moment, we can't directly depend on ` dart run pigeon --input ./pigeons/messages.dart`, instead we have to use our own command which runs `dart fix` for that generated file to fix them all.

**Comment by stuartmorgan** [comment]
> Should be updated to

This PR has already landed, and cannot be updated. The place to report issues with code that has already landed is the issue tracker.

> it causes [analysis failure](https://github.com/singerdmx/flutter-quill/actions/runs/11103808226/job/30846555011) [...] maybe this should be changed to satisfy Dart analysis

That depends on your project's analysis settings; Dart has many optional analysis options, some of which are contradictory. We do not (and *cannot*, due to the contradictory settings) guarantee that all Pigeon-generated code will pass every possible set of analysis options.

>  or ignore all lint rules in the top of the file, or maybe provide the option to?

You can put arbitrary text in the `copyrightHeader` file, including ignore options.

**Comment by EchoEllet** [comment]
> That depends on your project's analysis settings; Dart has many optional analysis options, some of which are contradictory. We do not (and _cannot_, due to the contradictory settings) guarantee that all Pigeon-generated code will pass every possible set of analysis options.

You're right, it seems that I have missed that the [cascade_invocations](https://dart.dev/tools/linter-rules/cascade_invocations) is not part of the recommended nor the core lints provided by `lints` and `flutter_lints`.

So an issue specific to a project and not part of this repo.

Thank you for clarifying.

**Pull request merged**
