### PR TITLE
[google_maps_flutter_web] Web changes to support heatmaps

### PR DESCRIPTION
**Pull request by Rexios80**
Sequel to:
- https://github.com/flutter/packages/pull/7312

Prequel to:
- https://github.com/flutter/packages/pull/3257

### CODE REVIEW

**Comment by Rexios80** [comment]
@ditman @stuartmorgan Time for round two!

**Review by stuartmorgan — APPROVED** [review]
LGTM!

**Comment by Rexios80** [comment]
@ditman any comments?

**Comment by stuartmorgan** [comment]
@Rexios80 since @ditman already reviewed the web bits in the main PR and there are no significant changes here as compared to that, it's fine to land the sub-PR with just my approval in this case.

**Pull request merged**
