### PR TITLE
[pigeon] Updated documentation in run_tests.sh and turned the ios unit tests back on.

### PR DESCRIPTION
**Pull request by gaaclarke**

### CODE REVIEW

**Comment by jmagman** [comment]
When I run this locally I get:
```
/var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.je1w2uMX/Pigeon.java:5: error: package io.flutter.plugin.common does not exist
import io.flutter.plugin.common.BasicMessageChannel;
                               ^
/var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.je1w2uMX/Pigeon.java:6: error: package io.flutter.plugin.common does not exist
import io.flutter.plugin.common.BinaryMessenger;
                               ^
/var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.je1w2uMX/Pigeon.java:7: error: package io.flutter.plugin.common does not exist
import io.flutter.plugin.common.StandardMessageCodec;
                               ^
/var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.je1w2uMX/Pigeon.java:36: error: cannot find symbol
    private final BinaryMessenger binaryMessenger;
                  ^
  symbol:   class BinaryMessenger
  location: class Api
/var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.je1w2uMX/Pigeon.java:37: error: cannot find symbol
    public Api(BinaryMessenger argBinaryMessenger){
               ^
  symbol:   class BinaryMessenger
  location: class Api
/var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.je1w2uMX/Pigeon.java:44: error: cannot find symbol
      BasicMessageChannel<Object> channel =
      ^
  symbol:   class BasicMessageChannel
  location: class Api
/var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.je1w2uMX/Pigeon.java:45: error: cannot find symbol
          new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.Api.setValue", new StandardMessageCodec());
              ^
  symbol:   class BasicMessageChannel
  location: class Api
/var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.je1w2uMX/Pigeon.java:45: error: cannot find symbol
          new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.Api.setValue", new StandardMessageCodec());
                                                                                            ^
  symbol:   class StandardMessageCodec
  location: class Api
8 errors
javac /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.je1w2uMX/Pigeon.java failed
```

**Comment by gaaclarke** [comment]
@jmagman looks like it can't find your `flutter.jar`.  Maybe because you haven't build for android, it doesn't know how to find it?

Try running `bash -x ./run_tests.sh`  Look for the `-classpath` flag to `javac`.

**Comment by gaaclarke** [comment]
@jmagman You can try running `flutter precache --android` before running the tests.  If that works I can add it to the script.

**Comment by gaaclarke** [comment]
@jmagman I talked to jonah and I'm pretty sure that should work, i added the precache for ios too.  Go ahead and give that a shot.

**Comment by jmagman** [comment]
Pigeon.java errors are gone, analysis errors left:
```
Analyzing /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart...
  error • Target of URI doesn't exist: 'package:flutter/services.dart'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:5:8 • uri_does_not_exist
  error • Undefined class 'BasicMessageChannel'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:80:13 • undefined_class
  error • Const variables must be initialized with a constant value. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:80:52 • const_initialized_with_non_constant_value
  error • The method 'BasicMessageChannel' isn't defined for the type 'FlutterSearchApi'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:80:52 • undefined_method
  error • The method 'StandardMessageCodec' isn't defined for the type 'FlutterSearchApi'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:81:57 • undefined_method
  error • Undefined class 'BasicMessageChannel'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:96:11 • undefined_class
  error • The method 'BasicMessageChannel' isn't defined for the type 'NestedApi'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:96:50 • undefined_method
  error • Const variables must be initialized with a constant value. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:96:50 • const_initialized_with_non_constant_value
  error • The method 'StandardMessageCodec' isn't defined for the type 'NestedApi'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:97:48 • undefined_method
  error • The method 'PlatformException' isn't defined for the type 'NestedApi'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:101:13 • undefined_method
  error • The method 'PlatformException' isn't defined for the type 'NestedApi'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:107:13 • undefined_method
  error • Undefined class 'BasicMessageChannel'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:121:13 • undefined_class
  error • Const variables must be initialized with a constant value. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:121:52 • const_initialized_with_non_constant_value
  error • The method 'BasicMessageChannel' isn't defined for the type 'TestNestedApi'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:121:52 • undefined_method
  error • The method 'StandardMessageCodec' isn't defined for the type 'TestNestedApi'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:122:50 • undefined_method
  error • Undefined class 'BasicMessageChannel'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:137:11 • undefined_class
  error • The method 'BasicMessageChannel' isn't defined for the type 'Api'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:137:50 • undefined_method
  error • Const variables must be initialized with a constant value. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:137:50 • const_initialized_with_non_constant_value
  error • The method 'StandardMessageCodec' isn't defined for the type 'Api'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:138:42 • undefined_method
  error • The method 'PlatformException' isn't defined for the type 'Api'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:142:13 • undefined_method
  error • The method 'PlatformException' isn't defined for the type 'Api'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:148:13 • undefined_method
  error • Undefined class 'BasicMessageChannel'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:162:13 • undefined_class
  error • Const variables must be initialized with a constant value. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:162:52 • const_initialized_with_non_constant_value
  error • The method 'BasicMessageChannel' isn't defined for the type 'TestHostApi'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:162:52 • undefined_method
  error • The method 'StandardMessageCodec' isn't defined for the type 'TestHostApi'. • /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/pigeon.VCqAAhSx/pigeon.dart:163:44 • undefined_method
```

I'm starting with a clean cloned directory, running `pub get` and then `./run_tests.sh`

**Comment by gaaclarke** [comment]
@jmagman I added those extra missing setup commands that you found.  I also spawned https://github.com/flutter/flutter/issues/64202 to help chase down any remaining issues.  Thanks for the help.

**Comment by gaaclarke** [comment]
@jmagman Did your e2e tests work?  Mine didn't on a fresh clone.  That thing is so finicky for iOS.

**Comment by jmagman** [comment]
> @jmagman Did your e2e tests work? Mine didn't on a fresh clone. That thing is so finicky for iOS.

Honestly I killed it after the analyzer passed.  I can try again.

**Comment by jmagman** [comment]
@gaaclarke I get:
```
    error: /Users/m/Projects/packages/packages/pigeon/e2e_tests/test_objc/ios/Flutter/Debug.xcconfig: unable to open file (in target "Runner" in project "Runner") (in target 'Runner' from project 'Runner')
    error: /Users/m/Projects/packages/packages/pigeon/e2e_tests/test_objc/ios/Flutter/Debug.xcconfig: unable to open file (in target "Runner" in project "Runner") (in target 'Runner' from project 'Runner')
    error: /Users/m/Projects/packages/packages/pigeon/e2e_tests/test_objc/ios/Flutter/Debug.xcconfig: unable to open file (in target "Runner" in project "Runner") (in target 'Runner' from project 'Runner')
```
It looks like the following `pigeon/e2e_tests` files aren't checked into this repo:
```
  ios/Flutter/Debug.xcconfig (created)
  ios/Flutter/Release.xcconfig (created)
  ios/Flutter/AppFrameworkInfo.plist (created)
```
are

**Comment by gaaclarke** [comment]
@jmagman, that worked!  I figured out the xcconfig files, but was missing AppFrameworkInfo.plist.  I've never seen that before, the errors were not helpful.  Thanks!

**Pull request merged**
