### PR TITLE
Added some documentation for gauge.

### PR DESCRIPTION
**Pull request by gaaclarke**
relevant issues: https://github.com/flutter/flutter/issues/45435

### CODE REVIEW

**Comment by gaaclarke** [comment]
@liyuqian looks like CI is broken, analyze step.  You seen this before?

**Comment by liyuqian** [comment]
@gaaclarke : I haven't seen this before. Does rebasing with the latest master help? @goderbauer and @dnfield may have more knowledge about the presubmit tests in this repo.

**Comment by dnfield** [comment]
I'm not sure why this is happening, but it appears unrelated to this package.  I haven't touched CI here in a while.

**Comment by goderbauer** [comment]
Can we also remove https://github.com/flutter/packages/blob/master/packages/gauge/analysis_options.yaml now? (and the exception in https://github.com/flutter/packages/blob/master/.cirrus.yml#L15)?

**Comment by gaaclarke** [comment]
> Can we also remove https://github.com/flutter/packages/blob/master/packages/gauge/analysis_options.yaml now? (and the exception in https://github.com/flutter/packages/blob/master/.cirrus.yml#L15)?

I tried but I started getting errors outside of this code:
```
  info - Document all public members at lib/commands/base.dart:10:14 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:11:14 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:12:14 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:13:14 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:14:14 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:15:14 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:17:14 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:19:16 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:20:3 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:36:21 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:56:23 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:96:16 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:101:8 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:108:12 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:110:14 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:112:14 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:115:16 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:116:3 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:127:14 - (public_member_api_docs)
  info - Document all public members at lib/commands/base.dart:129:14 - (public_member_api_docs)
  info - Document all public members at lib/commands/ioscpugpu.dart:9:7 - (public_member_api_docs)
  info - Document all public members at lib/commands/ioscpugpu.dart:10:3 - (public_member_api_docs)
  info - Document all public members at lib/commands/ioscpugpu/new.dart:13:3 - (public_member_api_docs)
  info - Document all public members at lib/parser.dart:12:3 - (public_member_api_docs)
  info - Document all public members at lib/parser.dart:14:16 - (public_member_api_docs)
  info - Document all public members at lib/parser.dart:15:16 - (public_member_api_docs)
  info - Document all public members at lib/parser.dart:22:8 - (public_member_api_docs)
  info - Document all public members at lib/parser.dart:39:14 - (public_member_api_docs)
  info - Document all public members at lib/parser.dart:40:16 - (public_member_api_docs)

29 issues found; analyzed 9 source files in 6.9s.
```

**Pull request merged**
