### PR TITLE
Update configuration.dart

### PR DESCRIPTION
**Pull request by elihaialgoaitech**
Added check for empty route

Fixed an error while the route is empty in some reason

### CODE REVIEW

**Comment by elihaialgoaitech** [comment]
Fixes that https://github.com/flutter/flutter/issues/132044#issuecomment-1704021378

**Review by chunhtai — COMMENTED** [review]
Hi @elihaialgoaitech ,

Thanks for your contribution. However, in order to land this pr, there are some additional works
1. A test to ensure the fix will not be regress
2. A Changelog entry indicate this change
3. A revision version bump.

**Comment by chunhtai** [comment]
Hi @elihaialgoaitech are you still plan to work on this pr?

**Comment by chunhtai** [comment]
Closing this pr for now, feel free to reopen if you have time to work on it in the future

**Pull request closed without merging**
