### PR TITLE
[metrics_center] Add new non-numeric keys in the Google Benchmark JSON format

### PR DESCRIPTION
**Pull request by gw280**
Updated versions of the Google Benchmark library have added new fields to the JSON schema. We need to add the non-numeric fields to the `_kNonNumericalValueSubResults` list so that the parser can correctly parse the data.

https://github.com/flutter/flutter/issues/93345

I'm not sure what testing needs to be done for this.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by gw280** [comment]
The updated keys are here: https://github.com/google/benchmark/blob/main/src/json_reporter.cc#L228

**Comment by dnfield** [comment]
I'd say we're testing this in the engine repo once it lands, but maybe @stuartmorgan has a better idea.

**Comment by dnfield** [comment]
CI isn't happy.

**Comment by gw280** [comment]
I updated the tests.

At first I thought `_kNonNumericalValueSubResults` only needs to list the keys that aren't numbers, but looking at the test it actually needs to list everything that isn't the actual benchmark result (because `iterations` was already in that list). I've added all the rest of the keys now, and updated the example JSON based on a real run on my machine.

This ensures that the `MetricPoint` list that is generated only contains points for the actual benchmarking result (`cpu_time`, `real_time`, `cpu_coefficient` and `real_coefficient`).

**Review by dnfield — APPROVED** [review]
LGTM

**Pull request merged**
