### PR TITLE
[pigeon] Kotlin/Java method overloading for the `setUp` method

### PR DESCRIPTION
**Pull request by RobinCombrink**
This PR allows Java code to call the Kotlin `setUp` method without the optional `messageChannelSuffix` parameter.

I am not 100% sure how the tests should be adjusted to accurately test the Java/Kotlin interop - any advice there would be welcome?

### Affected issues:
flutter/flutter#149027

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by tarrinneal** [comment]
@stuartmorgan any thoughts on whether we want to start doing java <-> kotlin and objc <-> swift testing at all? Or would a generator unit test be good enough here?

**Comment by stuartmorgan** [comment]
A unit test is fine with me. As long as we're maintaining both generators for the platforms (making cross-calling a relatively niche use case) I think the overhead of maintaining two more sets of tests is probably not worthwhile.

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Review by tarrinneal — APPROVED** [review]
Thanks for throwing this together!

**Pull request merged**
