### PR TITLE
[webview_flutter_android] Adds support to accept third party cookies

### PR DESCRIPTION
**Pull request by bparrishMines**
Adds support to accept third party cookies with https://developer.android.com/reference/android/webkit/CookieManager#setAcceptThirdPartyCookies(android.webkit.WebView,%20boolean)

This is being added as an Android-specific method since iOS doesn't seem to have an equivalent. See
https://developer.apple.com/forums/thread/701327
https://developer.apple.com/forums/thread/16847

This also updates the `CookieManager` wrapping since the `HostApi` needs to access the `InstanceManager` for this method.

Fixes https://github.com/flutter/flutter/issues/125569

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by bparrishMines** [comment]
cc @jjliu15 FYI

**Comment by stuartmorgan** [comment]
> This is being added as an Android-specific method since iOS doesn't seem to have an equivalent.

Support just landed for it last month in WebKit: https://bugs.webkit.org/show_bug.cgi?id=249508 (I happened to see this go by because the very old https://bugs.webkit.org/show_bug.cgi?id=140205 was filed by my team back when I was in Chromium-land, and was dup'd against it just recently.) So we should probably go ahead and design this as a cross-platform feature and just indicate that it's not supported on iOS yet. I'm not sure how iOS branching and cutoffs work; presumably this will be in this year's iOS release if we're lucky, or next year's if not.

**Comment by stuartmorgan** [comment]
Actually, hm. It looks like they maybe only added Allow and Deny at the WKWebView level, and it's not clear to me if Allow includes third-party cookies. I guess we should do this now, and revisit a cross-platform API if/when we have something final on iOS to look at.

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Comment by jjliu15** [comment]
cc @malandr2

**Comment by tariqzarif** [comment]
How do you fix this error. been a month finding the solution. "Stripe.js requires 'allow-same-origin' if sandboxed." and Uncaught SecurityError: Failed to read the 'cookie' property from 'Document': Cookies are disabled inside 'data:' URLs.", source: https://js.stripe.com/v3/. Problem is related to webview and I can provide the code too

**Comment by tariqzarif** [comment]
import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import '../constants.dart';

String checkoutSuccessUrl = '$BACKEND_HOST/pay-out-mobile?result=success';
String checkoutFailureUrl = '$BACKEND_HOST/pay-out-mobile?result=failure';
String stripePublicKey =
    'pk_test_51MPPCnGWLLYsWJjCn0ju2BWyRqRz6g0VQPIadKpFZMPi0TvpvDn3qMXyTKJQrPN4JkY3epO8dEEqtV9PTvpEzO8H00NvCXVwqj';

const stripeHtmlPageScaffold = '''
  <!DOCTYPE html>
  <html>
    <script src="https://js.stripe.com/v3/"></script>
    <style>
      body, html {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #loader {
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center; 
      }
    </style>
    <head><title>Stripe checkout</title></head>
    <body>
      <div id="loader">
        <span>Please wait...</span>
      </div>
    </body>
  </html>
''';

class CheckoutPage extends StatefulWidget {
  final String sessionId;

  const CheckoutPage({Key? key, required this.sessionId}) : super(key: key);

  @override
  _CheckoutPageState createState() => _CheckoutPageState();
}

class _CheckoutPageState extends State<CheckoutPage> {
  //  late WebViewController _controller ;
  late WebViewController _controller = WebViewController()
    ..setJavaScriptMode(JavaScriptMode.unrestricted)
    // ..setBackgroundColor(const Color(0x00000000))
    ..setNavigationDelegate(
      NavigationDelegate(
        onProgress: (int progress) {
          // Update loading bar.
          print('progress==>$progress');
        },
        onPageStarted: (String url) {
          print('url==>$url');
        },
        onPageFinished: (String url) {
          print('url==>$url');
          if (url == initialUrl) {
            _redirectToStripe();
          }
        },
        onWebResourceError: (WebResourceError error) {
          debugPrint('''
  Page resource error:
  code: ${error.errorCode}
  description: ${error.description}
  errorType: ${error.errorType}
  isForMainFrame: ${error.isForMainFrame}
          ''');
        },
        onNavigationRequest: (NavigationRequest request) {
          if (request.url.startsWith(checkoutSuccessUrl)) {
            Navigator.of(context).pop('success'); // <-- Handle success case
          } else if (request.url.startsWith(checkoutFailureUrl)) {
            Navigator.of(context).pop('cancel'); // <-- Handle cancel case
          }
          return NavigationDecision.navigate;
        },
      ),
    )
    ..loadRequest(Uri.parse(initialUrl));

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: Container(
        padding: EdgeInsets.only(top: 30),
        child:
        //
            WebViewWidget(
              controller: _controller,
            )
        
      ),
    );
  }

  String get initialUrl =>
      'data:text/html;base64,${base64Encode(Utf8Encoder().convert(stripeHtmlPageScaffold))}';

  void _redirectToStripe() {
    final redirectToCheckoutJs = '''
      var stripe = Stripe(\'$stripePublicKey\');
      stripe.redirectToCheckout({
        sessionId: '${widget.sessionId}'
      }).then(function (result) {
        result.error.message = 'Error'
      });
    ''';
      _controller.runJavaScript(
          redirectToCheckoutJs); //<--- call the JS function on controller
   

  }
}

**Pull request merged**
