### PR TITLE
[flutter_template_images] Add support for new template and shared platform files

### PR DESCRIPTION
**Pull request by brianegan**
There is a proposal to add a new Flutter app template to the flutter CLI. This new app template lives alongside the current counter template, it does not replace it. The team has made the following request on the related PR: 

  > We need to find a way to not duplicate the existing platform files. We occasionally have to update these, and having 2 copies of everything is going to increase the chances that we accidentally get out of sync somewhere.

This PR moves assets common to both apps into an `app_shared` directory and introduces a new `list_detail_app` folder to support images unique to the new template.

Related Issues:

  - https://github.com/flutter/flutter/pull/76519
  - https://github.com/flutter/flutter/pull/76519

## Pre-launch Checklist

- [X] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated `CHANGELOG.md` to add a description of the change.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the `#hackers-new` channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
If you want to use this in flutter/flutter it needs to be published, so this must include a version change and corresponding CHANGELOG entry.

**Review by goderbauer — COMMENTED** [review]
Can you bump the version in the pubspec and update the changelog? Thanks!

**Comment by goderbauer** [comment]
Oh, sorry, didn't see that @stuartmorgan already said that above... :)

**Comment by brianegan** [comment]
Thanks so much, @stuartmorgan and @goderbauer :) I've updated the PR to include a CHANGELOG and pubspec.

**Review by stuartmorgan — APPROVED** [review]
LGTM assuming the flutter/flutter PR is approved with this structure. I'd like to wait on landing this until that's approved just in case there are any changes.

**Comment by brianegan** [comment]
Thanks @stuartmorgan! I have gotten a ["LGTM" on the Template](https://github.com/flutter/flutter/pull/76519#pullrequestreview-608053899). Is that enough to land this PR and publish it up? 

I'm in a bit of a catch-22 here, haha. In order for the all my tests to pass on the Flutter PR, this new version needs to be deployed to pub :)

**Comment by stuartmorgan** [comment]
Yes, that's all it needed. I realized just as I was about to land it that the version bump needs to be to 2.0 since it's a breaking change though (moving existing files), so I've changed that. Once the tests re-run and are green I'll land and publish.

**Comment by stuartmorgan** [comment]
Published 2.0.0

**Comment by brianegan** [comment]
Excellent, thanks for your help @stuartmorgan :)

**Pull request merged**
