### PR TITLE
[webview_flutter] Fix typo in JavascriptChannel docs

### PR DESCRIPTION
**Pull request by Frank3K**
I came across a spelling error on the [JavascriptChannel documentation page](https://pub.dev/documentation/webview_flutter_upload/latest/webview_flutter/JavascriptChannel-class.html).

image

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by bparrishMines** [comment]
@Frank3K It looks like you are missing some of the check boxes mentioned in the PR description. More specifically, this is missing the version bump mentioned in https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates

**Comment by Frank3K** [comment]
> @Frank3K It looks like you are missing some of the check boxes mentioned in the PR description. More specifically, this is missing the version bump mentioned in https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates

I assumed fixing a typo does not require a version bump. Could it fall under this category?

> Any change that needs to be published in order to take effect must update the version in pubspec.yaml. There are very few exceptions:
> ...
> * **Non-code changes** that we make to future-proof development in some way, but don't directly benefit clients. 

What do you think? If you agree, can you add the `override: no versioning needed` label?

**Comment by bparrishMines** [comment]
> What do you think? If you agree, can you add the `override: no versioning needed` label?

Further down in the [FAQ](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#faq) has this line: 

> Do I need to update the version if I'm just changing comments? If the comment is intended for clients of the package (a /// comment on anything exported by the package), then yes, since what developers using the package will see in their IDE will come from the published version.

This doesn't change code, but it affects the documentation seen by clients.

**Comment by Frank3K** [comment]
> > What do you think? If you agree, can you add the `override: no versioning needed` label?
> 
> Further down in the [FAQ](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#faq) has this line:
> 
> > Do I need to update the version if I'm just changing comments? If the comment is intended for clients of the package (a /// comment on anything exported by the package), then yes, since what developers using the package will see in their IDE will come from the published version.
> 
> This doesn't change code, but it affects the documentation seen by clients.

Thanks for pointing that out. I searched for _documentation_, but should also have searched for _comments_. I think the PR is good now (bar the failing _Linux repo_checks_).

**Comment by bparrishMines** [comment]
@Frank3K I actually just realized that the picture you showed is from `webview_flutter_upload`. We don't manage that package. 

On top of that, you are changing the file `packages/webview_flutter/webview_flutter_platform_interface/lib/src/legacy/types/javascript_channel.dart`, which is no longer maintained and can't be accessed from the `webview_flutter` package. Closing since we don't plan on landing this.

**Pull request closed without merging**
