### PR TITLE
[google_maps_flutter] Fix incorrect comment: Change "marker" to "polyline"

### PR DESCRIPTION
**Pull request by dhiaCodes**
*This pull request fixes an incorrect comment in the `polyline.dart` file.*

fixes [#155379
](https://github.com/flutter/flutter/issues/155379)
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Thanks for the contribution!

> * [x]  I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning), or this PR is [exempt from version changes](https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version).
> * [x]  I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style), or this PR is [exempt from CHANGELOG changes](https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog).

Which of the linked exemption reasons are you requesting an exemption under?

**Comment by dhiaCodes** [comment]
> Thanks for the contribution!
> 
> > * [x]   I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning), or this PR is [exempt from version changes](https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version).
> > * [x]   I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style), or this PR is [exempt from CHANGELOG changes](https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog).
> 
> Which of the linked exemption reasons are you requesting an exemption under?

Thanks for your feedback! I believe this PR is a small tweak, so I thought it might be exempt from versioning. If that's incorrect, I'd be happy to uncheck the box and make the necessary changes—I'm still learning the process.

**Comment by stuartmorgan** [comment]
> I believe this PR is a small tweak, so I thought it might be exempt from versioning.

The reasons a PR would be exempt are those listed in the linked document.

**Comment by dhiaCodes** [comment]
> > I believe this PR is a small tweak, so I thought it might be exempt from versioning.
> 
> The reasons a PR would be exempt are those listed in the linked document.

I have updated the version inside `pubspec.yaml` to 2.9.3
Would that work?

**Comment by dhiaCodes** [comment]
@stuartmorgan, can we merge this PR?

**Comment by stuartmorgan** [comment]
@dhiaCodes In order to land, the PR needs passing all CI checks, and then to be reviewed. Please see the Details section of the `Linux repo_checks` and update the PR accordingly; once it's passing CI I can review it.

**Comment by dhiaCodes** [comment]
@stuartmorgan I get it. Now it has passed all CI checks and is ready for your review. thank you

**Review by stuartmorgan — APPROVED** [review]
LGTM, thanks!

@tarrinneal Could you do the secondary approval on this one?

**Review by tarrinneal — APPROVED** [review]
Thanks for putting this together!

**Pull request merged**
