### PR TITLE
[ci] Disable maps tests in Android emulator

### PR DESCRIPTION
**Pull request by stuartmorgan**
When the emulator tests for Android were brought up, `google_maps_fluter_android` was excluded due to flake. We're also seeing high flake from `google_maps_flutter` on Android, so disabling that as well.

We continue to have coverage of these tests via FTL, so it's only the relatively new emulator version that is being disabled here.

See https://github.com/flutter/flutter/issues/130986

### CODE REVIEW

**Comment by johnmccutchan** [comment]
I'd rather not disable these tests. How can I reproduce these failures so I can address them?

**Comment by stuartmorgan** [comment]
> I'd rather not disable these tests. How can I reproduce these failures so I can address them?

See https://github.com/flutter/flutter/issues/130986#issuecomment-1735947097

Keeping these extremely flaky tests enabled is really not an option. They should have been disabled much earlier.

**Comment by stuartmorgan** [comment]
test-exempt: is a test

**Review by bparrishMines — APPROVED** [review]
LGTM since the tests are still running on FTL

**Comment by stuartmorgan** [comment]
Landing so that the roller can actually keep up over the weekend, rather than getting behind due to heavy flake.

**Pull request merged**
