### PR TITLE
Optimized images and updated a url in readme.

### PR DESCRIPTION
**Pull request by phanirithvij**
Optimized all the images found in the repository. Done by [Imgbot](https://imgbot.net/)
And changed the url in [packages/palette_generator/Readme](packages/palette_generator/README.md) from [packages/palette_generator/example/README](packages/palette_generator/example/README.md) to [packages/palette_generator/example/lib/main.dart](packages/palette_generator/example/lib/main.dart)

### CODE REVIEW

**Comment by phanirithvij** [comment]
I signed it

**Comment by phanirithvij** [comment]
How can I make a bot agree? Will create an issue in the `googlebot` repo.

**Comment by gspencergoog** [comment]
It looks like ImgBot would need to agree to the CLA in order for the CLA bot to be happy with it.  Why did you want to optimize the images?

**Comment by phanirithvij** [comment]
That wasn't my intention actually. I wanted to change the readme. But the images that I optimized in my fork came along with it so added them as well. I didn't know that I'd have to sign a cla. I don't think imgbot can sign the cla. So, I'll revert those commits **or** close this PR and @gspencergoog can edit the readme if that change's valid.

**Comment by gspencergoog** [comment]
Just revert the images, and I'll commit the README.md change: it's fine.

**Comment by phanirithvij** [comment]
It says an unknown repository on the top. So I must've deleted my fork. I'll send another pull request with the changes.

**Comment by phanirithvij** [comment]
PR #45

**Pull request closed without merging**
