### PR TITLE
[google_maps_flutter] Restore the arm64 workaround

### PR DESCRIPTION
**Pull request by stuartmorgan**
Restores the workaround to exclude arm64 when building for simulator, which is still necessary for apps that support back to iOS 12.

Also removes all the example-app-level workarounds that manually excluded arm64 simulator, which were masking the failure in the first place, so that we don't accidentally break this again. The exception is the exclusions for the unit test targets, which need them in order to match the Flutter-tool-generated exclusion to the Runner, otherwise the unit tests can't build.

See https://github.com/flutter/flutter/issues/94491

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
test-exempt: removing the workarounds from the Xcode project is a test for the actual change

**Review by hellohuanlin — APPROVED** [review]

**Comment by jmagman** [comment]
```
 Error (Xcode): Building for iOS Simulator, but linking in object file built for iOS, file '/Volumes/Work/s/w/ir/x/w/packages/packages/google_maps_flutter/google_maps_flutter/example/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture arm64
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8758620211172029057/+/u/Run_package_tests/drive_examples/stdout

Is this because `google_maps_flutter/google_maps_flutter/example` is using the published 2.4.0 plugin with the `EXCLUDED_ARCH` missing?

**Comment by stuartmorgan** [comment]
Ah, right. That cleanup is the least important, so I'll just revert it, and make a note to do a separate PR for it later.

Looks like I'll need to keep some workarounds in the unit test target as well.

**Review by jmagman — APPROVED** [review]
Thanks for tracking all this down and remembering all the details I forgot. 🙂

**Comment by IttaiBarkai** [comment]
I am not sure if this is the correct place to post, so happy to delete this comment if necessary. Similar to one of the comments above, I had the same issue below: 

` Error (Xcode): Building for iOS Simulator, but linking in object file built for iOS, file ` 

Since your latest commit, this issue has now been resolved (much appreciated), but for some reason the app crashes every time I do a hot restart. Just wondering if anyone else is experiencing this issue now or if it's just me.

**Comment by jmagman** [comment]
> Since your latest commit, this issue has now been resolved (much appreciated), but for some reason the app crashes every time I do a hot restart. Just wondering if anyone else is experiencing this issue now or if it's just me.

@IttaiBarkai can you file a new issue and completely fill out the template, including reproduction steps? https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml
Feel free to @ me in the issue.  Thanks!

**Comment by IttaiBarkai** [comment]
Hi @jmagman, no problem, I will try and do it this weekend if I have time. Thanks for the quick response.

**Pull request merged**
