### PR TITLE
[webview_flutter_web] Migrate integration tests to package:web.

### PR DESCRIPTION
**Pull request by ditman**
This PR: 

* Fixes a DOM timing issue that was preventing the _Legacy_ Widget from building.
* Makes the `integration_tests` for the package less flaky, now that they seem to be timing out unexpectedly in CI.

## Issues

* Fixes https://github.com/flutter/flutter/issues/151693
* Should prevent this flake from happening: [bad](https://ci.chromium.org/ui/p/flutter/builders/try/Linux_web%20web_platform_tests_shard_3%20stable/8987/overview) / [good](https://ci.chromium.org/ui/p/flutter/builders/try/Linux_web%20web_platform_tests_shard_3%20stable/8991/overview) (`Linux_web web_platform_tests_shard_3 stable`)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by ditman** [comment]
Now the non-legacy test should actually do *something* in CI. The legacy one is only left as a manual check. No coverage is lost, since neither of the tests were actually verifying anything earlier (the bug that is being fixed here should have been caught by a functional legacy test!)

**Comment by ditman** [comment]
Nah, this is still flaking :/

* https://ci.chromium.org/ui/p/flutter/builders/try/Linux_web%20web_platform_tests_shard_1%20master/9401/overview

**Comment by ditman** [comment]
```console
$ flutter clean; run_integration_test.sh | ts -s
00:00:03 
00:00:03 ============================================================
00:00:03 || Running for packages/webview_flutter/webview_flutter_web
00:00:03 ============================================================
00:00:03 
00:00:03 Starting chromedriver on port 4444
00:00:03 Running command: "flutter drive -d web-server --web-port=7357 --browser-name=chrome --web-renderer=canvaskit --driver test_driver/integration_test.dart --target integration_test/webview_flutter_test.dart" in /work/flutter/packages/packages/webview_flutter/webview_flutter_web/example
00:00:03 Resolving dependencies...
00:00:04 Downloading packages...
00:00:04   collection 1.18.0 (1.19.0 available)
00:00:04   leak_tracker 10.0.4 (10.0.5 available)
00:00:04   leak_tracker_flutter_testing 3.0.3 (3.0.5 available)
00:00:04   material_color_utilities 0.8.0 (0.12.0 available)
00:00:04   meta 1.12.0 (1.15.0 available)
00:00:04   platform 3.1.4 (3.1.5 available)
00:00:04   string_scanner 1.2.0 (1.3.0 available)
00:00:04   test_api 0.7.0 (0.7.3 available)
00:00:04   vm_service 14.2.1 (14.2.4 available)
00:00:04 Got dependencies!
00:00:04 9 packages have newer versions incompatible with dependency constraints.
00:00:04 Try `flutter pub outdated` for more information.
00:00:04 Launching integration_test/webview_flutter_test.dart on Web Server in debug mode...
00:00:31 Waiting for connection from debug service on Web Server...         26.3s
00:00:31 integration_test/webview_flutter_test.dart is being served at http://localhost:7357
00:00:31 The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
00:00:38 All tests passed.
00:00:38 Application finished.
00:00:39 Stopping chromedriver
00:00:39 
00:00:39 
00:00:39 ------------------------------------------------------------
00:00:39 Run overview:
00:00:39   packages/webview_flutter/webview_flutter_web - ran
00:00:39 
00:00:39 Ran for 1 package(s)
00:00:39 
00:00:39 
00:00:39 No issues found!
```

vs [CI](https://github.com/flutter/packages/pull/7115/checks?check_run_id=27399709222). 🤷

**Comment by ditman** [comment]
The problem seems to stem from some DDC modules not being ready when the app starts. It doesn't always reproduce, but it can be seen when the app fails to start with `--no-headless` flag set:

Screenshot 2024-07-12 at 8 33 49 PM

(I've seen it also fail with a very similar trace, but complaining about `IntegrationTestWidgetsFlutterBinding` not being defined... Smells like a race condition!) 

I wonder if testing in `--profile` mode would yield better results (in general)

**Comment by ditman** [comment]
> I wonder if testing in `--profile` mode would yield better results (in general)

It probably does, but we can't use that mode, because **assertions are not thrown there**, and we have some tests [that check that assertions are thrown](https://ci.chromium.org/ui/p/flutter/builders/try/Linux_web%20web_platform_tests_shard_2%20master/9393/overview).

**Comment by ditman** [comment]
Try by inlining the bootstrap file.

**Comment by ditman** [comment]
(Updating `master` seems to have been beneficial!)

**Comment by ditman** [comment]
I'm going to try next to revert the inlining of the bootstrap, it might not be needed.

**Comment by Rexios80** [comment]
> > I wonder if testing in `--profile` mode would yield better results (in general)
> 
> It probably does, but we can't use that mode, because **`assert`s don't work in `--profile`**, and we have some tests [that check that assertions are thrown](https://ci.chromium.org/ui/p/flutter/builders/try/Linux_web%20web_platform_tests_shard_2%20master/9393/overview).

@ditman Related to asserts with WASM integration tests: https://github.com/flutter/flutter/issues/151426

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Comment by ditman** [comment]
Turns out the flakiness in `--canvaskit` mode is now fixed in `master`, but the fix won't be backported to the current `stable` (v3.22).

@stuartmorgan should I roll back the `--canvaskit` mode in tests until the fix lands in the next stable? Until then, web tests in `stable` are extra flaky. WDYT?

**Comment by stuartmorgan** [comment]
> Turns out the flakiness in `--canvaskit` mode is now fixed in `master`, but the fix won't be backported to the current `stable` (v3.22).
> 
> @stuartmorgan should I roll back the `--canvaskit` mode in tests until the fix lands in the next stable? Until then, web tests in `stable` are extra flaky. WDYT?

This is looking really bad on stable so far; we should make CI run canvaskit only on `master` ASAP.

**Comment by ditman** [comment]
Working on this right now.

**Comment by ditman** [comment]
> This is looking really bad on stable so far; we should make CI run canvaskit only on master ASAP.

@stuartmorgan PR posted https://github.com/flutter/packages/pull/7146

**Pull request merged**
