### PR TITLE
[in_app_purchase] Replaced deprecated ProrationMode with ReplacementMode

### PR DESCRIPTION
**Pull request by vongrad**
Replace deprecated `ProrationMode` in Android's billing client with `ReplacementMode`. 

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/128957

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by vongrad** [comment]
I had to update the versions in both `in_app_purchase` and `in_app_purchase_android` pubspec.yaml files, but now the in_app_purchase cannot resolve the in_app_purchase_android ^0.3.3 dependency when running your pipeline checks. What would be the right approach?

**Review by bparrishMines — COMMENTED** [review]
@vongrad It looks like you are changing the name of the `ProrationMode` class. This is a breaking change for the Android implementation, so it would need a major version bump (e.g. 0.4.0) if that is the goal of the PR. 

Also, you are bumping the android implementation in `packages/in_app_purchase/in_app_purchase/pubspec.yaml`, but that version doesn't exist on `pub.dev` until this PR would land.

But overall I think we should actually deprecate `ProrationMode` on the Dart side and add `ReplacementMode` as a separate enum. And add it as a separate parameter in `launchBillingFlow`. This would give users time to transition without breaking them immediately. 

Since this looks like it is only changing an Android specific method, you shouldn't need to change `in_app_purchase` in this PR.

**Comment by vongrad** [comment]
@bparrishMines I agree that its probably better to introduce a new enum for `ReplacementMode` instead of placing it in as a replacement. 
In this case, I suppose I should leave the version of `in_app_purchase` untouched and only increase the version of `in_app_purchase_android`. What would you prefer to have as a version number?

**Comment by bparrishMines** [comment]
Since this is adding a new feature, this should bump `in_app_purchase_android` to `0.3.3`.

**Comment by vongrad** [comment]
Sure thing, I will submit a new PR during next week once I get some free time.

**Comment by vongrad** [comment]
I made a new PR with the mentioned changes and in general re-worked it a bit. Please see here: https://github.com/flutter/packages/pull/6515

**Pull request closed without merging**
