### PR TITLE
[go_router] Export GoRouteInformationParser, GoRouteInformationProvider, and GoRouterDelegate

### PR DESCRIPTION
**Pull request by ValentinVignal**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

This PR makes `go_router.dart` export
- `src/go_route_information_parser.dart`
- `src/go_route_information_provider.dart`
- `src/go_router_delegate.dart`

*List which issues are fixed by this PR. You must list at least one issue.*

Should fix https://github.com/flutter/flutter/issues/106863

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by ValentinVignal** [comment]
I believe this PR is a test exempt candidate? If no, what would be the correct way to test it?

**Comment by Hixie** [comment]
The best way to test this is to find the tests that depend on the newly exported files, and change the imports in those tests to import the whole package instead of the individual files.

**Comment by ValentinVignal** [comment]
Thanks for the answer @Hixie , This commit https://github.com/flutter/packages/pull/2298/commits/47843a0f290f117c5debf02a84818eb01d6b4e8a already removes the import of the individual files.

**Comment by chunhtai** [comment]
we should probably wait until we have agreement on https://github.com/flutter/flutter/issues/107757

**Comment by chunhtai** [comment]
I am closing this PR. I understand this three classes should have been public since the beginning, but there are some parameters and properties we should clean up from these class before exposing them so that we don't have to make a breaking change in the future

**Pull request closed without merging**
