### PR TITLE
[google_maps_flutter_android] Android changes to support heatmaps

### PR DESCRIPTION
**Pull request by Rexios80**
Sequel to:
- https://github.com/flutter/packages/pull/7312

Prequel to:
- https://github.com/flutter/packages/pull/3257

### CODE REVIEW

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
The platform implementation PRs need to wait for the platform interface PR to land and be published before they are reviewable, since the state of the PR right now isn't what will land.

**Comment by Rexios80** [comment]
@reidbaker
I get this error with `@Config(minSdk = Build.VERSION_CODES.LOLLIPOP)` but not with `@Config(sdk = Build.VERSION_CODES.P)`

<details>

<summary>Error</summary>

```console
Failed to load /Users/rexios/.m2/repository/org/robolectric/android-all-instrumented/13-robolectric-9030017-i4/android-all-instrumented-13-robolectric-9030017-i4.jar
java.lang.OutOfMemoryError: Failed to load /Users/rexios/.m2/repository/org/robolectric/android-all-instrumented/13-robolectric-9030017-i4/android-all-instrumented-13-robolectric-9030017-i4.jar
	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:275)
	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:293)
	at android.content.res.ApkAssets.nativeLoad(ApkAssets.java)
	at android.content.res.ApkAssets.__constructor__(ApkAssets.java:296)
	at android.content.res.ApkAssets.<init>(ApkAssets.java)
	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:145)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at org.robolectric.shadows.ShadowArscApkAssets9$_ApkAssets_$$Reflector395.loadFromPath(Unknown Source)
	at org.robolectric.shadows.ShadowArscApkAssets9.lambda$loadFromPath$3(ShadowArscApkAssets9.java:239)
	at org.robolectric.shadows.ShadowArscApkAssets9.getFromCacheOrLoad(ShadowArscApkAssets9.java:178)
	at org.robolectric.shadows.ShadowArscApkAssets9.loadFromPath(ShadowArscApkAssets9.java:237)
	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java)
	at android.content.res.AssetManager.createSystemAssetsInZygoteLocked(AssetManager.java:249)
	at android.content.res.AssetManager.getSystem(AssetManager.java:276)
	at org.robolectric.shadows.ShadowResources.getSystem(ShadowResources.java:83)
	at android.content.res.Resources.getSystem(Resources.java)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.onCreate(RoboMonitoringInstrumentation.java:74)
	at org.robolectric.android.internal.AndroidTestEnvironment.createInstrumentation(AndroidTestEnvironment.java:582)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:205)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:340)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:281)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.robolectric.res.android.FileMap.getDataPtr(FileMap.java:413)
	at org.robolectric.res.android.Asset$_CompressedAsset.getBuffer(Asset.java:1338)
	at org.robolectric.res.android.CppApkAssets.LoadImpl_measured(CppApkAssets.java:259)
	at org.robolectric.res.android.CppApkAssets.lambda$LoadImpl$0(CppApkAssets.java:206)
	at org.robolectric.res.android.CppApkAssets$$Lambda$441/0x00000008005bec50.get(Unknown Source)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.res.android.CppApkAssets.LoadImpl(CppApkAssets.java:203)
	at org.robolectric.res.android.CppApkAssets.Load(CppApkAssets.java:117)
	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:272)
	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:293)
	at java.base/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(Unknown Source)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000802225800.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00000008019a6000.reinvoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00000008019a6400.guard(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00000008019a6800.linkToCallSite(LambdaForm$MH)
	at android.content.res.ApkAssets.nativeLoad(ApkAssets.java)
	at android.content.res.ApkAssets.$$robo$$android_content_res_ApkAssets$__constructor__(ApkAssets.java:296)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x000000080199e400.invokeSpecial(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00000008019a0400.guardWithCatch(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00000008019a2400.reinvoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00000008019a2800.guard(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00000008019a2c00.linkToCallSite(LambdaForm$MH)
	at android.content.res.ApkAssets.<init>(ApkAssets.java)
	at android.content.res.ApkAssets.$$robo$$android_content_res_ApkAssets$loadFromPath(ApkAssets.java:145)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.robolectric.shadows.ShadowArscApkAssets9$_ApkAssets_$$Reflector395.loadFromPath(Unknown Source)
	at org.robolectric.shadows.ShadowArscApkAssets9.lambda$loadFromPath$3(ShadowArscApkAssets9.java:239)
	at org.robolectric.shadows.ShadowArscApkAssets9$$Lambda$803/0x000000080221bce8.call(Unknown Source)
	at org.robolectric.shadows.ShadowArscApkAssets9.getFromCacheOrLoad(ShadowArscApkAssets9.java:178)
```
</details>

**Comment by reidbaker** [comment]
Feel free to leave as targeting p. We will figure it out after your pr lands

**Review by reidbaker — APPROVED** [review]

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Pull request merged**
