### PR TITLE
flutter_migrate package - Master

### PR DESCRIPTION
**Pull request by GaryQian**
Master PR for flutter_migrate standalone command.

### CODE REVIEW

**Comment by GaryQian** [comment]
cc @christopherfujino @zanderso @stuartmorgan @goderbauer Just for reference, this is the latest WIP draft of standalone migration tool. I'll begin to try to land this in sections again once I have it at parity to the flutter_tools verison.

**Comment by GaryQian** [comment]
Base boilderplate landed in https://github.com/flutter/packages/pull/2694

**Comment by reidbaker** [comment]
Do you have any interest in landing this cl? It looks good. If not I understand just let me know.

**Comment by stuartmorgan** [comment]
Closing for now; I've left a comment in the most relevant issue so this is findable in the future.

**Pull request closed without merging**
