### PR TITLE
remove unnecessary _updateActiveAnimations()

### PR DESCRIPTION
**Pull request by ThanhDat-Vo**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @ThanhDat-Vo welcome. This PR does not have tests, but I am also not sure what issue you are trying to fix. Can you provide a link to an issue that this is fixing? 
The cla will also need to be addressed (see the comment from the bot). Thanks!

**Comment by ThanhDat-Vo** [comment]
@Piinks 
Hi, 
I did not create a pr yet.
The issue I want to fix is about the TreeView.
In Android, when user tap on the Node to collapse, it works.
In Web, when user tap on the Node to collapse, it collapses and then expands immediately.

This is screen recording.

https://github.com/user-attachments/assets/3d99235a-c16d-4360-98a9-f5bdc5989bc7


P/s 1: sorry if I make any mistake in my English
P/s 2: this my first contribution, therefore I have to wait for s.o to review by CLA

**Comment by ThanhDat-Vo** [comment]
@Piinks 
one more thing, even this PR is to fix the collapse behavior of the Node of TreeView. The difference behavior between the same Flutter application Android and Web could be a hidden issue. I believe you should bring this issue with core Flutter team.

**Comment by stuartmorgan** [comment]
Thanks for the contribution! You’ve checked boxes in the PR checklist above that are not reflected in this PR, so I’m assuming this is a work in progress and am marking it as a Draft. Please review the checklist, updating the PR as appropriate, and when the checklist reflects the state of the PR as posted please feel free to mark it as ready for review.

**Comment by stuartmorgan** [comment]
Since this is marked as a draft and hasn't been updated in several months I'm going to close it to clean out our review queue. Please don't hesitate to submit a new PR if you decide to revisit this. Thanks!

**Comment by ThanhDat-Vo** [comment]
@stuartmorgan Thank you! 
I thought I had already closed this PR because I discovered another issue with the changes I made in it.

**Pull request closed without merging**
