### PR TITLE
[pigeon] Split CI and developer test scripts

### PR DESCRIPTION
**Pull request by stuartmorgan**
This creates a new `test.dart` script for developers to run tests locally, separate from the `run_tests.dart` entrypoint whose no-argument behavior is constrained by our CI requirements since it's what the repo tooling's `custom-tests` runs.

Most of the logic is extracted to a new shared file, which is used by `run_tests.dart` and `test.dart`.
- `run_tests.dart` is now solely intended for CI. It distributes the tests among the host platforms so that everything is run, but not all on the same host, and not more than once. It follows the same logic we use for most of our CI in that it runs everything it can on Linux, and only the things that need to be run on Windows and macOS are run there. It also adds validation that we are running every test suite on at least one host unless explicitly opted out, so that we can't accidentally forget to run things in CI (and so that we can easily see in one place what we aren't running in CI).
- `test.dart` is for developers to run locally. It still has the arguments for selecting specific tests, but the default behavior is to run every test that can run on that host, so local runs get the maximum possible coverage. This includes integration tests that we aren't currently set up to be able to run in CI. This means developers don't need to remember what is and isn't run locally by default.

Linux `custom-tests` is moved to the heavy workload machine configuration in the Cirrus configuration since the Android build is OOMing on the light workload configuration.

Fixes https://github.com/flutter/flutter/issues/115393

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
`test_suites.dart` is code moved from `run_tests.dart` with essentially no changes; the individual commits let you see the minor adjustments.

**Comment by stuartmorgan** [comment]
Looks like the light-workload machine config doesn't have enough memory for the Android builds; trying it with the heavy-workload config.

**Review by tarrinneal — APPROVED** [review]
Seems solid to me.

**Comment by stuartmorgan** [comment]
The merge here was incorrect, I'll fix it later.

**Pull request merged**
