### PR TITLE
[all] Update UIViewControllerBasedStatusBarAppearance to true

### PR DESCRIPTION
**Pull request by cyanglaz**
Now that we support UIViewControllerBasedStatusBar by default (after engine roll: https://github.com/flutter/flutter/commit/c7167765d74c1980c9ba750c5750ae27817ad630), we should make this value to be true.

Part of https://github.com/flutter/flutter/issues/128969

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by hellohuanlin** [comment]
can you explain more about this flag and the future plan (if any)?

**Comment by stuartmorgan** [comment]
What effect does this have prior to your PR landing (e.g., if someone runs the examples on `stable`)?

**Comment by cyanglaz** [comment]
> What effect does this have prior to your PR landing (e.g., if someone runs the examples on `stable`)?

Actually, the status bar hide feature won't work on stable. I think we can still migrate now in this repository because I don't see any tests are using this feature. It is easy to forget if we wait until the feature lands on stable.

**Comment by cyanglaz** [comment]
> can you explain more about this flag and the future plan (if any)?

The flag is to enable ViewControllerBased status bar styling API. The UIApplication based APIs are deprecated in iOS 9. The default value of this flag is true, meaning if info.plist does not have this flag, the value is true. 

To disable ViewControllerBased status bar styling, the app needs to explicitly declare this flag in info.plist and set it to false.

Flutter app explicitly declared the flag to be false and used deprecated UIApplication APIs due to historical reasons that I'm not entirely sure but I think it is safe to flip the flag now. 

There are no future plans. The project is done once the flag is flipped. The only thing I'd say is that we need to monitor to see if there are new related issues filed.

**Comment by hellohuanlin** [comment]
does a new xcode project contain this flag? should we just remove this flag?

**Comment by cyanglaz** [comment]
> does a new xcode project contain this flag? should we just remove this flag?

New project does not have this flag. Yeah, removing is the same as making it to true.

**Review by stuartmorgan — APPROVED** [review]
LGTM, although it seems like removing it might be preferable so we're not keeping cruft in the plist forever. Either way is fine though.

**Comment by cyanglaz** [comment]
> LGTM, although it seems like removing it might be preferable so we're not keeping cruft in the plist forever. Either way is fine though.

Updated to removing the flags

**Review by hellohuanlin — APPROVED** [review]

**Comment by stuartmorgan** [comment]
Overriding changelog: this change isn't interesting to plugin clients.

**Pull request merged**
