### PR TITLE
[google_maps_flutter] Update example android configuration

### PR DESCRIPTION
**Pull request by Rexios80**
Updates the example android configuration to fix the following issue:

Fixes https://github.com/flutter/flutter/issues/122137

I think this change should be exempt from a version bump since it only affects example configuration, but let me know if I should bump it anyways.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by Rexios80** [comment]
Oh yeah I should probably explain that the only manual change here is bumping the gradle version to 7.4 in `gradle-wrapper.properties` so that the project could sync. The rest of the changes were done by the AGP Upgrade Assistant

**Comment by CaseyHillers** [comment]
test-exempt: This is a version bump that is verified in CI

**Comment by stuartmorgan** [comment]
> The rest of the changes were done by the AGP Upgrade Assistant

@reidbaker Do you have an opinion on these automatic changes? I'm not aware of us ever having made these kind of other changes when updating AGP; if they are useful/necessary we should probably do them in general, but if not this is going to make these files different from the versions in all of the other examples.

**Comment by Rexios80** [comment]
If you don't like the changes besides version bumps, I can revert them.

**Review by reidbaker — APPROVED** [review]

**Comment by reidbaker** [comment]
Please hold merging until/unless @stuartmorgan approves.

**Comment by stuartmorgan** [comment]
> I am not opposed to these automatic changes. Until and Unless I feel like our decisions are better than the ones proposed by the tool I would like to defer to the tool.

Works for me. Ideally we should do this everywhere then; having the lint options be in different formats in different packages is not ideal.

**Comment by stuartmorgan** [comment]
Exempt from changelog change: the manifest files that are triggering the failure are uninteresting to clients.

**Pull request merged**
