### PR TITLE
Add example app

### PR DESCRIPTION
**Pull request by jemishavasoya**
added simple example app for it that demonstrates

[css_color] Add example app #136217
#136217

added Example app

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [X] I signed the CLA.
- [X] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [X] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
> * [x]  All existing and new tests are passing.

Since a large number of CI checks are failing, I'm assuming this is a work in progress, and marking it as a Draft accordingly, Please mark it as ready for review once it's passing.

**Comment by stuartmorgan** [comment]
> [css_color] Add example app #136217
> #136217

The referenced issue is about a completely different package.

What's the goal of adding this example app? It's not clear to me what this is accomplishing that the README doesn't (and/or than a simple example.md wouldn't do). We don't need integration tests, for instance.

**Comment by goderbauer** [comment]
(triage): @jemishavasoya Do you still have plans to get back to this PR in the near future to address the feedback given above?

**Comment by stuartmorgan** [comment]
Since this is marked as a draft and hasn't been updated in several months I'm going to close it to clean out our review queue. Please don't hesitate to submit a new PR if you decide to revisit this. Thanks!

**Pull request closed without merging**
