### PR TITLE
[Re-land] Bump legacy all_packages project AGP version to 7.0.0, Gradle version to 7.0.2

### PR DESCRIPTION
**Pull request by camsim99**
Re-lands https://github.com/flutter/packages/pull/6591.

The only difference between that PR and this one is that this PR bumps the required Flutter version of Android facing packages to the latest Flutter stable version (3.22) that weren't doing so already. That is because the stable version includes the warning about using older versions of Android dependencies.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by camsim99** [comment]
`stable` seems to be resolving as newer than the `master` branch causing the failures, so this is blocked until that is resolved.

**Comment by camsim99** [comment]
@stuartmorgan we are good to override version changes here right?

**Comment by stuartmorgan** [comment]
Yes, that's correct!

**Comment by stuartmorgan** [comment]
Version override: This only changes minimum SDK version, which is [a documented exception](https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version)

**Review by reidbaker — APPROVED** [review]

**Pull request merged**
