### PR TITLE
[CrossFile] Fix class name in readme

### PR DESCRIPTION
**Pull request by ueman**
This PR fixes the class name in CrossFiles readme.
It says you have to use a class `CrossFile` which doesn't even exist in the package. It must be `XFile`.

There's no issue which mentions this, but I just wondered why it doesn't work when copying from the example.

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the `#hackers-new` channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
Thanks, LGTM!

You'll need to merge master into the PR so that the CI tests pass; there was an infrastructure issue that required a fix in the repository. Once that's done, I can get this landed and published.

**Comment by ueman** [comment]
> Thanks, LGTM!
> 
> You'll need to merge master into the PR so that the CI tests pass; there was an infrastructure issue that required a fix in the repository. Once that's done, I can get this landed and published.

Sure, thanks for the heads up. I'll update it tomorrow morning as it's already late over here.

**Comment by ueman** [comment]
> You'll need to merge master into the PR so that the CI tests pass

Done

**Review by stuartmorgan — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
