### PR TITLE
[camera][android]:Catches IllegalArgumentException exception for CameraCaptureSession setRepeatingRequest call

### PR DESCRIPTION
**Pull request by arc-yong**
Catches IllegalArgumentException exception for CameraCaptureSession setRepeatingRequest call.

Fixes https://github.com/flutter/flutter/issues/117945

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

### CODE REVIEW

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
[This comment](https://github.com/flutter/packages/pull/5199#pullrequestreview-1696985009) from the previous iteration remains unadressed.

**Comment by stuartmorgan** [comment]
> Catches IllegalArgumentException exception for CameraCaptureSession setRepeatingRequest call.

This PR needs an explanation of why catching an illegal argument is the correct behavior. That would require strong justification since generally an illegal argument is a programming error, and the solution is to not call the function with the illegal argument, rather than to simply ignore the exception.

> Fixes [flutter/flutter#117945](https://github.com/flutter/flutter/issues/117945)

This issue is already closed. Please file an issue with a clear description and reproduction steps.

**Comment by arc-yong** [comment]
> [This comment](https://github.com/flutter/packages/pull/5199#pullrequestreview-1696985009) from the previous iteration remains unadressed.

This issue can only be reproduced sometimes. No tests can be provided. Can it be test-exempt?

**Comment by stuartmorgan** [comment]
> No tests can be provided.

Why can't this code be unit tested using a mock capture session?

**Comment by reidbaker** [comment]
> > No tests can be provided.
> 
> Why can't this code be unit tested using a mock capture session?

To get a test exemption you can follow the process here https://github.com/flutter/flutter/wiki/Tree-hygiene#tests. I will say I do think this code requires a test and will not get an exemption.

**Comment by stuartmorgan** [comment]
Are you still planning on updating this PR to add tests per the review comments above?

**Comment by gmackall** [comment]
Thanks for your contribution! Since I haven't seen a reply, I'm going to reluctantly close this pull request for now, but if you get time to address the comments, we'd be more than happy to take a look at a new patch. If you do send a new patch, it would be very useful to reference this one in the description in order to help reviewers see the previous context.

**Pull request closed without merging**
