### PR TITLE
[flutter_markdown] Ignore leading space for p and li

### PR DESCRIPTION
**Pull request by TarekkMA**
Leading spaces in a paragraph and in list items should be ignored as per
https://github.github.com/gfm/#example-192
https://github.github.com/gfm/#example-236

Please let me know if I should change anything

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
> * [ ]  I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning), or this PR is [exempt from version changes](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates).
> * [ ]  I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style).

These steps will need to be done before this can land.

**Review by domesticmouse — APPROVED** [review]

**Comment by TarekkMA** [comment]
Thank you, I have updated changelog and version.

**Comment by TarekkMA** [comment]
I assume that this PR needs to wait for #522 to land.

**Review by stuartmorgan — APPROVED** [review]
LGTM. Could you merge in the latest main so that the CI will pass?

**Comment by TarekkMA** [comment]
Still, there are issues with CI

```
ERROR: Package validation found the following potential issue:
* 5 checked in files are ignored by a `.gitignore`.
  Previous versions of Pub would include those in the published package.
  
  Consider adjusting your `.gitignore` files to not ignore those files, and if you do not wish to
  publish these files use `.pubignore`. See also dart.dev/go/pubignore
  
  Files that are checked in while gitignored:
  
  example/linux/flutter/generated_plugin_registrant.cc
  example/linux/flutter/generated_plugin_registrant.h
  example/macos/Flutter/GeneratedPluginRegistrant.swift
  example/windows/flutter/generated_plugin_registrant.cc
  example/windows/flutter/generated_plugin_registrant.h
```

**Comment by stuartmorgan** [comment]
> Still, there are issues with CI

This is now fixed if you merge in the latest `main`.

**Comment by TarekkMA** [comment]
Passed CI 🥳

**Pull request merged**
