### PR TITLE
[pigeon] update deprecated command in README of the example

### PR DESCRIPTION
**Pull request by EchoEllet**
*Replace a deprecated command in the instructions of using `pigeon`.*

Running `flutter pub run pigeon --input path/to/input.dart` will output the following at the start of the output:

```console
Deprecated. Use `dart run` instead.
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by tarrinneal** [comment]
Good catch! This will need an update to the changelog, I think a `NEXT` entry would be fine for this. @stuartmorgan is that the case for this? And tagged for second review once that is done.

**Comment by EchoEllet** [comment]
Thank you for reviewing the change, IMO `CHANGELOG.md` is for the end user or the developer who will use the package, such minor changes is not in the list of interest for most users, and I think `CHANGELOG.md` should be different from Git log or the commit history. Such projects have many of those changes and having them all in a `CHANGELOG.md` will result in users will not read them even if it has critical changes, features, deprecation, or breaking changes. User expect that docs up to to date with related repositories. See [Keep a Changelog
](https://keepachangelog.com/en/1.1.0/) as an example format for `CHANGELOG.md`.

Though I can add it if needed.

**Comment by tarrinneal** [comment]
> Thank you for reviewing the change, IMO `CHANGELOG.md` is for the end user or the developer who will use the package, such minor changes are not in the list of interest for most users, and I think `CHANGELOG.md` should be different from Git log or the commit history. Such projects have many of those changes and having them all in a `CHANGELOG.md` will result in users not reading them even if it has critical changes, features, deprecation, or breaking changes. User expect that docs up to to date with related repositories. See [Keep a Changelog ](https://keepachangelog.com/en/1.1.0/) as an example format for `CHANGELOG.md`.
> 
> Though I can add it if needed.

The issue is that README changes don't get published without a new version, I could wrap this change up in another pr I'm making to avoid the issue, or @stuartmorgan could grant an exception for this case.

**Comment by EchoEllet** [comment]
if they can grant an exception I would wait, otherwise, If you prefer to have this change documented in `CHANGELOG.md`, it should be minimal to update `CHANGELOG.md`

**Comment by stuartmorgan** [comment]
This README isn't published, because pub.dev prioritizes `example/lib/main.dart` (unfortunately, in this case, since that's empty) over `example/README.txt`, which is why it's not failing the version check. It's fine to CHANGELOG-exempt this; the only reason changes to unpublished example files aren't auto-exempted from the CHANGELOG check is because sometimes changes to example files are relevant to people understanding the package, such as adding a missing permission to the example app that a real app would need, so we add a human check.

**Comment by stuartmorgan** [comment]
CHANGELOG override: minor update to instructions for local running.

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Review by tarrinneal — APPROVED** [review]
Well, there ya go! Thanks for putting this together!

**Pull request merged**
