### PR TITLE
[pigeon] add null handling to FlutterApi.setup()

### PR DESCRIPTION
**Pull request by matejdro**
Fixes https://github.com/flutter/flutter/issues/66994

### CODE REVIEW

**Comment by gaaclarke** [comment]
This PR would really benefit from unit tests that run on the generated java code.  I haven't found the time to land that quite yet.  Let me see if I can get that going again.

**Comment by matejdro** [comment]
You meant generated flutter code? I can take a stab at creating some tests if you want.

**Comment by gaaclarke** [comment]
@matejdro sorry, yes.  Today I'm going to implement null safety for the Dart code, it's an impediment for another team so I might get a chance to fix it then.

**Comment by gaaclarke** [comment]
I integrated this change over to my PR that implemented null safety.  Sorry I didn't get around the giving this the consideration it deserved earlier.  I cc'd you on the PR please give it a look.

**Pull request closed without merging**
