### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mit-mit**
Swap word sequence to make it even clearer that this contains `package:lints`

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

If you want this change released to pub.dev as soon as possible: Can you bump the version number and add an entry to the changelog?

**Comment by mit-mit** [comment]
Updated, PTAL

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by mit-mit** [comment]
@goderbauer merged; can you please publish?

**Comment by goderbauer** [comment]
Done. It's live at https://pub.dev/packages/flutter_lints.

**Pull request merged**
