### PR TITLE
[flutter_markdown] Import from flutter/flutter_markdown

### PR DESCRIPTION
**Pull request by stuartmorgan**
Imports the flutter/flutter_markdown repository as a package, to
consolidate repositories.

Part of flutter/flutter#74757

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@domesticmouse The last two commits in the chain do need actual review:
- The second to last updates the metadata to point here, and the version to allow releasing that.
- The last fixes (or in some cases, suppresses) the >1k analyzer warnings the project had with this repo's settings :(

**Review by domesticmouse — APPROVED** [review]
That last commit is a doozy

**Comment by domesticmouse** [comment]
@googlebot I consent.

**Comment by domesticmouse** [comment]
@stuartmorgan I'm guessing we are going to have to override CLAbot for this PR, as I doubt we can get consent on this PR from all the authors of the package. On the flipside, all the authors already consented to having their PRs merged into the `flutter/flutter_markdown` repo.

**Comment by stuartmorgan** [comment]
> @stuartmorgan I'm guessing we are going to have to override CLAbot for this PR, as I doubt we can get consent on this PR from all the authors of the package. On the flipside, all the authors already consented to having their PRs merged into the `flutter/flutter_markdown` repo.

Yes, that's what I've been doing for all the imports I've been doing. But I learned that every push resets the override so I was waiting for approval first in case the last commit needed any changes.

**Comment by stuartmorgan** [comment]
Overriding CLA check, as this is a direct import from a repository that itself enforced the CLA check.

**Pull request merged**
