### PR TITLE
[ci] Manual roll Flutter to c246ecd (84 revisions) + fixes

### PR DESCRIPTION
**Pull request by ditman**
Updates the flutter master version and adds fixes for broken stuff.

* [flutter_markdown] Updates a test image used as a golden file.
* ~~[google_maps_flutter_android]~~ Flaky test/fixed OOB.

## Issues

* Completes https://github.com/flutter/packages/pull/6861

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by ditman** [comment]
(Brought from #6861)

OK, the [android crash](https://github.com/flutter/packages/pull/6861/checks?check_run_id=25761018241) seems to be different/more explicit this time:

```
     FATAL EXCEPTION: GL-Map
Process: io.flutter.plugins.googlemapsexample, PID: 19653
java.lang.IllegalStateException: Trying to call onSurfaceCreated with no current context
	at m.fvx.l(:com.google.android.gms.policy_maps_core_dynamite@241110203@241110201042.615149234.615149234:10)
	at m.ezu.run(:com.google.android.gms.policy_maps_core_dynamite@241110203@241110201042.615149234.615149234:816)
```

This has taken me to the following public buganizer:

* https://b.corp.google.com/issues/339141097

Maybe we can mitigate by doing this:

* https://developers.google.com/maps/documentation/android-sdk/renderer#opt-out ?

(/cc @reidbaker)

**Comment by reidbaker** [comment]
> (Brought from #6861)
> 
> OK, the [android crash](https://github.com/flutter/packages/pull/6861/checks?check_run_id=25761018241) seems to be different/more explicit this time:
> 
> ```
>      FATAL EXCEPTION: GL-Map
> Process: io.flutter.plugins.googlemapsexample, PID: 19653
> java.lang.IllegalStateException: Trying to call onSurfaceCreated with no current context
> 	at m.fvx.l(:com.google.android.gms.policy_maps_core_dynamite@241110203@241110201042.615149234.615149234:10)
> 	at m.ezu.run(:com.google.android.gms.policy_maps_core_dynamite@241110203@241110201042.615149234.615149234:816)
> ```
> 
> This has taken me to the following public buganizer:
> 
> * https://b.corp.google.com/issues/339141097
> 
> Maybe we can mitigate by doing this:
> 
> * https://developers.google.com/maps/documentation/android-sdk/renderer#opt-out ?
> 
> (/cc @reidbaker)

You resolved this. Did you find a solution?

**Comment by ditman** [comment]
> You resolved this. Did you find a solution?

This resolved itself by bumping one more revision of Flutter, but the incoming changes don't seem related, so it's maybe an OOB fix from Google Maps or FTL (?) (or we got lucky in the flakiness lottery)

**Review by stuartmorgan — APPROVED** [review]

**Comment by ditman** [comment]
Will restart the roller now that this has landed!

**Comment by ditman** [comment]
The new roll is now showing the "Trying to call onSurfaceCreated with no current context" error... Ugh!

**Pull request merged**
