### PR TITLE
[flutter_lints] remove prefer_const_constructors, prefer_const_declarations, prefer_const_literals_to_create_immutables

### PR DESCRIPTION
**Pull request by devoncarew**
This PR removes three const lints from package:flutter_lints: `prefer_const_constructors`, `prefer_const_declarations`, and `prefer_const_literals_to_create_immutables`.

This PR does not rev the pubspec version. We want to stage this change out in coordination with package:lints; see https://github.com/dart-lang/lints/issues/209.

- https://github.com/dart-lang/lints/issues/205

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by devoncarew** [comment]
I _believe_ this PR is except from the changelog check, as we're intentionally staging this change in prep for a publish once the next major version of package:lints is available.

**Comment by devoncarew** [comment]
cc @Piinks and @stuartmorgan as likely reviewers (normally I would ask @goderbauer for a review here / he would author the PR).

**Review by stuartmorgan — APPROVED** [review]
LGTM mechanically; I haven't had any direct involvement with this package before so I have no idea what the policies on changes are, or how it's versioned.

(E.g., this is the correct way to land in this repo if you explicitly don't want to publish right now, so RSLGTM on landing an unpublished change in the first place, but LGTM on this given that goal.)

**Comment by devoncarew** [comment]
> (E.g., this is the correct way to land in this repo if you explicitly don't want to publish right now, so RSLGTM on landing an unpublished change in the first place, but LGTM on this given that goal.)

Great! Yup, this is the intent. We'll follow this up near-term with a rev to some deps and to a new major version, and plan to publish that.

**Pull request merged**
