### PR TITLE
Remove use_modular_headers! from Podfiles

### PR DESCRIPTION
**Pull request by loic-sharma**
⚠️ _This PR does not update packages' versions as it only affects unpublished parts of example apps and tests._

We added `use_modular_headers!` to our `Podfile`s as we originally planned to phase out `use_frameworks!` (see https://github.com/flutter/flutter/pull/42204). However, our plans have now changed and we are instead phasing out CocoaPods entirely in favor of Swift Package Manager.

CocoaPods's `use_frameworks!` and `use_modular_headers!` are two different overlapping options that should not be used together. This change removes the `use_modular_headers!` from example apps' `Podfile`s. This change does not affect packages themselves.

Part of https://github.com/flutter/flutter/issues/156259

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM once the test passes

```
  Expected: equals [
              ProcessCall:"which pod" in /packages,
              ProcessCall:"pod lib lint /packages/plugin1/ios/plugin1.podspec --configuration=Debug --skip-tests --use-modular-headers --use-libraries" in /packages,
              ProcessCall:"pod lib lint /packages/plugin1/ios/plugin1.podspec --configuration=Debug --skip-tests --use-modular-headers" in /packages
            ] ordered
    Actual: [
              ProcessCall:"which pod" in /packages,
              ProcessCall:"pod lib lint /packages/plugin1/ios/plugin1.podspec --configuration=Debug --skip-tests --use-libraries" in /packages,
              ProcessCall:"pod lib lint /packages/plugin1/ios/plugin1.podspec --configuration=Debug --skip-tests" in /packages
            ]
     Which: at location [1] is ProcessCall:<"pod lib lint /packages/plugin1/ios/plugin1.podspec --configuration=Debug --skip-tests --use-libraries" in /packages> instead of ProcessCall:<"pod lib lint /packages/plugin1/ios/plugin1.podspec --configuration=Debug --skip-tests --use-modular-headers --use-libraries" in /packages>
  
  package:matcher                             expect
  test/podspec_check_command_test.dart 144:7  main.<fn>.<fn>
```

**Comment by loic-sharma** [comment]
@stuartmorgan Ah, I misunderstood the content at the bottom of this section to mean "Add the override label once you've verified your change meets these conditions": https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version

I'll update this README to clarify this label should only be added if the CI check fails.

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by LouiseHsu — APPROVED** [review]
in_app_purchase, local_auth, and pointer_interceptor lgtm!

**Comment by loic-sharma** [comment]
This is now ready for review! The webview test failure that affected this change was also fixed by https://github.com/flutter/flutter/issues/157449

**Review by tarrinneal — APPROVED** [review]

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Pull request merged**
