### PR TITLE
[go_router] Remove assert so that ShellRoute allows child ShellRoute

### PR DESCRIPTION
**Pull request by johnpryan**
closes flutter/flutter#111981

See https://github.com/flutter/samples/pull/1437 for an example use-case.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by chunhtai — COMMENTED** [review]
code LGTM, would need a test though

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by loic-sharma — APPROVED** [review]

**Comment by johnpryan** [comment]
It looks like CI will fail until we fix https://github.com/flutter/flutter/issues/111909

**Comment by chunhtai** [comment]
This should unblock it https://github.com/flutter/packages/pull/2627

**Comment by chunhtai** [comment]
This should be able to merge now

**Pull request merged**
