### PR TITLE
[flutter_template_images] Add iOS app icon assets

### PR DESCRIPTION
**Pull request by RockerFlower**
Adds the the AppIcon and LaunchImage assets in the iOS app template while simultaneously updating them to meet Apple's icon guidelines as of iOS.

Ref:
https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons#specifications

Issue: flutter/flutter#106110

---
1. This is how the application icons are displayed in the settings list, obviously with black gaps in the four corners. This is because the mask Apple uses is not the standard rounded corners, but continuous corner.

    <details>

    icons in settings list

    </details>

2. This is a slow motion video of the app when it is opened from the home screen. The black color in the transition animation is caused by the transparent part of the icon.

    This animation takes the colors of the left, bottom and right sides of the icon and then spreads the colors in all three directions, but the current icon has rounded corners, so some of the colors are missing.

    <details>

    video when open

    </details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@jmagman Could you route this to a good reviewer for the icon changes?

**Review by jmagman — CHANGES_REQUESTED** [review]
Thanks for the contribution! 
This LGTM, but before we merge can you create a draft PR like https://github.com/flutter/flutter/pull/103739 to allow this to be adopted in the template?  Some tests will fail until this is published but if the tool PR is prepped then we can merge them close to the same time.

Can you also add some tests to prove the template is applying from this package (I know the referenced PR didn't have any tests).
Maybe around https://github.com/flutter/flutter/blob/0e0baa40c75fca3d119a821080038b45f1a3cf11/packages/flutter_tools/test/commands.shard/permeable/create_test.dart#L159

**Comment by RockerFlower** [comment]
Hi @jmagman 

I've updated the PR for the flutter repository. https://github.com/flutter/flutter/pull/106111

But I'm not sure how to prove that the template was applying from this package, so I haven't committed that part yet. I'm sorry for my lack of testing knowledge.

**Review by jmagman — APPROVED** [review]
> I've updated the PR for the flutter repository. [flutter/flutter#106111](https://github.com/flutter/flutter/pull/106111)

Oh great, I didn't see that!  This LGTM!  Once this is published you can rebase or merge that one to re-run the tests, and we can work on adding one to create_test.  Thanks for your contribution!

**Comment by jmagman** [comment]
Adding @stuartmorgan forgot I needed a second reviewer.

**Review by stuartmorgan — APPROVED** [review]

**Pull request merged**
