### PR TITLE
Remove dart:html dependency from url_launcher and shared_preferences.

### PR DESCRIPTION
**Pull request by joshualitt**

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@joshualitt Is this PR still something you were planning on completing?

**Comment by joshualitt** [comment]
@stuartmorgan , sorry,, I'd like to, but I haven't had time to return to it. Why?

**Comment by stuartmorgan** [comment]
We were just checking on old draft PRs during triage.

**Comment by joshualitt** [comment]
Ahh okay, I'm happy to abandon this one until we decide to return to it.

**Pull request closed without merging**
