### PR TITLE
[cupertino_icons] Import from flutter/cupertino_icons

### PR DESCRIPTION
**Pull request by stuartmorgan**
Imports the flutter/cupertino_icons repository as third_party/packages/cupertino_icons, as part of the repository consolidation.

Updates pubspec.yaml to point to this location, and bumps the version to allow publishing with the new metadata.

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@xster Where does this LICENSE come from? I looked at the history, but it's not clear to me from the commit messages why this has an unusual license rather than our standard one.

@Hixie Do we need to make a /third_party/packages/ directory to put this in instead?

**Comment by Hixie** [comment]
I guess so.

**Comment by xster** [comment]
The license is from https://github.com/framework7io/framework7-icons/blob/master/LICENSE copied as is in consultation with go/licensereview. 

I wouldn't put it in third_party since it's derivative work.

**Comment by Hixie** [comment]
anything that isn't the flutter licenses should be in third_party according to ospo

**Comment by stuartmorgan** [comment]
@xster What part of the package is covered by that license? Is it just the font, or the CSS file as well?

It's not clear to me if we should put the whole package in third_party, or have a third_party inside this package containing specific elements.

**Comment by xster** [comment]
Based on Ian's last point, the whole thing would be in a third_party folder

**Comment by stuartmorgan** [comment]
Sounds like I'll need to do a bunch of tooling work before we can merge this in then, because the tools assume that all packages in the repo live at `packages/*`

> The license is from https://github.com/framework7io/framework7-icons/blob/master/LICENSE copied as is in consultation with go/licensereview.

Were other models discussed? I'm wondering if we could restructure to have the package be a Flutter-licensed package with a third_party directory inside it containing the font, and then both licenses in the LICENSE file.

**Comment by xster** [comment]
go/licensereview just gave me one recommendation. Though I think you can bring up your proposal with them.

**Comment by stuartmorgan** [comment]
I just discovered that we already have a /third_party/packages/ (for bsdiff), so apparently that ship has already sailed. I'll need to see if the tooling is actually running the formatter, analyzer, tests, etc. for it, but if it's not we already need to fix it. So I'll go ahead with updating this PR to import there with the existing license structure.

**Review by xster — APPROVED** [review]

**Pull request merged**
