### PR TITLE
[go_router] docs: replace out dated initialRoute to initialLocation

### PR DESCRIPTION
**Pull request by unliar**
‌‌‌‌Updated the outdated configurations in [upgrading.md](https://github.com/flutter/packages/compare/main...unliar:packages:main#diff-0acd78ed04ed5af73daeb7496126c67bd4997e3068806c90d0385f323af20e7b).

### CODE REVIEW

**Comment by chunhtai** [comment]
can you bump the version and add changelog?

**Comment by unliar** [comment]
> can you bump the version and add changelog?

It has been supplemented.

**Comment by chunhtai** [comment]
Also we should use code-excerpt for code in md file as well. you can find some example by searching `<?code-excerpt`

**Comment by chunhtai** [comment]
edit: looks like the code excerpt support is only for readme.

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by hangyujin — APPROVED** [review]
LGTM

**Pull request merged**
