### PR TITLE
Update to the latest pigeon

### PR DESCRIPTION
**Pull request by natebosch**
The current version is incompatible with the latest `analyzer`, which is a blocker for getting the latest `mockito`, which is a blocker for getting the latest `test_api`, which is pinned by `flutter_test` and will be breaking in the next package roll.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
This is missing the updates required to release it: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates

**Review by gmackall — APPROVED** [review]
LGTM 

I've also actually tried running the sample app with the generated code from this version of pigeon already (because I was curious about the generated FlutterError exception in 9.1.0), and I didn't run into any issues.

**Comment by gmackall** [comment]
> > because I was curious about the generated FlutterError exception in 9.1.0
> 
> It doesn't do anything unless you use it. You can throw it instead of a generic `RuntimeException` in order to better control how the Dart-side `PlatformException` is populated from it, since the default `RuntimeException`->`PlatformException` translation isn't all that helpful in making good errors.

Yes, I didn't realize that the `Runtime`->`Platform` was the default approach and it felt weird enough to me that I was looking around at what else was possible, but I ended up just sticking with it.

**Comment by stuartmorgan** [comment]
If you're returning any errors in camerax, I definitely recommend updating to using `FlutterError` everywhere when you have a chance :)

**Pull request merged**
