### PR TITLE
Append $flutter/osx sdk property to existing platforms/targets relying on xcode

### PR DESCRIPTION
**Pull request by keyonghan**
Part of https://github.com/flutter/flutter/issues/127534

### CODE REVIEW

**Comment by keyonghan** [comment]
Friendly ping. This is a no-op for existing workflows.

**Review by ricardoamador — APPROVED** [review]
LGTM

**Comment by keyonghan** [comment]
Hi @stuartmorgan, what is the process to land PRs on red for packages repo? Seems the tree has been red the whole day. This PR is a no-op config change. Is it feasible to land manually, or do I need to wait for the tree green? If one has to wait, where can I track the status of the tree? Is there a bug tracking the tree fix?

**Review by godofredoc — APPROVED** [review]

**Comment by godofredoc** [comment]
> Hi @stuartmorgan, what is the process to land PRs on red for packages repo? Seems the tree has been red the whole day. This PR is a no-op config change. Is it feasible to land manually, or do I need to wait for the tree green? If one has to wait, where can I track the status of the tree? Is there a bug tracking the tree fix?

Tree is green!

**Comment by stuartmorgan** [comment]
> Hi @stuartmorgan, what is the process to land PRs on red for packages repo?

It's the same as the other repos: only do it if your PR is fixing the breakage.

> Seems the tree has been red the whole day.

We're having a fair amount of flake that we need to resolve, so it's red on and off a lot recently, but it definitely hasn't been red for the entire day. `autosubmit` is the best way to land things, as it'll generally land as soon as flake resolves.

> If one has to wait, where can I track the status of the tree? Is there a bug tracking the tree fix?

The ecosystem channel in Discord is the best place to ask about tree issues.

**Pull request merged**
