### PR TITLE
[flutter_markdown] [bug-fix] [#86138] Forcing a unique key for RichText widgets

### PR DESCRIPTION
**Pull request by abdlrhmanshehatamoussa**
**Issues Fixed:**
- https://github.com/flutter/flutter/issues/86138

**Fix Description**:
The resolution to this issue mentioned was to assign a unique key for each RichText widget while creating inline links.

Not having a unique key caused the widgets with the same text to share the same LinkHandler, consequently when the user changes the URL of a given link while keeping the Text, the Markdown widget is not updating the onTap callback with the new URL.

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Review by domesticmouse — CHANGES_REQUESTED** [review]
Please add types per [the failing CI run](https://github.com/flutter/packages/pull/415/checks?check_run_id=3128503064):

 ```
Running command: "dart analyze --fatal-infos" in /tmp/cirrus-ci-build/packages/flutter_markdown
Analyzing flutter_markdown...

   info - test/link_test.dart:111:23 - Specify type annotations. - always_specify_types

1 issue found.
```

**Comment by abdlrhmanshehatamoussa** [comment]
Hi,
Thanks for the feedback,
Yeah sure, will do this ASAP and update you.

**Comment by abdlrhmanshehatamoussa** [comment]
Hi @domesticmouse 

Changes applied, please check and let me know if anything else needed

Thanks in advance

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Thanks @abdlrhmanshehatamoussa, I'll land this once tests turn green

**Comment by domesticmouse** [comment]
Thanks!

**Comment by stuartmorgan** [comment]
> @stuartmorgan can you publish this package?

No need, we're living in the future now: https://github.com/flutter/packages/runs/3177386612

**Comment by domesticmouse** [comment]
Aww sweet! Thanks @stuartmorgan

**Pull request merged**
