### PR TITLE
chore: updating readme with available packages

### PR DESCRIPTION
**Pull request by jddeep**
chore: updating readme with available packages in the repository.

pub

### CODE REVIEW

**Comment by jddeep** [comment]
@googlebot I signed it!

**Comment by jddeep** [comment]
@gaaclarke @csells Could you please tell why the `test+format` test is failing with:
> Tests for the following packages are failing (see above):
>  * fuchsia_ctl

**Comment by gspencergoog** [comment]
This just looks like you are synced to a bad revision. Maybe try rebasing to the HEAD again. (Obviously your README change isn't causing this code to fail analysis.)

**Comment by jddeep** [comment]
Cool. So can we get this merged then? (Ignoring the false analysis test)

**Comment by gspencergoog** [comment]
Well, we typically don't do that: we have had cases where we were surprised by the effect of changing docs. However, I do think that it's especially unlikely here, given the context.

**Pull request merged**
