### PR TITLE
[camera] Reland android flip/change camera while recording

### PR DESCRIPTION
**Pull request by BradenBagby**
This is the revert to the revert here https://github.com/flutter/packages/pull/3272 that was merged because a flaky crash on an old device

### CODE REVIEW

**Comment by BradenBagby** [comment]
A couple comments @stuartmorgan @camsim99:

Ive tried reproducing the crash that was seen here https://github.com/flutter/packages/pull/3272 for the old Galaxy device on APK 26. I cannot reproduce it in TestLab.

Reading through the logs from the official testlab crash it looks like the camera was started, but by the time a captureRequest was made, the camera was already closed. This is probably due to the older device erroring somewhere early on. From the logs I can tell it is happening when the camera is flipped mid recording, so it happens on the second camera. This error was never caught and causes the application to crash. 

I check to make sure flipping while recording is compatible by looking at the APK version. If its not compatible, it just throws an error and doesnt flip. But this Galaxy APK 26 device doesnt indicate that it is incompatible. It just fails sometimes. 

This PR does not stop the error from happening. It just catches and logs it. Im not sure if that is enough. Wondering if @stuartmorgan could trigger another TestLab run to see if it happens again?

**Comment by stuartmorgan** [comment]
That should trigger a run; if it passes I can restart it a couple of times to try to catch flake.

**Comment by stuartmorgan** [comment]
Looks like some kind of Cirrus-wide issue; trying again to see if it's resolved.

**Comment by stuartmorgan** [comment]
> the full tests did not run

How so? https://cirrus-ci.com/task/4946608610082816?logs=firebase_test_lab looks like a full run to me, with all five integration tests passing.

**Comment by BradenBagby** [comment]
> > the full tests did not run
> 
> How so? https://cirrus-ci.com/task/4946608610082816?logs=firebase_test_lab looks like a full run to me, with all five integration tests passing.

I guess I was looking at the wrong thing

**Comment by stuartmorgan** [comment]
It's passed 5/5 runs (not counting the Cirrus meltdown), so it's looking good!

**Comment by BradenBagby** [comment]
So Im assuming we're waiting on a @camsim99 review now?

**Review by camsim99 — APPROVED** [review]
This sounds good to me!

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Pull request merged**
