### PR TITLE
Temporarily Disabling Flaky Integration Tests in Plugin Example Apps

### PR DESCRIPTION
**Pull request by jesswrd**
Temporarily skipping flaky integration tests in plugin example apps for camera, camera_android, and camera_android_camerax to safely land https://github.com/flutter/packages/pull/8037.

The flakes are unrelated to the mentioned PR and can likley be traced back to the following issues:
https://github.com/flutter/flutter/issues/154682
https://github.com/flutter/flutter/issues/157556

Partially addresses https://github.com/flutter/flutter/issues/152656

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Review by matanlurey — CHANGES_REQUESTED** [review]
Let's leave a TODO linking to an issue to renable these tests (could repurpose the ones you have already for Camille), i.e. at every line where you wrote `skip: true`. There should be at least one example in the repo if you want a reference.

This is important because otherwise we permanently skip test coverage which can have worse implications down the line.

Thanks for creating the PR!

**Comment by jesswrd** [comment]
Thanks for the explanation! done.

**Review by matanlurey — APPROVED** [review]

**Review by camsim99 — APPROVED** [review]
LGTM! Thanks for this :)

**Comment by stuartmorgan** [comment]
Are we sure these are flaky tests? The referenced PR is creating a situation that one of the referenced issues says will break the test, and the PR appears to be failing *every* Android camera package, even with retries. What's the evidence that this is pre-existing flake rather than the PR actually breaking the tests?

**Comment by camsim99** [comment]
@stuartmorgan can confirm this test is broken by something in the plugin not flaky and should be disabled until I can investigate.

https://github.com/flutter/flutter/issues/154682 has evidence of it failing locally in the past.
b/376074365 has further evidence of this previously being broken.

I know these don't reference `camera` but if those run on Android expect them to fail too because I'm guessing that CameraX doesn't support lower resolutions anymore but need to look into it this week. I believe the test only appears to be flaky because it doesn't run all of the time.

If you need more proof, let me know and I can validate its broken-ness to help unblock https://github.com/flutter/packages/pull/8037!

**Comment by camsim99** [comment]
Ah I just noticed https://github.com/flutter/packages/pull/8037#issuecomment-2480826738. It's possible that the bugs I've seen are related to bumping the target SDK version (though I don't think the b/376074365 is; it appears it's even more broken after the target SDK bump).

@stuartmorgan would a good compromise be not bumping the target SDK version until I fix the tests? @jesswrd not sure if your change https://github.com/flutter/packages/pull/8037 relies on that or not.

**Comment by jesswrd** [comment]
> @stuartmorgan would a good compromise be not bumping the target SDK version until I fix the tests? @jesswrd not sure if your change #8037 relies on that or not.

@camsim99 I can't merge without bumping the target sdk version. Google Play requires a target sdk version of at least 33, so I upgraded the target sdk version for `camera`, `camera_android`, and `camera_android_camera_androidx`. I get an error if I don't. 

@stuartmorgan Given the above, I think I should disable the tests but let me know how you'd like me to proceed.

**Comment by stuartmorgan** [comment]
> [flutter/flutter#154682](https://github.com/flutter/flutter/issues/154682) has evidence of it failing locally in the past.

Right, but it was failing in a PR that tried to bump the SDK version. And so the camera part was backed out of that PR. That's not flake, that's deterministic failure under the same conditions as the new PR.

It just seems like there's a mismatch here, where this PR describes the failures as "flakes [...] unrelated to the mentioned PR", but what I'm seeing is significant evidence that the failures are in fact directly caused by that PR, for reasons that have been previously established last time we tried to roll the target SDK.

> I believe the test only appears to be flaky because it doesn't run all of the time.

It runs any time anyone touches `camera` or and android sub-package, and also any time all tests run (such as every roll). If it were failing consistently on `main`, we would definitely know.

AFAICT the state is that it's fine on `main`, but attempting to roll the target SDK forward will break it. If we believe that the test is wrong and we want to disable it to roll the target SDK forward we can, but we should be clear that we are doing that—explicitly disabling a working test in order to land a PR that breaks that test—not disabling a flaky test.

**Comment by camsim99** [comment]
> AFAICT the state is that it's fine on main, but attempting to roll the target SDK forward will break it. If we believe that the test is wrong and we want to disable it to roll the target SDK forward we can, but we should be clear that we are doing that—explicitly disabling a working test in order to land a PR that breaks that test—not disabling a flaky test. (And I would suggest we do the disabling in the PR that breaks the tests, in that case.)

This SGTM!

**Pull request closed without merging**
