### PR TITLE
[go_router] Fix a typo in the ShellRoute docstring

### PR DESCRIPTION
**Pull request by emesterhazy**
Remove an extraneous "that" and an unnecessary comma.

This is just a simple typo fix for the docstring comment above the ShellRoute class.
Assuming I am correct that this is a typo, I think it makes the documentation a little
more difficult to read.

There is no issue open to track this, but I can create one if it's really necessary.
I'm going to check the box in the pre-launch checklist anyways :see_no_evil:

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by johnpryan — APPROVED** [review]
Thanks!

**Comment by johnpryan** [comment]
Hmm, I'm wondering why we can't submit this? This shouldn't need version change, so we added the "override: no versioning needed" label, but it's saying that "the change to this package could not be verified to be exempt from version changes according to repository policy"

**Comment by chunhtai** [comment]
forgot to rerun the check after applying the label, rerunning

**Pull request merged**
