### PR TITLE
[local_auth] Implemented plugin to support local auth in macOS

### PR DESCRIPTION
**Pull request by OutdatedGuy**
Created plugin `local_auth_macos` to support macOS platform for biometric and password authentication for the [local_auth](https://pub.dev/packages/local_auth) plugin.

The Objective-C code for macOS is built upon the implementation of iOS with necessary changes to work on macOS.

**Working Demo:**

https://github.com/flutter/packages/assets/74326345/71f31ec1-8d67-4208-9d06-ef2dd8f7ad89

<hr />

resolves https://github.com/flutter/flutter/issues/140685

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Per the comment in https://github.com/flutter/flutter/issues/140685, the first step here would need to be a package rename; we wouldn't accept this as-is since it duplicates a significant amount of code.

Marking this as a draft pending a prequel PR to rename the package.

**Comment by jmagman** [comment]
@OutdatedGuy thanks for contributing to this!  An example of what @stuartmorgan is asking for (sharing between the platforms instead of copying) was done for path_provider and shared_preferences, as he mentioned in https://github.com/flutter/flutter/issues/140685#issuecomment-1871098814

Examples:
https://github.com/flutter/plugins/pull/6988
https://github.com/flutter/plugins/pull/6920

**Comment by OutdatedGuy** [comment]
> @OutdatedGuy thanks for contributing to this! An example of what @stuartmorgan is asking for (sharing between the platforms instead of copying) was done for path_provider and shared_preferences, as he mentioned in [flutter/flutter#140685 (comment)](https://github.com/flutter/flutter/issues/140685#issuecomment-1871098814)
> 
> Examples: [flutter/plugins#6988](https://github.com/flutter/plugins/pull/6988) [flutter/plugins#6920](https://github.com/flutter/plugins/pull/6920)

Aahhh, now I get it.

@jmagman so what should I rename it to? `local_auth_foundation` as in examples you gave or `local_auth_darwin`?

**Comment by stuartmorgan** [comment]
> `local_auth_foundation` as in examples you gave or `local_auth_darwin`?

`LocalAuthentication` is not from the Foundation framework, so we would not call it `local_auth_foundation`.

**Comment by stuartmorgan** [comment]
> > Examples: [flutter/plugins#6988](https://github.com/flutter/plugins/pull/6988) [flutter/plugins#6920](https://github.com/flutter/plugins/pull/6920)
> 
> Aahhh, now I get it.

Note that those are a single PR for each plugin because we were merging existing implementations for two platforms, which is not the case for `local_auth`. So there won't be a single PR like in those examples, but instead a series of distinct PRs as a described in the issue.

**Comment by jmagman** [comment]
> @jmagman so what should I rename it to? `local_auth_foundation` as in examples you gave or `local_auth_darwin`?

I guess `local_auth_darwin`, naming is hard 🙂

**Comment by OutdatedGuy** [comment]
@stuartmorgan can you tell me what is exactly failing and how to solve it.

Also can you add the `override: no versioning needed` label.

**Comment by stuartmorgan** [comment]
> @stuartmorgan can you tell me what is exactly failing and how to solve it.

The project's unit tests appear to be configured incorrectly; I'll take a look in Xcode.

> Also can you add the `override: no versioning needed` label.

Which of the linked exemptions do you believe that this falls under? And why would you not want people to be able to use the macOS implementation?

**Comment by stuartmorgan** [comment]
The unit test file had not been added to the macOS project, so it couldn't build anything. I've pushed a fix.

**Review by stuartmorgan — CHANGES_REQUESTED** [review]

**Comment by stuartmorgan** [comment]
FYI, you'll need to resolve a raft of conflicts with https://github.com/flutter/packages/pull/6108 once that lands. The easiest way to do it will most likely be to make the same changes in your code and then just take your copy of everything.

**Comment by jmagman** [comment]
Heads up some of these classes are being renamed, though I don't see any obvious spots you'll merge conflict https://github.com/flutter/packages/pull/6108

**Comment by alexrabin-sentracam** [comment]
The implementation of this pr seems to be outdated with the current local_auth_darwin approach. I made a new pr https://github.com/flutter/packages/pull/6267

**Comment by stuartmorgan** [comment]
Since this is marked as a draft and hasn't been updated in several months I'm going to close it to clean out our review queue. Please don't hesitate to submit a new PR if you decide to revisit this. Thanks!

**Pull request closed without merging**
