### PR TITLE
[go_router_builder] Generate replace method in RouteExtension

### PR DESCRIPTION
**Pull request by omensight**
The problem is described here https://github.com/flutter/flutter/issues/115789
The method replace is added to the route_config.dart file 

*List which issues are fixed by this PR. You must list at least one issue.*
The replace method is needed in the generated class

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by omensight** [comment]
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need [an exemption](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests) to this rule, contact Hixie on the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat) (don't just cc him here, he won't see it! _He's on Discord!_).
> 
> If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, **is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?**
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

The test

> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need [an exemption](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests) to this rule, contact Hixie on the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat) (don't just cc him here, he won't see it! _He's on Discord!_).
> 
> If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, **is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?**
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

The ShouldGenerate annotation method have been edited in the line 93 of the file "_go_router_builder_test_input.dart" before to edit the lib code

**Review by chunhtai — COMMENTED** [review]
you should probably need run code gen in the example/ folder. I am surprise this does not trigger ci failure. The test/ensure_build_test.dart should have failed. @kevmoo Since you wrote the package that enabled this test, do you know why this is the case

**Comment by kevmoo** [comment]
https://cirrus-ci.com/task/4668337259544576?logs=unit_test#L239

This test is not properly configured on CI to run!

**Comment by chunhtai** [comment]
lol it looks like the presubmit-only tag is not working properly

**Comment by kevmoo** [comment]
> lol it looks like the presubmit-only tag is not working properly

You need to pass a flag to the test command to include the ensure bits.

See https://github.com/google/json_serializable.dart/blob/master/.github/workflows/dart.yml#L335

**Comment by chunhtai** [comment]
This will requires flutter_plugin_tools to support adding -t to the test command. another question may be whether this this test really needs this tag, Is there a reason why this need to be presubmit only?

**Comment by kevmoo** [comment]
@chunhtai – it runs a build and checks for a `git` delta. Can be annoying during normal development.

We could certainly drop it in the short run!

**Comment by omensight** [comment]
> Contributor

What should I do for it to be accepted?

**Comment by chunhtai** [comment]
We should wait for https://github.com/flutter/packages/pull/2846#discussion_r1036599512 because we are going to rename this to pushReplacement

**Comment by stuartmorgan** [comment]
What's the status of this PR? Is it ready for re-review?

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Should we test that the generated files are the files you get when you run the generator? Does that make sense?

**Comment by chunhtai** [comment]
> Should we test that the generated files are the files you get when you run the generator? Does that make sense?

Yes there is a test that makes sure of that https://github.com/flutter/packages/blob/main/packages/go_router_builder/example/test/ensure_build_test.dart

**Comment by Hixie** [comment]
test-exempt: is tested

**Review by hangyujin — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
hi @omensight can you fix the merge conflict?

**Comment by omensight** [comment]
> hi @omensight can you fix the merge conflict?

I did it, thanks for waiting.

**Comment by chunhtai** [comment]
@omensight it looks like there is some test failures

**Comment by omensight** [comment]
> @omensight it looks like there are some test failures

I'm sorry but I'm not understanding what the problem is.

**Comment by chunhtai** [comment]
This is the test failure
```
test/builder_test.dart: DefaultValueRoute                                                                                                                                                    
00:34 
+2
 -1
: test/builder_test.dart: DefaultValueRoute 
[E]
  Expected: 'GoRoute get $defaultValueRoute => GoRouteData.$route(\n'
              '      path: \'/default-value-route\',\n'
              '      factory: $DefaultValueRouteExtension._fromState,\n'
              '    );\n'
              '\n'
              'extension $DefaultValueRouteExtension on DefaultValueRoute {\n'
              '  static DefaultValueRoute _fromState(GoRouterState state) => DefaultValueRoute(\n'
              '        param: _$convertMapValue(\'param\', state.queryParams, int.parse) ?? 0,\n'
              '      );\n'
              '\n'
              '  String get location => GoRouteData.$location(\n'
              '        \'/default-value-route\',\n'
              '        queryParams: {\n'
              '          if (param != 0) \'param\': param.toString(),\n'
              '        },\n'
              '      );\n'
              '\n'
              '  void go(BuildContext context) => context.go(location, extra: this);\n'
              '\n'
              '  void push(BuildContext context) => context.push(location, extra: this);\n'
              '}\n'
              '\n'
              'T? _$convertMapValue<T>(\n'
              '  String key,\n'
              '  Map<String, String> map,\n'
              '  T Function(String) converter,\n'
              ') {\n'
              '  final value = map[key];\n'
              '  return value == null ? null : converter(value);\n'
              '}\n'
              ''
    Actual: 'GoRoute get $defaultValueRoute => GoRouteData.$route(\n'
              '      path: \'/default-value-route\',\n'
              '      factory: $DefaultValueRouteExtension._fromState,\n'
              '    );\n'
              '\n'
              'extension $DefaultValueRouteExtension on DefaultValueRoute {\n'
              '  static DefaultValueRoute _fromState(GoRouterState state) => DefaultValueRoute(\n'
              '        param: _$convertMapValue(\'param\', state.queryParams, int.parse) ?? 0,\n'
              '      );\n'
              '\n'
              '  String get location => GoRouteData.$location(\n'
              '        \'/default-value-route\',\n'
              '        queryParams: {\n'
              '          if (param != 0) \'param\': param.toString(),\n'
              '        },\n'
              '      );\n'
              '\n'
              '  void go(BuildContext context) => context.go(location, extra: this);\n'
              '\n'
              '  void push(BuildContext context) => context.push(location, extra: this);\n'
              '\n'
              '  void pushReplacement(BuildContext context) =>\n'
              '      context.pushReplacement(location, extra: this);\n'
              '}\n'
              '\n'
              'T? _$convertMapValue<T>(\n'
              '  String key,\n'
              '  Map<String, String> map,\n'
              '  T Function(String) converter,\n'
              ') {\n'
              '  final value = map[key];\n'
              '  return value == null ? null : converter(value);\n'
              '}\n'
              ''
     Which: is different.
            Expected: ... : this);\n}\n\nT? _$ ...
              Actual: ... : this);\n\n  void p ...
                                    ^
             Differ at offset 725
  package:test_api                                               expect
  package:source_gen_test/src/test_annotated_classes.dart 244:7  AnnotatedTest._shouldGenerateTest
ACTUAL CONTENT:
r'''
GoRoute get $defaultValueRoute => GoRouteData.$route(
      path: '/default-value-route',
      factory: $DefaultValueRouteExtension._fromState,
    );
extension $DefaultValueRouteExtension on DefaultValueRoute {
  static DefaultValueRoute _fromState(GoRouterState state) => DefaultValueRoute(
        param: _$convertMapValue('param', state.queryParams, int.parse) ?? 0,
      );
  String get location => GoRouteData.$location(
        '/default-value-route',
        queryParams: {
          if (param != 0) 'param': param.toString(),
        },
      );
  void go(BuildContext context) => context.go(location, extra: this);
  void push(BuildContext context) => context.push(location, extra: this);
  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location, extra: this);
}
T? _$convertMapValue<T>(
  String key,
  Map<String, String> map,
  T Function(String) converter,
) {
  final value = map[key];
  return value == null ? null : converter(value);
}
'''
```

**Comment by omensight** [comment]
> This is the test failure
> 
> ```
> test/builder_test.dart: DefaultValueRoute                                                                                                                                                    
> 00:34 
> +2
>  -1
> : test/builder_test.dart: DefaultValueRoute 
> [E]
>   Expected: 'GoRoute get $defaultValueRoute => GoRouteData.$route(\n'
>               '      path: \'/default-value-route\',\n'
>               '      factory: $DefaultValueRouteExtension._fromState,\n'
>               '    );\n'
>               '\n'
>               'extension $DefaultValueRouteExtension on DefaultValueRoute {\n'
>               '  static DefaultValueRoute _fromState(GoRouterState state) => DefaultValueRoute(\n'
>               '        param: _$convertMapValue(\'param\', state.queryParams, int.parse) ?? 0,\n'
>               '      );\n'
>               '\n'
>               '  String get location => GoRouteData.$location(\n'
>               '        \'/default-value-route\',\n'
>               '        queryParams: {\n'
>               '          if (param != 0) \'param\': param.toString(),\n'
>               '        },\n'
>               '      );\n'
>               '\n'
>               '  void go(BuildContext context) => context.go(location, extra: this);\n'
>               '\n'
>               '  void push(BuildContext context) => context.push(location, extra: this);\n'
>               '}\n'
>               '\n'
>               'T? _$convertMapValue<T>(\n'
>               '  String key,\n'
>               '  Map<String, String> map,\n'
>               '  T Function(String) converter,\n'
>               ') {\n'
>               '  final value = map[key];\n'
>               '  return value == null ? null : converter(value);\n'
>               '}\n'
>               ''
>     Actual: 'GoRoute get $defaultValueRoute => GoRouteData.$route(\n'
>               '      path: \'/default-value-route\',\n'
>               '      factory: $DefaultValueRouteExtension._fromState,\n'
>               '    );\n'
>               '\n'
>               'extension $DefaultValueRouteExtension on DefaultValueRoute {\n'
>               '  static DefaultValueRoute _fromState(GoRouterState state) => DefaultValueRoute(\n'
>               '        param: _$convertMapValue(\'param\', state.queryParams, int.parse) ?? 0,\n'
>               '      );\n'
>               '\n'
>               '  String get location => GoRouteData.$location(\n'
>               '        \'/default-value-route\',\n'
>               '        queryParams: {\n'
>               '          if (param != 0) \'param\': param.toString(),\n'
>               '        },\n'
>               '      );\n'
>               '\n'
>               '  void go(BuildContext context) => context.go(location, extra: this);\n'
>               '\n'
>               '  void push(BuildContext context) => context.push(location, extra: this);\n'
>               '\n'
>               '  void pushReplacement(BuildContext context) =>\n'
>               '      context.pushReplacement(location, extra: this);\n'
>               '}\n'
>               '\n'
>               'T? _$convertMapValue<T>(\n'
>               '  String key,\n'
>               '  Map<String, String> map,\n'
>               '  T Function(String) converter,\n'
>               ') {\n'
>               '  final value = map[key];\n'
>               '  return value == null ? null : converter(value);\n'
>               '}\n'
>               ''
>      Which: is different.
>             Expected: ... : this);\n}\n\nT? _$ ...
>               Actual: ... : this);\n\n  void p ...
>                                     ^
>              Differ at offset 725
>   package:test_api                                               expect
>   package:source_gen_test/src/test_annotated_classes.dart 244:7  AnnotatedTest._shouldGenerateTest
> ACTUAL CONTENT:
> r'''
> GoRoute get $defaultValueRoute => GoRouteData.$route(
>       path: '/default-value-route',
>       factory: $DefaultValueRouteExtension._fromState,
>     );
> extension $DefaultValueRouteExtension on DefaultValueRoute {
>   static DefaultValueRoute _fromState(GoRouterState state) => DefaultValueRoute(
>         param: _$convertMapValue('param', state.queryParams, int.parse) ?? 0,
>       );
>   String get location => GoRouteData.$location(
>         '/default-value-route',
>         queryParams: {
>           if (param != 0) 'param': param.toString(),
>         },
>       );
>   void go(BuildContext context) => context.go(location, extra: this);
>   void push(BuildContext context) => context.push(location, extra: this);
>   void pushReplacement(BuildContext context) =>
>       context.pushReplacement(location, extra: this);
> }
> T? _$convertMapValue<T>(
>   String key,
>   Map<String, String> map,
>   T Function(String) converter,
> ) {
>   final value = map[key];
>   return value == null ? null : converter(value);
> }
> '''
> ```

I have fixed the error, sorry, I didn't add the respective lines for the test.

**Pull request merged**
