### PR TITLE
[pigeon] Add Kotlin parameters to run pigeon command

### PR DESCRIPTION
**Pull request by paolorotolo**
Add example parameters to generate Kotlin code in pigeon's example as described in the attached issue.

I didn't update pigeon changelog since [pigeon/example/README.md](https://github.com/flutter/packages/blob/main/packages/pigeon/example/README.md) isn't published on pub.dev.

Thanks!

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/121238

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*
N/A

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by tarrinneal — APPROVED** [review]
Good catch, looks like we still need the c++ flags as well.

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
> * [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning), or this PR is [exempt from version changes](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates).
> * [x]  I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style).

You checked the boxes for these steps, but didn't do them. This README is published on pub.dev.

**Comment by paolorotolo** [comment]
Sorry about that, I thought that just the main README.md was published on pub.dev. I'm seeing now that the example/README is there too. I'll update the pr ASAP.

**Comment by paolorotolo** [comment]
I've updated CHANGELOG and pubspec and rebased with upstream.

**Comment by paolorotolo** [comment]
Not sure why tests are still failing

**Comment by paolorotolo** [comment]
Got it, `clang-format` was not installed on my machine. Should be fine now.

**Comment by tarrinneal** [comment]
@stuartmorgan I believe this is ready for a second review now.

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Comment by stuartmorgan** [comment]
Some other Pigeon PRs landed; could you re-rev the version here?

**Pull request merged**
