### PR TITLE
Bump Plugin Example Apps to TargetSdkVersion >= 34

### PR DESCRIPTION
**Pull request by jesswrd**
Bumping all plugin example apps to TargetSdkVersion >= 34. These are the remaining plugins example apps that have to be bumped.

Fixes https://github.com/flutter/flutter/issues/152929

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Review by matanlurey — APPROVED** [review]

**Comment by matanlurey** [comment]
Given these are examples and IMO, trivial, I'd say land this without waiting for individual CODEOWNERS.

**Review by camsim99 — APPROVED** [review]
This change LGTM :) but I do have two non-blocking questions:

1. I noticed [the `local_auth_android` example](https://github.com/flutter/packages/blob/311b660c622931a930ec87f5d11a1ca38ba8fd90/packages/local_auth/local_auth_android/example/android/app/build.gradle#L33) is not using the `flutter.targetSdkVersion` yet. Should we add it to make it consistent? From my quick search it does look like this PR would catch all of the other examples using a different `targetSdkVersion`.
2. Should we consider bumping [the `targetSdkVersion` of the all packages app](https://github.com/flutter/packages/blob/311b660c622931a930ec87f5d11a1ca38ba8fd90/script/tool/test/create_all_packages_app_command_test.dart#L78) to `flutter.targetSdkVersion` to in order to test against what we actually target in each of the plugins? cc @reidbaker for thoughts

**Comment by camsim99** [comment]
@jesswrd pinging you in case my questions got lost in the merge!

> This change LGTM :) but I do have two non-blocking questions:
> 
> 1. I noticed [the `local_auth_android` example](https://github.com/flutter/packages/blob/311b660c622931a930ec87f5d11a1ca38ba8fd90/packages/local_auth/local_auth_android/example/android/app/build.gradle#L33) is not using the `flutter.targetSdkVersion` yet. Should we add it to make it consistent? From my quick search it does look like this PR would catch all of the other examples using a different `targetSdkVersion`.
> 2. Should we consider bumping [the `targetSdkVersion` of the all packages app](https://github.com/flutter/packages/blob/311b660c622931a930ec87f5d11a1ca38ba8fd90/script/tool/test/create_all_packages_app_command_test.dart#L78) to `flutter.targetSdkVersion` to in order to test against what we actually target in each of the plugins? cc @reidbaker for thoughts

**Comment by jesswrd** [comment]
@camsim99 My bad I didn't see your comments. Let me roll it back :)

**Comment by camsim99** [comment]
@jesswrd wait no need to roll it back! Maybe we can just reopen the issue and we can discuss there? The change LGTM!

**Comment by jesswrd** [comment]
Okay sounds good

**Pull request merged**
