### PR TITLE
Make generated Java enum fields final

### PR DESCRIPTION
**Pull request by ChristianEdwardPadilla**
The enum should be immutable, so the fields should be final.

### CODE REVIEW

**Comment by tarrinneal** [comment]
Is this causing internal issues?

**Comment by ChristianEdwardPadilla** [comment]
Yes we've forked this line internally, because of a blocking lint used on all Java code internally.

**Review by tarrinneal — APPROVED** [review]

**Comment by tarrinneal** [comment]
You'll need to update the version number in the pubspec.yaml file as well as the generator tools file (in the lib folder)

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates for information about using the tooling.

**Pull request merged**
