### PR TITLE
[file_selector_android] Attempt to close system dialogs before integration tests run

### PR DESCRIPTION
**Pull request by bparrishMines**
Attempt to close any system dialogs before running the test. This idea came from https://stackoverflow.com/questions/39457305/android-testing-waited-for-the-root-of-the-view-hierarchy-to-have-window-focus. 

There may be a system dialog before the test runs that prevents the FlutterView from getting focus. Which also prevents any of the espresso actions to run

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Can we temporarily add the roll into this PR, to test that it actually fixes the issue we're having?

**Review by stuartmorgan — COMMENTED** [review]
Changes LGTM assuming they bear out in tests.

If this is it, we should also file an infra issue about the fact that the Android emulators suddenly started failing tests due to the presence of a system dialog, since that seems like a fundamental issue that we shouldn't have to work around in each test.

**Review by stuartmorgan — APPROVED** [review]

**Comment by bparrishMines** [comment]
> Changes LGTM assuming they bear out in tests.
> 
> If this is it, we should also file an infra issue about the fact that the Android emulators suddenly started failing tests due to the presence of a system dialog, since that seems like a fundamental issue that we shouldn't have to work around in each test.

I'm not sure if this is a problem that can be fixed by our infra. The stackoverflow link shows that it is also a problem with non-Flutter Android integration tests. It may just be related to Android 34 emulators since I don't remember it being flaky before.

**Review by gmackall — APPROVED** [review]

**Review by tarrinneal — APPROVED** [review]
another domino falls!

**Comment by gmackall** [comment]
It looks like 2 of the 4 checks the packages tree are red on are due to this error - should we land this on red or does the fix for the other flakes need to land first?

**Comment by tarrinneal** [comment]
merging on red to fix tree

**Pull request merged**
