### PR TITLE
Migrate the Animations Package to NNBD

### PR DESCRIPTION
**Pull request by rami-a**
This PR migrates the `animations` package to NNBD and is based on https://github.com/flutter/packages/pull/245 but the author is currently on vacation.

This also addresses the last comments from @goderbauer

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by zepfietje** [comment]
@rami-a are there any plans for publishing a null-safe prerelease version of the animations package?

**Comment by rami-a** [comment]
I believe so. @goderbauer and @shihaohong do you know what the plan is for publishing a prerelease null-safe version?

**Comment by shihaohong** [comment]
I discussed some ideas with Tianguang in the previous PR (https://github.com/flutter/packages/pull/245#issuecomment-732642312), but we never got to talking about a timeline or who was going to drive publishing the prerelease.

**Pull request merged**
