### PR TITLE
[extension_google_sign_in_as_googleapis_auth] Adopt code excerpts in …

### PR DESCRIPTION
**Pull request by mike-v2**
…README

Updates the README to use a compiled excerpt source for its example of using google_sign_in plugin with the `googleapis` package.

Part of [flutter/flutter#102679](https://github.com/flutter/flutter/issues/102679)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by mike-v2** [comment]
I wasn't sure if this code needs a test, since it's essentially just making an API call, and therefore the test would just be testing the mock?

**Comment by mike-v2** [comment]
The failed check in `Windows_x64 dart_unit_tests_shard_1 master` seems to come from a failed unit test in `packages/camera/camera_android_camerax`, but I was unable to reproduce this locally.

**Review by tarrinneal — CHANGES_REQUESTED** [review]
I don't think the new file you added is necessary. The former example is already in the example/lib/main file I believe. You should be able to just quote it from there (thus avoiding the need for tests and such for the new code).

**Comment by tarrinneal** [comment]
There's a conflict that needs to be handled still @mike-v2

**Comment by tarrinneal** [comment]
There's another one :(

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Comment by stuartmorgan** [comment]
@tarrinneal You have to approve it :)

**Comment by tarrinneal** [comment]
> @tarrinneal You have to approve it :)

I don't wanna

**Review by tarrinneal — APPROVED** [review]

**Pull request merged**
