### PR TITLE
[flutter_markdown] Removed build status from README

### PR DESCRIPTION
**Pull request by 0xVesion**
- The build status wasn't displaying correctly, and clicking the badge yielded in a 404 not found error. I assume the build status is not required anymore.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Thanks for the contribution! You deleted half of the PR checklist, and as result are missing several required steps. I've restored the missing half; please mark this as ready for review once you've worked through the remaining items.

**Comment by 0xVesion** [comment]
Sorry for removing the steps from the checklist @stuartmorgan. I thought they weren't applicable to my PR, as I only changed the README of the repo. Do I have to increase the version of the package for this change?

**Comment by stuartmorgan** [comment]
> Sorry for removing the steps from the checklist @stuartmorgan. I thought they weren't applicable to my PR, as I only changed the README of the repo. Do I have to increase the version of the package for this change?

This is answered in the FAQ of the description of what changes require version changes, which is linked from that step in the template.

**Comment by stuartmorgan** [comment]
Closing in favor of https://github.com/flutter/packages/pull/1326

**Pull request closed without merging**
