### PR TITLE
Explicitly pass the web renderer into the tests.

### PR DESCRIPTION
**Pull request by eyebrowsoffire**
The web tests currently all assume to be using the html renderer. `flutter test` previously erroneously was serving files for the HTML renderer by default (which is not the intended behavior). After this was fixed, the tests started running on the CanvasKit renderer and some of them broke. If we are relying on the html renderer, we should explicitly pass it when running `flutter test`

### CODE REVIEW

**Comment by stuartmorgan** [comment]
This tooling has unit test, so this will need a test.

@ditman It seems like we have a coverage problem here; is there an issue tracking the fact that we are only testing with one renderer?

**Comment by eyebrowsoffire** [comment]
@stuartmorgan I went ahead and filed https://github.com/flutter/flutter/issues/143543

**Review by stuartmorgan — APPROVED** [review]
LGTM.

Do we need to do the same thing for [`flutter drive`](https://github.com/flutter/packages/blob/main/script/tool/lib/src/drive_examples_command.dart)?

**Comment by eyebrowsoffire** [comment]
> Do we need to do the same thing for [flutter drive](https://github.com/flutter/packages/blob/main/script/tool/lib/src/drive_examples_command.dart)?

Probably a good idea. Let me look

**Pull request merged**
