### PR TITLE
[flutter_image] added example app

### PR DESCRIPTION
**Pull request by opxdelwin**
Added example app for pub points, PR is test-exempt & exempt from version changes.

fixes https://github.com/flutter/flutter/issues/133471

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Thanks for the contribution!

> PR is test-exempt

Example apps are not test exempt; we want to ensure that they continue to work.

> & exempt from version changes.

Which of [the exemption reasons](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version) do you believe this falls under?

> fixes [flutter/flutter#133471](https://github.com/flutter/flutter/issues/133471)

That issue is for the `platform` package, not the `flutter_image` package.

For `flutter_image`, there is already https://github.com/flutter/packages/pull/4353 under review. If you have feedback about that PR I would strongly encourage providing comments on the PR, rather than opening an alternate PR, since the most likely outcome is that the existing PR that's already undergoing review will land.

**Comment by opxdelwin** [comment]
> we don't provide any kind of example doc or app for `flutter_image`. We should have a simple example app for it that demonstrates its functionality.

Was mentioned in https://github.com/flutter/flutter/issues/133471

and since #4353 has not yet landed, I didn't notice existing app in the package directories...
Regarding the versioning exempt, it's an honest mistake, my bad

**Comment by opxdelwin** [comment]
Closing as duplicate of https://github.com/flutter/packages/pull/4353

**Comment by stuartmorgan** [comment]
Oops, that's a copy/paste error in the issue description. I'll fix it, thanks.

**Comment by opxdelwin** [comment]
@stuartmorgan no problem :)

**Pull request closed without merging**
