### PR TITLE
[flutter_template_images] Support the new skeleton app template

### PR DESCRIPTION
**Pull request by filiph**
Relands #295 after it was reverted with #353.

> There is a proposal to add a new Flutter app template to the flutter CLI. This new app template lives alongside the current counter template, it does not replace it. The team has made the following request on the related PR: 
>
> > We need to find a way to not duplicate the existing platform files. We occasionally have to update these, and having 2 copies of everything is going to increase the chances that we accidentally get out of sync somewhere.
>
> This PR moves assets common to both apps into an `app_shared` directory and introduces a new `list_detail_app` folder to support images unique to the new template.
>
> Related Issues:
>
>  - https://github.com/flutter/flutter/pull/76519

See more at #295.

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
  - no code change here, just new files
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by filiph** [comment]
Hi, this is ready for review. I have LGTM for the corresponding change over at https://github.com/flutter/flutter/pull/83530.

**Comment by stuartmorgan** [comment]
> Hi, this is ready for review. I have LGTM for the corresponding change over at [flutter/flutter#83530](https://github.com/flutter/flutter/pull/83530).

The PR doesn't have any actual approvals, and it looks like there is active discussion there right now about `create` not actually working correctly with that template.

The previous version had initial LGTMs too, but was never actually finished despite that. I will review and land this when that PR is approved by everyone who you are expecting a review from, and it is *ready to land*, other than the tests.

**Comment by filiph** [comment]
That's fair. I do have LGTMs from csells and goderbauer on that CL (they're comments), but you're right that Hixie and HansMuller have only commented. I should have checked. Sorry about that.

I'll get the missing approvals.

**Comment by filiph** [comment]
Hi, https://github.com/flutter/flutter/pull/83530 is now LGTM'd (Hixie & Jonah in UI + comment; Chris & Michael in comment text only). The change passes locally — at least the test I was able to run on my device.

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Pull request merged**
