### PR TITLE
[pigeon] Allow newer versions of analyzer

### PR DESCRIPTION
**Pull request by stuartmorgan**
The changes since 2.4 are almost all deprecations of, and removal of, code that Pigeon doesn't use, so we can support a range for maximal ecosystem compatibility.

Fixes https://github.com/flutter/flutter/issues/105090

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by brianquinlan** [comment]
A strong +1 on this PR - it is needed to update the flutter package dependencies. See https://github.com/flutter/flutter/pull/106148

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by brianquinlan** [comment]
What's the normal delay between merge and releasing an updated package?

**Comment by stuartmorgan** [comment]
> What's the normal delay between merge and releasing an updated package?

The duration of our post-submit automated tests. It had already been auto-published by the time you asked this question :)

**Comment by brianquinlan** [comment]
Sweet setup ;-)

**Pull request merged**
