### PR TITLE
[many] Remove dependency on `kotlin-bom`

### PR DESCRIPTION
**Pull request by gmackall**
~This dependency seems to no longer be necessary. I expected this would be because the the androidx upgrade that [landed recently](https://github.com/flutter/engine/pull/53592) fixed the problem ([see theory](https://github.com/flutter/packages/pull/7036#issuecomment-2218659328)), but it seems that the packages even build on stable successfully. Perhaps there have been updates to the underlying `androidx` libraries themselves that fix the conflict, and we updated the versions in plugins far enough? I'm unsure.~

Updated for 3.24 release.

In a sense, fixes https://github.com/flutter/flutter/issues/125062

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by gmackall** [comment]
Expecting tests to fail on stable, will need to wait until stable contains https://github.com/flutter/engine/pull/53592, aka contains https://github.com/flutter/flutter/pull/150952. This should be `3.24`.

**Comment by stuartmorgan** [comment]
test-exempt: configuration change

**Review by camsim99 — APPROVED** [review]
Woohoo!

**Comment by stuartmorgan** [comment]
https://github.com/flutter/packages/pull/3960 suggests that we weren't catching this problem in CI. Given that, are we confident that we would catch it now (i.e., that the green result here is actually telling us what we need to know)? Can we try re-creating some things like what's described in that PR description?

**Comment by gmackall** [comment]
> #3960 suggests that we weren't catching this problem in CI. Given that, are we confident that we would catch it now (i.e., that the green result here is actually telling us what we need to know)? Can we try manually re-creating (on stable) some things like what's described in that PR description?

This is a good question, I'll try with a workflow similar to what I described in that PR for all the affected packages on stable. 

If I had to guess why we didn't catch this in ci for `camerax` (and it really is a guess) it would be that the `all_packages` app maybe already had the workaround included in one of the packages, which fixed it for the app, and perhaps the `camerax` example was also depending on a plugin that had the fix (but only the example, not the plugin itself). Anyways I'll double check all the plugins.

**Comment by gmackall** [comment]
Hmm okay, yeah the workflow described in the PR:

1. `flutter create sample`
2. Add a dependency on the locally changed plugin to the pubspec
3. `flutter build apk`

Fails on stable, while succeeding on master. So this will indeed have to wait for the next stable. I'll also try to figure out why the `all_packages`/`example` apps aren't catching this in the meantime - I don't know why they wouldn't, but it's clear they aren't.

**Review by reidbaker — APPROVED** [review]
approve % next stable being set at the minimum

**Review by matanlurey — APPROVED** [review]

**Comment by gmackall** [comment]
I think this is going to be blocked on the same `main < stable` blocker from the last release

**Comment by stuartmorgan** [comment]
Yep, I've already flagged it in Discord; it's blocking at least one other PR already as well.

**Comment by gmackall** [comment]
This should be ready for review again for any remaining reviewers that want to take a look.

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Review by reidbaker — APPROVED** [review]

**Review by bparrishMines — APPROVED** [review]
LGTM

**Comment by reidbaker** [comment]
Our assumptions about this being safe might not be correct https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20android_platform_tests_shard_2%20master/1640/overview

**Comment by stuartmorgan** [comment]
https://github.com/flutter/packages/pull/7997 has some follow-up analysis on that failure.

**Comment by reidbaker** [comment]
https://github.com/flutter/packages/pull/7986 Updated the annotation version 
The commits added in that patch version are listed here 
https://android.googlesource.com/platform/frameworks/support/+log/2e6556166965445a8a129114765a3903c063735c..87b88ad088cc9b18d4ab75611fc8b74e8b01c24a/annotation
"Bump Kotlin Target of annotation, collection, and compose to 1.9"

FWIW flutter fix said to update the kotlin version to 1.9.

**Pull request merged**
