### PR TITLE
[go_router_builder] fix integration test

### PR DESCRIPTION
**Pull request by kevmoo**
Related to https://github.com/flutter/flutter/issues/102799

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by chunhtai** [comment]
since the ci does not pick up the test in go_router_builder/example/test, can you write a script in /script folder to run the test?
Once we have that we can add a new task in .cirrus.yml

**Comment by kevmoo** [comment]
This fixes local invocation, which is broken. Let's land this and then do the next bit...

Which `/script` dir are you talking about?

**Comment by ditman** [comment]
No need to write new tests, I think, only make the `example` directory comply with the file structure that other packages have so it's automatically picked up by the tooling. Take a look at this one:

https://github.com/flutter/packages/tree/main/packages/pointer_interceptor/example

(Those tests can run with `flutter drive`, there's a README there too!)

**Comment by kevmoo** [comment]
> No need to write new tests, I think, only make the `example` directory comply with the file structure that other packages have so it's automatically picked up by the tooling. 

How?

**Comment by chunhtai** [comment]
> No need to write new tests, I think, only make the `example` directory comply with the file structure that other packages have so it's automatically picked up by the tooling. Take a look at this one:
> 
> https://github.com/flutter/packages/tree/main/packages/pointer_interceptor/example
> 
> (Those tests can run with `flutter drive`, there's a README there too!)

are those tests run in ci? I can't seem to find the task that runs it

**Comment by chunhtai** [comment]
you may need to bump the version, yeah the ci setup can be a separate task

**Review by chunhtai — APPROVED** [review]
LGTM except for required version bump, running test in ci will be tracked in https://github.com/flutter/flutter/issues/102845

**Comment by ditman** [comment]
If you guys don't want to bump the version (because this is only fixing tests), you can do a `## NEXT` entry in the CHANGELOG.md, like this one:

https://github.com/flutter/plugins/blob/c808ab8c9c71cf99ca3656895d1624caddff320e/packages/webview_flutter/webview_flutter_web/CHANGELOG.md?plain=1#L1-L3

**Pull request merged**
