### PR TITLE
[image_picker] fix typos in comments

### PR DESCRIPTION
**Pull request by ElDavoo**
Removes two extraneous "fo".

This is just a simple typo fix , assuming I am correct that this is a typo.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

I ticked the relevant boxes  

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by tarrinneal — APPROVED** [review]
Thanks!

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
This isn't version-exempt; these are documentation comments of public methods, and the most common way developers will see them is locally, in their IDE. That means that this needs to be published to be useful, so needs a version and changelog update.

**Review by stuartmorgan — APPROVED** [review]
LGTM ; per offline discussion we'll just skip the version bumps here.

**Comment by tarrinneal** [comment]
Adding version exemption since this change is fine to get published when another pr pulls them in.

**Comment by ElDavoo** [comment]
Ok, i was going to rebase it but then forgot, thank you for merging!

**Pull request merged**
