### PR TITLE
Add shell route example

### PR DESCRIPTION
**Pull request by jonmountjoy**
It's in the repo, but not in the README, so I've added it to the README with all the others.

### CODE REVIEW

**Review by chunhtai — COMMENTED** [review]
LGTM

**Comment by chunhtai** [comment]
the ci is failing, it needs to be fixed before this can merge

**Comment by jonmountjoy** [comment]
It appears to be failing because the CI thinks this needs a version change, which it surely doesn't?  Can someone comment in the PR to explain why the PR is exempt and add the "override: no versioning needed" label?

**Comment by chunhtai** [comment]
I applied the label, but you still need to add a `## NEXT` to the changelog

**Comment by chunhtai** [comment]
Hi @jonmountjoy It looks like there is a merge conflict.

**Pull request closed without merging**
