### PR TITLE
[url_launcher_web] Disallows launching "javascript:" URLs.

### PR DESCRIPTION
**Pull request by ditman**
This PR updates the URL launcher to:

* Implement the new `launchUrl` method.
* Disallow `launch` and `launchUrl` for URLs with the `javascript:` scheme. 
* Prevent _Tabnabbing_.

### Issues

Fixes https://github.com/flutter/flutter/issues/136657

### Tests

Integration tests (and mocks) updated.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by mdebbar — COMMENTED** [review]
The code itself looks good to me, though I'm hesitant about blanket-adding `noopener,noreferrer`. I'm okay with making this the default behavior. But should we give developers the option to allow communication back with the main window? There could be a legit use case when the app is opening its own popup (not a user-provided URL).

**Comment by stuartmorgan** [comment]
> I'm hesitant about blanket-adding `noopener,noreferrer`. I'm okay with making this the default behavior. But should we give developers the option to allow communication back with the main window? There could be a legit use case when the app is opening its own popup (not a user-provided URL).

I had the same thought initially, but then wasn't convinced that `url_launcher` should be the mechanism for that use case. It's not intended to be a window management utility, and doesn't work that way on any other platform, so I think there's a good argument that if what you want to open is a page that's communicating with the main window, `url_launcher` isn't the plugin for you. Maybe `Link`'s use of `url_launcher` changes that dynamic though? Should `Link` be less tightly bound to allow use of `Link` in those cases without using `openUrl`, maybe?

**Comment by ditman** [comment]
> But should we give developers the option to allow communication back with the main window? There could be a legit use case when the app is opening its own popup (not a user-provided URL).

@mdebbar it's easy for us to pass a new `LaunchOptions` property to disable the "noreferrer, noopener" in case this breaks any user of the feature.

My two opinions, hoever:

* if you want to call `window.open` without the noopener rule, you can write your own code to do so (for example: `google_sign_in` handles its own popup).
* if you need to talk to a popup you opened, you should be using `postMessage`, so you can have a protocol that you can validate.

(Do you really think this change is a big breaking change?)

> Should Link be less tightly bound to allow use of Link in those cases without using openUrl, maybe?

@stuartmorgan hmmm, I think `Link` does not use `openUrl` on the web? (but @mdebbar can confirm!) ([code](https://github.com/flutter/packages/blob/353e9a2f951d10a2c2443a3ce0c62904ed62edc8/packages/url_launcher/url_launcher_web/lib/src/link.dart#L190-L212))

**Review by stuartmorgan — APPROVED** [review]
> @stuartmorgan hmmm, I think `Link` does not use `openUrl` on the web

[Doh!](https://github.com/flutter/packages/blob/353e9a2f951d10a2c2443a3ce0c62904ed62edc8/packages/url_launcher/url_launcher/lib/src/link.dart#L83)

This LGTM then. I would at this point vote for only adding options to remove the attributes if we get significant feedback that there's a compelling case for them in the context of the intended use of `url_launcher`.

**Comment by ditman** [comment]
> I would at this point vote for only adding options to remove the attributes if we get significant feedback that there's a compelling case for them in the context of the intended use of `url_launcher`.

I agree, but will wait to see how strongly @mdebbar feels about it!

**Review by mdebbar — APPROVED** [review]
LGTM. Keeping an eye for user feedback sounds like a good strategy!

**Comment by ditman** [comment]
Applying `autosubmit`

**Pull request merged**
