### PR TITLE
[image_picker] Copy exif tags in categories II and III

### PR DESCRIPTION
**Pull request by RobertOdrowaz**
Added all exif tags from Category II and Category III (excluding ones that don't have consts in `ExifInterface` WaterDepth etc.). Those tags include data not related to the structure of the file itself so resizing definitely doesn't invalidate them and thus they should be copied over.

I've also switched from list of raw strings to consts provided be the `ExifInterface`

I'm not sure show to handle `TAG_ISO_SPEED_RATINGS` deprecation in this case. The const is deprecated and the tag itself is deprecated in the standard however it would be reasonable to copy it as well to handle legacy files which include it. It was also being copied in the previous versions of this package.

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/132827

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
Thanks for the contribution!

> * [x]  I read and followed the [relevant style guides](https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style) and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)

The CI format check is failing; please ensure that the Java is auto-formatted as well.

> * [x]  I added new tests to check the change I am making, or this PR is [test-exempt](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests).

This change is not exempt, so will need tests before we can proceed with the review.

**Comment by gmackall** [comment]
Thanks for adding tests! I'll take a look this afternoon 🙂

**Review by gmackall — COMMENTED** [review]
Thanks for the contribution! This change mostly LGTM, but do you have a link to documentation on where Exif tags are broken into categories? I couldn't find anything clear just by searching. 

Also, would you mind adding documentation to `copyExif` explaining why we select this subset of Exif tags? It probably should have some documentation covering that, and this change seems like a good time to add it.

**Comment by RobertOdrowaz** [comment]
Thanks for the review. https://www.cipa.jp/std/documents/download_e.html?DC-008-Translation-2023-E here you can download the standard. On page 234 there is a table explaining categories and on page 238 is a table matching tags to categories.

I will add the explanation regarding tags chosen later today.

**Comment by RobertOdrowaz** [comment]
FYI couple of tags are missing eg. WaterDepth because `ExifInterface` is based on older 2.3 exif standard and those were introduced in 2.31. I believe we could copy them as well but we would need to go back to using raw string values

**Review by gmackall — APPROVED** [review]
This LGTM! @stuartmorgan do you want to do secondary review or shall I find another reviewer?

**Comment by stuartmorgan** [comment]
@tarrinneal is the ecosystem team codeowner for this plugin, so would probably be the best person to do the secondary review.

**Review by tarrinneal — APPROVED** [review]
lgtm, thanks for putting this together!

**Comment by stuartmorgan** [comment]
It looks like this just needs conflicts resolved, then we can land it.

**Review by stuartmorgan — APPROVED** [review]

**Pull request merged**
