### PR TITLE
[video_player] Bump min Android implementation version for better Java compatibility

### PR DESCRIPTION
**Pull request by vbuberen**
This change should help people avoid compilation issues caused by Java compatibility issues in old `video_player_android` versions as mentioned in https://github.com/flutter/flutter/issues/156111#issuecomment-2395462532

Bumped to `2.7.9` as this is the version which had changes for Java compatibility as mentioned in the linked comment and plugin's changelogs: https://pub.dev/packages/video_player_android/changelog#279

I understand that running `flutter pub upgrade` should resolve the issue, but it is not always possible to not get into dependency update hell in big projects.
The motivation to open such PR is the same as https://github.com/flutter/packages/pull/6355 - to let people get proper fixed versions even if they don't run `flutter pub upgrade` for their whole project.

Resolves https://github.com/flutter/flutter/issues/157691 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
> I understand that running `flutter pub upgrade` should resolve the issue, but it is not always possible to not get into dependency update hell in big projects.

Developers updating their toolchains should be prepared to update their dependencies, including transitive dependencies. If they choose to do that manually they certainly can, but they should not expect the entire ecosystem to enforce artificial minimums on all clients (creating more opportunities for different kinds of dependency problems which *can't* be fixed by clients).

> The motivation to open such PR is the same as #6355 - to let people get proper fixed versions even if they don't run `flutter pub upgrade` for their whole project.

The context of #6355 was very different: nobody who did not have the required version would be able to publish their app. That is not the case here; the situation where this version is required is one that is a choice by the developer (to use Java 21), not a requirement imposed onto the ecosystem from outside.

Closing as this goes against our standard versioning policy, and this situation does not warrant an exception.

**Comment by vbuberen** [comment]
> Developers updating their toolchains should be prepared to update their dependencies, including transitive dependencies. If they choose to do that manually they certainly can, but they should not expect the entire ecosystem to enforce artificial

Please check the issue I created with all the details of the problem I wanted to solve. Running `flutter pub upgrade video_player` doesn't make `video_player_android` update even though the project uses min Dart >=3.4.0 and Flutter >=3.24.1

> but they should not expect the entire ecosystem to enforce artificial minimums on all clients (creating more opportunities for different kinds of dependency problems which can't be fixed by clients).

Could you share concrete example about such opportunities from this change?

**Comment by vbuberen** [comment]
>  is a choice by the developer (to use Java 21), not a requirement imposed onto the ecosystem from outside.

It wasn't my choice as I explained in the linked issue. It is something that changed with updates to Android Studio and IntelliJ. I didn't specify Java 21 anywhere myself. So, technically, it something that was forced by the IDE.

**Comment by stuartmorgan** [comment]
> Running `flutter pub upgrade video_player` doesn't make `video_player_android` update even though the project uses min Dart >=3.4.0 and Flutter >=3.24.1

That's because of https://github.com/dart-lang/pub/issues/3504; it's a `pub` behavior, and has nothing to do with this plugin specifically or its constraints. (Once the very-recently-added flag reaches stable, we'll be able to recommend that for cases like this.)

> It wasn't my choice as I explained in the linked issue. It is something that changed with updates to Android Studio and IntelliJ. I didn't specify Java 21 anywhere myself. So, technically, it something that was forced by the IDE.

Updating your toolchain (including your IDE) is a choice, as is using Java from Android Studio rather than setting it to a version you control separately.

**Pull request closed without merging**
