### PR TITLE
[ci] Update for 3.27 stable release

### PR DESCRIPTION
**Pull request by stuartmorgan**
Updates CI with the steps from [the stable release playbook](https://github.com/flutter/flutter/blob/master/docs/ecosystem/release/Updating-Packages-repo-for-a-stable-release.md) to account for the new 3.27 stable release.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Package owners, please ignore this PR; the changes are mechanical and auto-generated. Only @tarrinneal needs to review this.

**Review by domesticmouse — APPROVED** [review]
In case @tarrinneal is busy =)

**Review by tarrinneal — APPROVED** [review]
good this looks

**Review by Piinks — CHANGES_REQUESTED** [review]
LGTM

**Comment by Piinks** [comment]
Oh whoops, toggled the wrong radio

**Review by Piinks — APPROVED** [review]
Once more with feeling...

**Comment by ditman** [comment]
🚀

**Review by yjbanov — APPROVED** [review]

**Pull request merged**
