### PR TITLE
[Infra] Update .cirrus.yml to use api 33 for FTL testing

### PR DESCRIPTION
**Pull request by reidbaker**
https://github.com/flutter/flutter/issues/127682
relevent line from ` gcloud firebase test android models list`
```
┌─────────────────────┬────────────────────┬──────────────────────────────────────────┬──────────┬─────────────┬─────────────────────────┬──────────────────┐
│       MODEL_ID      │        MAKE        │                MODEL_NAME                │   FORM   │  RESOLUTION │      OS_VERSION_IDS     │       TAGS       │
├─────────────────────┼────────────────────┼──────────────────────────────────────────┼──────────┼─────────────┼─────────────────────────┼──────────────────┤
| panther             │ Google             │ Pixel 7                                  │ PHYSICAL │ 2400 x 1080 │ 33                      │                  │
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by gmackall — APPROVED** [review]
LGTM!

**Review by dnfield — APPROVED** [review]

**Review by stuartmorgan-g — COMMENTED** [review]
LGTM assuming this is a high-availability device.

**Review by johnmccutchan — APPROVED** [review]

**Comment by reidbaker** [comment]
> LGTM assuming this is a high-availability device.

Yes it is 

```
gcloud firebase test android models describe panther
brand: google
codename: panther
form: PHYSICAL
formFactor: PHONE
id: panther
manufacturer: Google
name: Pixel 7
perVersionInfo:
- deviceCapacity: DEVICE_CAPACITY_HIGH
  versionId: '33'
screenDensity: 420
screenX: 1080
screenY: 2400
supportedAbis:
- arm64-v8a
supportedVersionIds:
- '33'
```

**Comment by stuartmorgan** [comment]
@reidbaker Did you want to update this to change the LUCI config instead?

**Comment by reidbaker** [comment]
> @reidbaker Did you want to update this to change the LUCI config instead?

Yes I did I have just had other work on my plate.

**Comment by stuartmorgan** [comment]
(Marking as draft since it's obsolete as currently written.)

**Pull request closed without merging**
