### PR TITLE
[Android] Introduces API 34 emulators for subset of tests

### PR DESCRIPTION
**Pull request by camsim99**
Introduces API 34 emulators for subset of tests not causing test failures in https://github.com/flutter/packages/pull/4804. Also changes linux_android version to 34v1.

Continuation of https://github.com/flutter/packages/pull/4820.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by camsim99** [comment]
@stuartmorgan I'm seeing failures on https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_platform_tests_api_33_shard_1%20master/9/overview because `espresso` does not have unit tests. Am I missing an exclusion do you know?

**Comment by stuartmorgan** [comment]
Yes, it looks like `android_platform_tests_api_33_avd.yaml` lost all the `--exclude` flags from the original version of the script. Excluding things that wouldn't be run anyway is harmless, so you should be able to just copy all of the excludes (other than the `still_requires_api_33` file) from the 34 script to the 33 script.

**Comment by camsim99** [comment]
> Yes, it looks like `android_platform_tests_api_33_avd.yaml` lost all the `--exclude` flags from the original version of the script. Excluding things that wouldn't be run anyway is harmless, so you should be able to just copy all of the excludes (other than the `still_requires_api_33` file) from the 34 script to the 33 script.

Ah good catch, thank you!

**Comment by stuartmorgan** [comment]
It would have been a better catch if I'd noticed when I reviewed PR adding that script :)

**Review by stuartmorgan — APPROVED** [review]
LGTM!

**Pull request merged**
