### PR TITLE
fix analysis warnings in imitation_game

### PR DESCRIPTION
**Pull request by yjbanov**
This should fix the master branch build.

/cc @creativecreatorormaybenot

### CODE REVIEW

**Comment by gaaclarke** [comment]
Thanks, weird that it didn't need this change:
```diff
--- a/packages/imitation_game/bin/imitation_game.dart
+++ b/packages/imitation_game/bin/imitation_game.dart
@@ -5,8 +5,6 @@ import 'package:mustache/mustache.dart';
 import 'package:imitation_game/README_template.dart';
 import 'package:args/args.dart';
 
-// ignore_for_file: avoid_as
-
 const int _port = 4040;
 
 Future<String> _findIpAddress() async {

```

**Comment by creativecreatorormaybenot** [comment]
I suppose it is due to an external analyzer change.

**Review by gaaclarke — APPROVED** [review]

**Comment by gaaclarke** [comment]
@creativecreatorormaybenot yep, it would be nice if those changes were incorporated as commits too so we could catch it earlier.  Here's another reason why having a mega-repository would be great (https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext).  I just had to fix the tree the other day after someone else's commit, now Yegor fixed it for me, karma.

**Comment by yjbanov** [comment]
I know. Monorepo FTW! I'm not sure what's up with `ignore_for_file: avoid_as` but if I remove it the analyzer complains :man_shrugging:

**Comment by yjbanov** [comment]
Landing on red to (hopefully) fix the build.

**Comment by yjbanov** [comment]
Filed https://github.com/flutter/flutter/issues/68934

**Pull request merged**
