### PR TITLE
[image_picker_ios] Update UITests for Xcode 15/iOS 17

### PR DESCRIPTION
**Pull request by vashworth**
With Xcode 15, XCTest's `addUIInterruptionMonitorWithDescription` sometimes doesn't work. To fix, I added a fallback to query for the buttons in the permissions dialog.

Also, the Allow text in the permissions dialog is different in iOS 17 than previous versions.

Fixes https://github.com/flutter/flutter/issues/136747

Example passing on Xcode 15 with iOS 17 simulator: https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20ios_platform_tests_shard_3%20master/7604/overview

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by vashworth** [comment]
@stuartmorgan I ran it locally on Xcode 14/iOS 16 but I don't think the CI test ran the image_picker_ios native tests: https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20ios_platform_tests_shard_3%20master/7605/overview
Is there any way I can trigger that?

**Comment by cyanglaz** [comment]
@vashworth It's in different shard: https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20ios_platform_tests_shard_1%20master/7574/overview

log: (they passed)
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8766871620514207761/+/u/Run_package_tests/native_test/stdout?format=raw

**Comment by vashworth** [comment]
> @vashworth It's in different shard: https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20ios_platform_tests_shard_1%20master/7574/overview
> 
> log: (they passed) https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8766871620514207761/+/u/Run_package_tests/native_test/stdout?format=raw

Oh excellent! Thanks!

**Comment by stuartmorgan** [comment]
> > @vashworth It's in different shard: https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20ios_platform_tests_shard_1%20master/7574/overview
> > log: (they passed) https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8766871620514207761/+/u/Run_package_tests/native_test/stdout?format=raw
> 
> Oh excellent! Thanks!

For general future reference: the way the sharding works in this repo (to try to minimize total time spent waiting on tests regardless of the change) is that the tooling figures out every package that could be affected by the PR, and then evenly distributes that list across the shards, which means packages don't have stable mapping to specific shards. If you compare runs that run every package it'll be stable (modulo changes to the overall list size), but if you are only touching one package it'll always be in shard 1. (And if you touch, say, 3 packages, they will be in shards 1, 2, and 3.)

**Review by stuartmorgan — APPROVED** [review]
LGTM

But also, yuck :( If we have a simple repro case for the handler not being reliable in Xcode 15 we should report it to Apple.

**Comment by vashworth** [comment]
> LGTM
> 
> But also, yuck :( If we have a simple repro case for the handler not being reliable in Xcode 15 we should report it to Apple.

Yeah unfortunately it's not consistent, I had to run it a bunch of times to reproduce. Also, there's a forum open about it and one of the people filed a Feedback ticket https://developer.apple.com/forums/thread/737880

**Pull request merged**
