### PR TITLE
Allows redirect method to return same location

### PR DESCRIPTION
**Pull request by chunhtai**
fixes https://github.com/flutter/flutter/issues/106214

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by johnpryan — APPROVED** [review]

**Comment by ahmednfwela** [comment]
on pub.dev for v5.1.3 it states that uri and path parameters should be in GoRouter, but they aren't https://pub.dev/documentation/go_router/5.1.3/go_router/GoRouter-class.html
did this PR override the 5.1.2 one ?

image

**Comment by chunhtai** [comment]
@ahmednfwela oops I think I messed up the change log, I will fix it.

You can now use GoRouterState.of(context) to access the uri and path parameters

**Comment by ahmednfwela** [comment]
@chunhtai but what if I don't have the context (e.g. in controller-based architecture) ? how can I access the path parameters ?

**Comment by chunhtai** [comment]
> @chunhtai but what if I don't have the context (e.g. in controller-based architecture) ? how can I access the path parameters ?

use a `Builder` widget

**Comment by ahmednfwela** [comment]
what I mean is accessing the parameters outside the flutter widget tree, where I am relying entirely on the `GoRouter` instance to listen for notifications and access path parameters

**Comment by chunhtai** [comment]
@ahmednfwela That is a use case i have not thought about, can you open an issue so that we can discuss in there?

**Comment by ahmednfwela** [comment]
@chunhtai I have opened https://github.com/flutter/flutter/issues/114642

**Pull request merged**
